### ISSUE TITLE
Laravel Inspired AR implementation

### ISSUE THREAD

**Issue by jspringe** [DirectoryTree/LdapRecord#1]
- LdapRecord Version: master
- LDAP Type: any
- PHP Version: 7.2.18

I think the name 'Providers' should go away. They should just be called 'Connections'. This is basically a specialized database library and those providers define the schema and the connection similar to a database connection in Laravel.

I also think that models shouldn't have a `Builder` dependency but a `Connection` dependency. Again, following the Laravel way. As I did in the other branch - you could get a `Builder` from the connection when needed. Also we should strive for something like the below:

    $user = new User(['cn' => 'Common Name', 'first_name' => 'Common', 'last_name' => 'Name']);
    $user->save();

Because of LDAP there would be a need for a DSL or some sort of translator.

Also models should have `toArray()`. There's a host of things to discuss there - like should Guids be converted as an example.

I have some other ideas but let's have some discussion and I'll provide some actual code to show you what I have in mind.

**Comment by stevebauman** [comment]
Thanks for all your input lately @jspringe! It’s much appreciated :smile:

I definitely agree with you about Providers. I’m looking to closely resemble Laravel’a fluent API as much as possible - I really enjoy its simplicity.

I also agree about the query Builder being a dependency for creating models - I wasn’t sure how I was going to work around it, but your recent PR is one step closer to that being removed and I’m really happy about it.

For models having the `toArray()` method - I also completely agree. I can add this to the [HasAttributes](https://github.com/Adldap2/Adldap2/blob/master/src/Models/Concerns/HasAttributes.php) trait which would be a perfect place for it.

I would definitely like to keep hearing your thoughts and suggestions!

**Comment by jspringe** [comment]
I personally hate traits, but if we're aiming for Laravel than go whole-assed into it and own it - don't half ass it.

This might mean some major changes in model, but let me think on it a bit and I'll see if I can pull together a request. Would you prefer it here or on the other?

**Comment by stevebauman** [comment]
> I personally hate traits, but if we're aiming for Laravel than let's go whole-assed into it and own it - don't half ass it.

Traits are perfect for what is needed by the model - they give us modular code needed for accessing LDAP functionality that is shared across multiple object types (group memberships for example). Without traits, the only solution I know of would be to implement an interface for each type of functionality required and then have the exact same code implemented in each model.

I'm prepared to go whole-assed - I don't do half-assed 👍 

> This might mean some major changes in model, but let me think on it a bit and I'll see if I can pull together a request. Would you prefer it here or on the other?

I'd prefer it on the Adldap2 repository if possible. I'm looking to lock an upcoming Adldap2 release and then migrate over to LdapRecord which will take over exactly where Adldap2 left off.

**Comment by stevebauman** [comment]
Hey @jspringe! I was wondering if you could test out LdapRecord in its current state at some point and let me know your thoughts?

I somewhat in the final stages now for a full AR implementation, with working relationships.

For example, here's the some usage:

```php
use LdapRecord\Connections\Container;
use LdapRecord\Connections\Connection;
use LdapRecord\Models\ActiveDirectory\Group;

$connection = new Connection([
    'hosts' => ['192.168.1.1'],
    'base_dn' => 'dc=acme,dc=org',
    'username' => 'user',
    'password' => 'secret',
]);

Container::add($connection);

$group = Group::find('Accounting');

// Getting group members
$members = $group->members()->get();

// Getting groups that the group is apart of
$groups = $group->groups()->get();

// Attaching groups
$otherGroup = Group::find('Staff');

$group->groups()->attach($otherGroup);

// Detaching groups
$group->groups()->detach($otherGroup);

// Detaching all groups
$group->groups()->detach();
```

Let me know what you think! :smile:

**Comment by stevebauman** [comment]
[First beta release is out](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.0.0-beta)!
