### ISSUE TITLE
Confuse with setAttribute and setFirstAttribute

### ISSUE THREAD

**Issue by Albvadi** [DirectoryTree/LdapRecord#102]
**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.3.9
 - Version: v1.2.2

Hi Steve,
testing the new version, I have encountered a problem that I don´t if it´s a bug or I don´t understand the methods well...

Due to LDAP's multi-valued nature, I know that all the attributes are arrays, so because of this, exists two methods to get the attributes: `getAttribute()` and `getFirstAttribute()`.

```php
$user->getAttribute("mail");

array:1 [▼
  0 => "old-mail@company.com"
]
```

```php
$user->getFirstAttribute("mail")

"old-mail@company.com"
```

All right until here.
With this in mind, when I set attributes, I use the same logic: `setAttribute()` for setting an array with different values and `setFirstAttribute()` for setting an string as unique value... but the results don´t are what I expected when I use `getAttribute()` to obtain the result array:

```php
$user->setFirstAttribute('mail', "newMail@company.com");

array:2 [▼
  0 => "old-mail@company.com"
  1 => "newMail@company.com"
]
```

```php
$user->setAttribute('mail', "newMail@company.com");

array:1 [▼
  0 => "newMail@company.com"
]
```
I expect exactly the same results because I setting a string that must be converted in array with only one value.
Or I expect at most the inverse results, the array with all values (old and new) when I set with `setAttribute()` (append the new to the old) and get only the new value with `setFirstAttribute()`..

It´s this a bug? Or really I don´t understad well the use of the methods??

Thanks as allways for ths awesome project!

P.S: I tested in old version of Adldap2 (v8.1.5) and all it´s working as expected, I obtain an array with only one item when I use both methods.

**Comment by stevebauman** [comment]
Hi @Albvadi, thanks for the report!

I agree with you, this isn't intended, I'm honestly surprised I implemented it this way...

Update coming shortly!
