### ISSUE TITLE
groups can not be retrieved when DN includes brackets

### ISSUE THREAD

**Issue by TravisWilder** [DirectoryTree/LdapRecord#105]
Hello

the command $user->groups() is failing, if the DN of the user includes brackets " ( ) ".

Error:
ldap_search(): Search: Bad search filter

example DN (which is valid in AD)

CN=Travis Wilder (external),OU=Office,DC=contos,DC=com

User::find("CN=Travis Wilder (external),OU=Office,DC=contos,DC=com") is working fine

**Comment by stevebauman** [comment]
Hi @TravisWilder,

I believe this is due to improper escaping in the relationship, looking into this now, thanks!

**Comment by stevebauman** [comment]
Fixed, release coming out as soon as tests pass, thanks!

**Comment by TravisWilder** [comment]
Hi
I can confirm : It is working now - thanks for the fast support
