### ISSUE TITLE
Discussion / Support?

### ISSUE THREAD

**Issue by laurin1** [DirectoryTree/LdapRecord#108]
Sorry to hijack Issues, but I don't know how else to ask...

I am trying to migrate from adLDAP to LdapRecord, but I just can't figure it out. Seems like this project has not got much traction, as I can't find a single forum where it's being actively discussed. I hope that I am wrong about that. Where can I go for community support/discussion?

**Comment by stevebauman** [comment]
Hi @laurin1!

Please feel free to ask anything here and create issues, I want everyone to feel comfortable doing so.

Though, do you think having a repository dedicated to discussions would be better suited? Such as a DirectoryTree/LdapRecord-Discussions repo (at least until GitHub discussions is fully out of beta)?

> I am trying to migrate from adLDAP to LdapRecord, but I just can't figure it out.

I've been working on a migration guide from Adldap2, but there's still a lot of work to do on it. I created this separate repository / company as to have it's own identity. I did this to honestly make it easier on myself, so I didn't have to worry about backwards compatibility and migration. Doing so would have made it an even greater task for me to do this single handedly (I am a lone dev, after all).

I'd be happy to help you migrate, as I've migrated all of my own projects (3 at the time of writing) to it without much pain.

> Seems like this project has not got much traction, as I can't find a single forum where it's being actively discussed.

I don't expect people to migrate for **at least** a year or two. It took almost 4 years for Adldap2 to gain a large audience, and I expect the same here.

Please let me know your thoughts. All feedback is **immensely** important to me -- I really do value it! 👍

**Comment by laurin1** [comment]
Wow, thanks for the fast, detailed (and tolerant) response. :) I'm migrating from adLDAP and pain seems to be the watchword as I've spent hours and I am having serious difficulty understanding the basics of how this library is supposed to be used. 

Basic example. How do I get all the objects in an OU? In adLDAP, these were called "Folders".

**Comment by laurin1** [comment]
I just figured out one way is to change the base_dn for that query. Surely there is a better way?

**Comment by laurin1** [comment]
Oh, I can use setDn(). 

As to the issue of a forum, I guess I'm trained to not use Issues for discussion (people normally don't like that), but if you are ok with us using it this way, I'm fine with that.

**Comment by stevebauman** [comment]
No problem @laurin1! I can definitely help you out.

> Basic example. How do I get all the objects in an OU? In adLDAP, these were called "Folders".

One of the main differences with LdapRecord and Adldap2, is that with LdapRecord, mostly all operations are done with *individual* model classes, rather than using a *single* `Adldap` instance.

For example, to get all objects in an OU, use the plain `Entry` model, and use the `in()` method:

```php
use LdapRecord\Models\ActiveDirectory\Entry;

$objects = Entry::in('ou=Users,dc=local,dc=com')->get();
```

You can also locate the OU first, and pass it directly inside:

```php
use LdapRecord\Models\ActiveDirectory\Entry;
use LdapRecord\Models\ActiveDirectory\OrganizationalUnit;

$ou = OrganizationalUnit::findOrFail('ou=Users,dc=local,dc=com');

$objects = Entry::in($ou)->get();
```

**Comment by stevebauman** [comment]
> Oh, I can use setDn().

Yup absolutely, `setDn()` and `in()` perform the same task -- you can use either or:

```php
use LdapRecord\Models\ActiveDirectory\Entry;

$objects = Entry::setDn('ou=Users,dc=local,dc=com')->get();
```

**Comment by laurin1** [comment]
> ```
> use LdapRecord\Models\ActiveDirectory\Entry;
> 
> $objects = Entry::in('ou=Users,dc=local,dc=com')->get();
> ```

Here's on the things that threw me - you are using the in() method static, but that method is not declared as static. Why?

**Comment by stevebauman** [comment]
> As to the issue of a forum, I guess I'm trained to not use Issues for discussion (people normally don't like that), but if you are ok with us using it this way, I'm fine with that.

Yea I agree, though it seems like the easiest option. I'm excited for Github discussions to come out, but I don't really want to have separate forum software where people need to register and activate their account to create a forum post.

**Comment by stevebauman** [comment]
> Here's on the things that threw me - you are using the in() method static, but that method is not declared as static. Why?

This is how Eloquent works in Laravel, and I wanted to port much of it's functionality to an LDAP equivalent. You can see here how it works: 

https://github.com/DirectoryTree/LdapRecord/blob/0ece5e5c2ddc13bd23c5afb86f6ad1889dccf345/src/Models/Model.php#L148-L176

If the method doesn't exist on the model, it is dynamically passed to a new query instance instead, allowing you to fluently query models easily.

**Comment by stevebauman** [comment]
For example, here's a comparison to Adldap2 and LdapRecord for the same query:

**Adldap2:**
```php
$user = $provider->search()->users()->where('mail', '=', 'sbauman@local.com')->first();
```

**LdapRecord:**
```php
$user = User::where('mail', '=', 'sbauman@local.com')->first();
```

**Comment by laurin1** [comment]
> > Here's on the things that threw me - you are using the in() method static, but that method is not declared as static. Why?
> 
> This is how Eloquent works in Laravel, and I wanted to port much of it's functionality to an LDAP equivalent. 

You don't happen to use PhpStorm do you and know a way to make the IDE play nice with this design? I can suppress warnings if necessary.

**Comment by laurin1** [comment]
I'm still confused as to how to do some basic operations. Like, how do I get all the users in a group (and that needs to be a recursive search)?

**Comment by stevebauman** [comment]
> You don't happen to use PhpStorm do you and know a way to make the IDE play nice with this design? I can suppress warnings if necessary.

I do use PhpStorm - I've added various `@mixin` annotations in each base model class to prevent "Method not found" IDE errors: 

**Base**:
https://github.com/DirectoryTree/LdapRecord/blob/0ece5e5c2ddc13bd23c5afb86f6ad1889dccf345/src/Models/Model.php#L19

**Active Directory**:
https://github.com/DirectoryTree/LdapRecord/blob/0ece5e5c2ddc13bd23c5afb86f6ad1889dccf345/src/Models/ActiveDirectory/Entry.php#L13

**OpenLDAP**
https://github.com/DirectoryTree/LdapRecord/blob/0ece5e5c2ddc13bd23c5afb86f6ad1889dccf345/src/Models/OpenLDAP/Entry.php#L11

It won't provide auto-completion on the initial static method calls, but it will show that the methods exist and allow auto-completion afterwards, rather than a missing method:

<img width="482" alt="Screen Shot 2020-04-20 at 10 59 20 AM" src="https://user-images.githubusercontent.com/6421846/79766549-1e4ab680-82f6-11ea-99a9-30491f264be9.png">

<img width="551" alt="Screen Shot 2020-04-20 at 11 04 29 AM" src="https://user-images.githubusercontent.com/6421846/79767008-be084480-82f6-11ea-89c0-84bfc19af7bf.png">

<img width="482" alt="Screen Shot 2020-04-20 at 11 00 42 AM" src="https://user-images.githubusercontent.com/6421846/79766617-3589a400-82f6-11ea-800b-01a9be9ae090.png">

Do you use Laravel? Or do you use a different framework?

**Comment by stevebauman** [comment]
> I'm still confused as to how to do some basic operations. Like, how do I get all the users in a group (and that needs to be a recursive search)?

I guess I need to work on my documentation 😅. I see there isn't really a place currently describing this. I'll work on this now.

LdapRecord new uses [relationships](https://ldaprecord.com/docs/model-relationships), much like Eloquent does to access things like users groups, group members, primary group, and more.

This is how you get a users groups:

```php
$user = User::find('cn=Steve Bauman,dc=local,dc=com');

$groups = $user->groups()->recursive()->get();
```

And vice-versa:

```php
$group = Group::find('cn=Accounting,dc=local,dc=com');

$members = $group->members()->recursive()->get();
```

**Comment by laurin1** [comment]
> Do you use Laravel? Or do you use a different framework?

No. We use a proprietary framework that I (primarily) built (hope to open-source it eventually).

What is the difference between these 2?

```php
$group = Group::find('cn=Accounting,dc=local,dc=com');

$members = $group->members()->recursive()->get();
```

And this:

```php
members = User::where('memberOf', '=', 'cn=Steve Bauman,dc=local,dc=com')->get();
```

**Comment by stevebauman** [comment]
Well:

1. The first example is recursive, the second example is not. For the second example, do you mean?:

```php
$members = User::where('memberOf', '=', 'cn=Accounting,dc=local,dc=com')->get()
```

2. The first example will also include a collection of **all** members, such as `Group`, `Contact` and `User` models, while the second example will only return `User` models.

**Comment by laurin1** [comment]
Sorry, yes, I was trying to work from our example (apples to apples) and messed that up. I should have just given you mine.

**Comment by laurin1** [comment]
I am running into issues that seem like bugs. Here is one. This works:

```php
$group = Group::find('CN=IntranetTest1,OU=Testing,OU=IT,DC=pridedallas,DC=com');

$members = $group->members()->recursive()->get();
```

But this one fails with an exception:

```php
$group = Group::find('CN=IT,OU=Departments,OU=Security Groups,DC=pridedallas,DC=com');

$members = $group->members()->recursive()->get();
```

With this error:

```
BadMethodCallException : Call to undefined method LdapRecord\Query\Model\ActiveDirectoryBuilder::members()
 C:\inetpub\Intranet_Local\vendor\directorytree\ldaprecord\src\Query\Builder.php:1705
 C:\inetpub\Intranet_Local\vendor\directorytree\ldaprecord\src\Models\Model.php:162
 C:\inetpub\Intranet_Local\vendor\directorytree\ldaprecord\src\Models\Relations\OneToMany.php:106
 C:\inetpub\Intranet_Local\vendor\tightenco\collect\src\Collect\Support\Traits\EnumeratesValues.php:178
 C:\inetpub\Intranet_Local\vendor\directorytree\ldaprecord\src\Models\Relations\OneToMany.php:109
 C:\inetpub\Intranet_Local\vendor\directorytree\ldaprecord\src\Models\Relations\OneToMany.php:71
 C:\inetpub\Intranet_Local\vendor\directorytree\ldaprecord\src\Models\Relations\Relation.php:127
 C:\inetpub\Intranet_Local\vendor\directorytree\ldaprecord\src\Models\Relations\Relation.php:109
 C:\inetpub\Intranet_Local\library\Intranet\LDAP.php:100
 C:\inetpub\Intranet_Local\phpunit\library\Intranet\LDAPTest.php:127
```

The exception seems to be caused by "->recursive()", if I remove that, I do not get the exception.

**Comment by stevebauman** [comment]
> But this one fails with an exception:

```php
$group = Group::find('CN=IT,OU=Departments,OU=Security Groups,DC=pridedallas,DC=com');

$members = $group->members()->recursive()->get();
```

Is this the entire code sample that's being ran?

This leads me to believe there's an unfinished query that is being called:

```
BadMethodCallException : Call to undefined method LdapRecord\Query\Model\ActiveDirectoryBuilder::members()
```

Can you post the whole namespace of the `Group` class you are querying?

**Comment by laurin1** [comment]
I broke it down so that I knew it was complete (this is not actually what I want, but this does fail):
```php
		Container::addConnection(
			LDAPConnection::getConnection());
		
		$group = Group::find('CN=IT,OU=Departments,OU=Security Groups,DC=pridedallas,DC=com');

		$members = $group->members()->recursive()->get();
```

**Comment by laurin1** [comment]
Ah, scratch that, bad test. Let me rework it.

**Comment by stevebauman** [comment]
Ah you're totally right @laurin1, I'm able to reproduce this on my end 🤦

Thanks a ton for reporting! Patching now :smile:

**Comment by laurin1** [comment]
Wonderful. I thought I was going crazy.

**Comment by stevebauman** [comment]
Lol definitely not! A new release coming out as soon as tests pass 👍

**Comment by stevebauman** [comment]
[v1.4.3](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.4.3) is out with this patch 🎉

**Comment by laurin1** [comment]
Thanks. Installed. Working.

**Comment by laurin1** [comment]
Here's another thing that has me confused. I want an array of all the user objects:

$aReturn = User::get();

I realized it has a Collection, one of those internal properties is items, which is not accessible. I don't want to iterate to pull out those items. Is there another way?

**Comment by stevebauman** [comment]
Yup absolutely, you call `toArray()` after getting a result from a query:

```php
$aReturn = User::get()->toArray();
```

LdapRecord uses Laravel collections, just as Adldap2 does, so you can call any of the methods shown in the Laravel docs here:

https://laravel.com/docs/collections#available-methods

**Comment by laurin1** [comment]
I've got a problem with getting the GUID. With adLDAP, these were pulled out like this:

![image](https://user-images.githubusercontent.com/75857/79866402-560f3800-83a2-11ea-92ad-f7a4629bda89.png)

But with LdapRecord, these are pulled out like this:

![image](https://user-images.githubusercontent.com/75857/79866446-6cb58f00-83a2-11ea-90f8-804c0846abf7.png)

I need these to be in alphanumeric format.

**Comment by stevebauman** [comment]
Hey @laurin1 -- new docs will be published today for Active Directory user and group management, and I've created the discussions repository ([LdapRecord-Discussions](https://github.com/DirectoryTree/LdapRecord-Discussions)).

Work continues on a migration guide for Adldap2 -- so stay tuned for that 👍
