### ISSUE TITLE
php artisan ldap:import ldap , Provider [ldap] is not configured for LDAP authentication.

### ISSUE THREAD

**Issue by scramatte** [DirectoryTree/LdapRecord#112]
I've setup LdapRecord on Laravel 6 project. 
I'm able to authenticate correclty so looks that setup is fine. 

Now I'm trying to sync_attributes when  I exec
php artisan ldap:import ldap

It returns me the following. error
Provider [ldap] is not configured for LDAP authentication.

Any idea of what occurs here ?

**Comment by stevebauman** [comment]
Hi @scramatte,

Can you post your `auth.php` file?

**Comment by stevebauman** [comment]
Whichever provider you setup inside of your `config/auth.php` must be sent with the LDAP import command. Here’s the docs:

https://ldaprecord.com/docs/laravel/auth/importing/#running-the-command
