### ISSUE TITLE
Can't create OpenLdap OrganizationalUnit

### ISSUE THREAD

**Issue by MajuTo** [DirectoryTree/LdapRecord#115]
**Describe the bug**
ErrorException: ldap_add(): Add: Invalid DN syntax

**To Reproduce**
1. OrganizationalUnit::create(['ou' => 'test'); // With Laravel

**Expected behavior**
The organozational unit should be created.

**Environment (please complete the following information):**
 - LDAP Server Type: OpenLDAP 
 - PHP Version: 7.4

WorkAround : 
OU can be created ba adding the same getCreatableRdn function as the OU class for AD : 

    /**
     * Get a creatable RDN for the model.
     *
     * @return string
     */
    public function getCreatableRdn()
    {
        $name = $this->escape($this->getFirstAttribute('ou'))->dn();

        return "ou=$name";
    } 

Is it possible to add it to OpenLdap OrganizationalUnit class ?

**Comment by stevebauman** [comment]
Thanks @MajuTo! Just pushed a fix.

**Comment by MajuTo** [comment]
It seems you modified Group model instead of OrganizationalUnit :D

**Comment by stevebauman** [comment]
Whoops! Haha thanks for that @MajuTo, brain fart 🤯
