### ISSUE TITLE
setOption problem with $value = []

### ISSUE THREAD

**Issue by PetzJohannes** [DirectoryTree/LdapRecord#116]
**Describe the bug**
After deploying my application with LdapRecord to the test server, I cannot get it running.
On my workstation everything is working fine.

I found the following difference:
Workstation: PHP 7.3.16 (RedHat 7 - Remi)
Server: PHP 7.3.11 (Ubuntu)

Exception:
```
ldap_set_option(): Expected non-empty array value for this option in /var/www/xxx/vendor/directorytree/ldaprecord/src/Ldap.php:349
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ldap_set_option...', '/var/www/xxx...', 351, Array)
#1 /var/www/xxx/vendor/directorytree/ldaprecord/src/Ldap.php(351): ldap_set_option(Resource id #267, 18, Array)

```

Problem location:
```
    public function setOption($option, $value)
    {
        return ldap_set_option($this->connection, $option, $value);
    }
```

I search a bit because I needed this right now ^^
I found that the `18` is resolved to the ldap constant 
```
/**
 * Specifies a default list of server controls to be sent with each request.
 * @link https://php.net/manual/en/ldap.constants.php
 */
define ('LDAP_OPT_SERVER_CONTROLS', 18);
```

And this refers to `LdapRecord\Query\Builder.php` `public $controls = [];`.
```
$ldap->setOption(LDAP_OPT_SERVER_CONTROLS, $this->controls);
```

But in my case `$this-controls` is empty.

What I do not know is why 7.3.11 is not throwing the exception, but 7.3.16 throws.

I fixed it by a little workaround:
```
    public function setOption($option, $value)
    {
        if (!$value) {
            return;
        }
        return ldap_set_option($this->connection, $option, $value);
    }
```

And this is currently working in production :S

I searched in the PHP ldap library and found this:
https://github.com/php/php-src/blob/PHP-7.3.11/ext/ldap/ldap.c#L3375
```
php_error_docref(NULL, E_WARNING, "Expected array value for this option");
				RETURN_FALSE;
```

But it did not change for the next versions:
https://github.com/php/php-src/blob/4e330d3d488c232ad5f9769f1fa9471c9b5ad088/ext/ldap/ldap.c#L3375

I edited the `ldaprecord/src/Ldap.php` file and logged out `$option` and `$value`:
```
[2020-04-23 15:54:48] production.DEBUG: 17  
[2020-04-23 15:54:48] production.DEBUG: 3  
[2020-04-23 15:54:48] production.DEBUG: 20485  
[2020-04-23 15:54:48] production.DEBUG: 5  
[2020-04-23 15:54:48] production.DEBUG: 8  
[2020-04-23 15:54:48] production.DEBUG:   
[2020-04-23 15:54:48] production.DEBUG: 18  
[2020-04-23 15:54:48] production.DEBUG: array (
)  

```

As you can see for other options (e.g. 8) it seems okay to be `null`.

8 refers to `LDAP_OPT_REFERRALS` which is an integer value (https://github.com/php/php-src/blob/0810fcd0d0eb907b79b9619f73dc7d13aed5c611/ext/ldap/ldap.c#L3007).

**Expected behavior**
No exception for a simple configured ldap connection.

**Environment:**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 7.3.16 (RedHat 7 - Remi)

Do you need more information?

**Comment by stevebauman** [comment]
Hi @PetzJohannes, thanks for posting such a detailed issue, this really helps!

I've never experienced or seen this before... Strange. It sounds like a PHP bug, but if we can patch it then I'd definitely take that route.

The `LDAP_OPT_REFERRALS` option is set here in the connection:

https://github.com/DirectoryTree/LdapRecord/blob/b3cbe46f89fede61bb878f37161364ff381447b7/src/Connection.php#L137

Have you defined a value for that option?

**Comment by PetzJohannes** [comment]
Hi @stevebauman

the option you wrote is working correctly. It's an integer option and was just an example to see integer values can be `null`. 

The option not working is `LDAP_OPT_SERVER_CONTROLS`. It's an `array` and is not allowed to be empty (`[]`). 

Thanks for the fast reply.

**Comment by stevebauman** [comment]
Oh okay I understand now.

We will probably have to use other validation on the `$value` rather than checking if it simply falsy via `if (! $value)`.

I’ll patch this to check if the `$value` is an array, and prevent empty controls being sent.

**Comment by PetzJohannes** [comment]
Okay nice. Yeah `if (! $value)` was just a quick fix to prevent a complete rollback.

I think the validation for an empty array fits better :)

**Comment by PetzJohannes** [comment]
Here is my `default` ldap connection (it's the only one) if you need it.

```
        'default' => [
            'hosts' => [env('LDAP_HOST', '127.0.0.1')],
            'username' => env('LDAP_USERNAME', 'cn=user,dc=local,dc=om'),
            'password' => env('LDAP_PASSWORD', 'secret'),
            'port' => env('LDAP_PORT', 389),
            'base_dn' => env('LDAP_BASE_DN', 'dc=local,dc=com'),
            'timeout' => env('LDAP_TIMEOUT', 5),
            'use_ssl' => env('LDAP_SSL', false),
            'use_tls' => env('LDAP_TLS', false),
            'version' => 3,

            'options' => [
                LDAP_OPT_X_TLS_CACERTFILE => '/etc/ssl/custom.ca',
            ]
        ],
```

**Comment by stevebauman** [comment]
Fixed, thanks @PetzJohannes! 😄 Appreciate the report. I'll have a new version up shortly as soon as tests pass.

**Comment by stevebauman** [comment]
Pasting this here in case for future reference:

http://gcov.php.net/viewer.php?version=PHP_7_2&func=tests&file=ext%2Fldap%2Ftests%2Fldap_set_option_error.phpt

**Test Case**:
```
$link = ldap_connect($host, $port);

$controls = array(
    array(
        array("xid" => "1.2.752.58.10.1", "iscritical" => true),
        array("xid" => "1.2.752.58.1.10", "value" => "magic"),
    ),
    array(
        array("oid" => "1.2.752.58.10.1", "iscritical" => true),
        array("oid" => "1.2.752.58.1.10", "value" => "magic"),
        "weird"
    ),
    array(
    ),
);

foreach ($controls as $control)
    var_dump(ldap_set_option($link, LDAP_OPT_SERVER_CONTROLS, $control));
```

**Expected**:

```text
Warning: ldap_set_option(): Expected non-empty array value for this option in %s on line %d
bool(false)
bool(false)
```

**Comment by stevebauman** [comment]
[v1.5.1](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.5.1) is released with this patch, thanks again for you detective work on this one @PetzJohannes!

**Comment by PetzJohannes** [comment]
Thank you :) You are fast. I will schedule an update tomorrow at work.

**Comment by stevebauman** [comment]
I've rolled back this change due to #125, which is reproducible on my end with every PHP version I've tested. I'll do some more playing, but I would suggest updating PHP first to its next minor version.

Going to do some more investigation in the meantime 👍
