### ISSUE TITLE
Add recursive capability to isDescendantOf & isAncestorOf

### ISSUE THREAD

**Issue by kkatpcc** [DirectoryTree/LdapRecord#127]
**Is your feature request related to a problem? Please describe.**
The current implementation of the `isDescendantOf` and `isAncestorOf` methods of the `LdapRecord\Models\Model` class are non-recursive. While the [documentation](https://ldaprecord.com/docs/models/#comparing-models) indeed indicates this as the intended behavior, such usage is not intuitive with respect to the usual unbounded meaning of the terms _descendant_ and _ancestor_.

**Describe the solution you'd like**
In order not to break existing code, I would like to initially suggest adding an optional second boolean parameter to the aforementioned methods representing whether the comparison should be recursive or not, which would default to the current non-recursive behavior, e.g. `$recursive = false`.

**Describe alternatives considered**
One alternative would be to change the behavior of `isDescendantOf` and `isAncestorOf` to be always recursive, while adding something like `isChildOf` and `isParentOf` for the non-recursive counterparts. This could be combined with the above initial suggestion and be phased in over time, perhaps with deprecation notices, as not to catch users by surprise.

**Additional context**
Related commit comment: https://github.com/DirectoryTree/LdapRecord/commit/f2a4a3a9ad94547e9d67a7de265f9665984c204a#commitcomment-38808641

**Comment by stevebauman** [comment]
Hi @kkatpcc, thanks! Appreciate the creation of the issue.

I'm going to consider this a bug so `isDescendantOf` and `isAncestorOf` work properly and returned the expected result. I'm also going to add your suggested methods `isChildOf` and `isParentOf` that preserves the current behaviour.

Give me a couple hours and I'll have this fixed 👍

**Comment by stevebauman** [comment]
Completed.

- `Model::isDescendantOf` and `Model::isAncestorOf` are now recursive
- `Model::isChildOf` and `Model::isParentOf` have been added to replace the current behaviour
- `DistinguishedName` attribute class has been added to perform these comparative operations

New release will be out shortly with these fixes 👍
