### ISSUE TITLE
How to remane or move OU into different OU

### ISSUE THREAD

**Issue by nohnaimer** [DirectoryTree/LdapRecord#128]
**Describe the bug**
How to remane or move OU into different OU? OU = OrganizationUnit

**To Reproduce**
1. Find ou model
2. Create new Dn
3. $ou->move($dn) or $ou->rename($ou->getRnd(), $dn)
4. return false

**Expected behavior**
Need to move one ou to other ou but methods return false

**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.4
 - LdapRecord: 1.6.1

**Comment by stevebauman** [comment]
Hi, please post your code so I can assist you.

**Comment by nohnaimer** [comment]
Hi,
```php
        $dn = $this->owner->getParentDn();
        /** @var OrganizationalUnit $ou */
        $ou = OrganizationalUnit::query()->findByGuid($this->owner->object_guid);
        if ($ou === null) {
            return;
        }

        $data = [];
        if ($this->isNameChanged || $this->isParentChanged) {
            $data[OrganizationalUnit::ATTRIBUTE_NAME] = $this->owner->ad_name;

            $rnd = $this->isNameChanged ?
                'OU=' . addcslashes(addslashes($this->owner->ad_name), ',') : $ou->getRdn();
            $dn = $this->isParentChanged ? $dn : null;

            $ou->rename($rnd, $dn);
            $ou->synchronize();
        }

        if ($this->isDescriptionChanged) {
            $data[OrganizationalUnit::ATTRIBUTE_DESCRIPTION] = $this->owner->description;
            $ou->description = $this->owner->description;
        }

        $ou->save($data);
```
**getParentDn()** - return string like **OU=test,OU=Groups,OU=Accounts,DC=dc,DC=loc**

**Comment by stevebauman** [comment]
Does the OU you're moving contain child entries, such as users or other OUs?

**Comment by nohnaimer** [comment]
> Does the OU you're moving contain child entries, such as users or other OUs?

I try move empty OU without any child entries and get false.

**Comment by stevebauman** [comment]
Is the OU marked as protected against accidental deletion in your AD server?

**Comment by nohnaimer** [comment]
> Is the OU marked as protected against accidental deletion in your AD server?

If you about something like this:
<img width="415" alt="Снимок экрана 2020-05-02 в 22 41 00" src="https://user-images.githubusercontent.com/8865830/80885128-23304280-8cc6-11ea-8b1b-685fbf1c7d32.png">
Option not enabled on all my created ou.

**Comment by stevebauman** [comment]
Hmm everything looks fine honestly... I’m going to try giving this a shot on my end and see if I encounter any issues.

No exceptions are thrown at all when the rename or move fails?

**Comment by stevebauman** [comment]
Just tested this and works fine on my local AD instance -- even with children inside of the nested OU's. I feel like there is an exception being caught or something else may be going on.

Does the account you are binding to your LDAP server with have permission to move these OUs around?

**Comment by nohnaimer** [comment]
> Hmm everything looks fine honestly... I’m going to try giving this a shot on my end and see if I encounter any issues.
> 
> No exceptions are thrown at all when the rename or move fails?

No any exceptions only return false
> Just tested this and works fine on my local AD instance -- even with children inside of the nested OU's. I feel like there is an exception being caught or something else may be going on.
> 
> Does the account you are binding to your LDAP server with have permission to move these OUs around?

I will check the user rights and write later

**Comment by nohnaimer** [comment]
Hi,
You were right, it was account rights.
Thanks for the help.

P.S. Now everything works as it should!

**Comment by stevebauman** [comment]
Awesome thanks for following up @nohnaimer! 😄
