### ISSUE TITLE
How can i create a new user on my active directory?

### ISSUE THREAD

**Issue by kruiz122893** [DirectoryTree/LdapRecord#130]
Hi everyone,
I have a little project which need create users on my own active directory
i can  rich request and list users with Ldap Record in Laravel, but i can not create users:

![image](https://user-images.githubusercontent.com/26779953/81237391-c3cf7c80-8fbc-11ea-9124-f131f2438d4d.png)

![image](https://user-images.githubusercontent.com/26779953/81237404-cd58e480-8fbc-11ea-8039-9f1407753d7f.png)

Ldap Controller

`<?php

namespace App\Http\Controllers;

use App\Ldap\User;
use LdapRecord\Models\Model;
use LdapRecord\Models\Entry;
use LdapRecord\Laravel\Auth\ListensForLdapBindFailure;
use LdapRecord\Models\Events\Saving;

class LdapUserController extends Controller
{

    public function index()
    {
        // $users = User::get();
        // $user = User::find('cn=John Doe,ou=Users,dc=acme,dc=org');

      
        $user = new User();
        $user->cn ='Kevin';
        $user->SamAccountName = 'kevin.ruiz';
        $user->UserPrincipalName = 'kevin.ruiz@corp.amavis.com';
        $user->Name = 'Kevin Ruiz Hernandez';
        $user->GivenName = 'Kevin';
        $user->Surname = 'Ruiz';
        $user->Email = 'kevin.ruiz@corp.amavis.com';
        $user->DisplayName= 'Kevin Ruiz Hernandez';
        $user->save();

    }
}`

ldap\user.php

`<?php

namespace App\Ldap;

use LdapRecord\Models\Model;
use LdapRecord\Models\Entry;
use LdapRecord\Models\Events\Saving;

class User extends Model
{
    /**
     * The object classes of the LDAP model.
     *
     * @var array
     */
    public static $objectClasses = [
        'top',
        'person',
        'organizationalperson',
        'users',

    ];
}
`

Error on my laravel project:

![image](https://user-images.githubusercontent.com/26779953/81237498-06915480-8fbd-11ea-95c1-f45827ac070c.png)

if anyone can help please let me know

**Comment by stevebauman** [comment]
Hi @kruiz122893!

The attribute `Email` does not exist — I believe you’re looking for `Mail`.

Let me know if that resolves your issue!

**Comment by kruiz122893** [comment]
Hi @Steve Bauman<mailto:notifications@github.com>

I I already made the changes you recommended, however the error still continues

ldap_add (): Add: No such attribute in


regards

Kevin Ruiz H

________________________________
De: Steve Bauman <notifications@github.com>
Enviado: miércoles, 6 de mayo de 2020 17:49
Para: DirectoryTree/LdapRecord <LdapRecord@noreply.github.com>
Cc: kruiz122893 <kevin.ru.18@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [DirectoryTree/LdapRecord] How can i create a new user on my active directory? (#130)


Hi @kruiz122893<https://github.com/kruiz122893>!

The attribute Email does not exist — I believe you’re looking for Mail.

Let me know if that resolves your issue!

**Comment by kruiz122893** [comment]
> Hi @kruiz122893!
> 
> The attribute `Email` does not exist — I believe you’re looking for `Mail`.
> 
> Let me know if that resolves your issue!


Hi @Steve Bauman

I I already made the changes you recommended, however the error still continues

ldap_add (): Add: No such attribute in


regards

**Comment by stevebauman** [comment]
Oh, also `surname` is `sn`.

**Comment by kruiz122893** [comment]
I think the attribute `save()` is a really problem

![image](https://user-images.githubusercontent.com/26779953/81418884-9c86c580-910a-11ea-8def-a4132d23234e.png)

**Comment by stevebauman** [comment]
No -- that is a method that persists the changes to your directory. 

I don't believe `name` is also an attribute you can set -- remove it from your code and then it should work.

Hope this helps!

**Comment by stevebauman** [comment]
You also have an error in your defined `$objectClasses` inside of your `Ldap\User.php` model

```php
public static $objectClasses = [
    'top',
    'person',
    'organizationalperson',
    'users', // <-- Incorrect
];
```

```php
public static $objectClasses = [
    'top',
    'person',
    'organizationalperson',
     'user', // <-- Correct
];
```

I would also suggest extending the built-in ActiveDirectory `User` model, rather than defining your own, to avoid these issues:

```php
use LdapRecord\Models\ActiveDirectory\User as BaseModel;

class User extends BaseModel
{
    //
}
```

As a third suggestion, I first test creating users with minimal attributes first (such as only the `cn` attribute) to ensure you are able to create them in your directory, and then start setting more attributes afterwards.

**Comment by kruiz122893** [comment]
Hi @stevebauman really thanks for your help

The solution were net next one:




`
        $user = new User();
        $user->cn ='Kevin Ruiz Hernadez';
        $user->givenname = 'Kevin';
        $user->sn = 'Ruiz';
        $user->title = 'Sofware Engineer';
        $user->department = 'DEV';
        $user->physicaldeliveryofficename = 'SJO';
        $user->employeeid = '1111111';
        $user->pager = '1111111';
        $user->samaccountname = 'kruiz';
        $user->userprincipalname = 'kruiz@corp.amavis.com';
        $user->mail = 'kruiz@corp.amavis.com';
        $user->proxyaddresses = $email = ['SMTP:kruiz@corp.amavis.com','smtp:kruiz@corp.amavis.net'];
        $user->wwwhomepage = 'Kevin18metal';
        $user->name = 'Kevin Ruiz Hernandez';
        $user->DisplayName= 'Kevin Ruiz Hernandez';
        $memberof = ['CN=Office365,CN=Users,DC=corp,DC=amavis,DC=com','CN=TEST1,CN=Users,DC=corp,DC=amavis,DC=com'];
        $user->save();

`


and User.php


`
class User extends Model
{
    /**
     * The object classes of the LDAP model.
     *
     * @var array
     */
    public static $objectClasses = [
 
        'top',
        'User',
        // 'organizationalperson',
    ];
}


`
