### ISSUE TITLE
Is this behavior normal

### ISSUE THREAD

**Issue by nohnaimer** [DirectoryTree/LdapRecord#136]
**Describe the bug**
When attach user to group or group to user use method attach. Work with models.

**To Reproduce**
Add models user to group or group to user use method attach

**Expected behavior**
In Active Directory get audit log:
<img width="768" alt="Снимок экрана 2020-05-17 в 14 10 21" src="https://user-images.githubusercontent.com/8865830/82142923-a4e8aa00-9848-11ea-8674-fb97bc33347f.png">
<img width="769" alt="Снимок экрана 2020-05-17 в 14 05 37" src="https://user-images.githubusercontent.com/8865830/82142925-a619d700-9848-11ea-98bc-2dfe52d04293.png">
<img width="766" alt="Снимок экрана 2020-05-17 в 14 05 49" src="https://user-images.githubusercontent.com/8865830/82142928-aade8b00-9848-11ea-916e-eef8957e8d56.png">

Add and then remove?

**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.4.6

**Comment by stevebauman** [comment]
Hi @nohnaimer,

Can you post your code where you're adding a user to a group?

Everything should be fine. Members are added to groups via `ldap_modify_batch()`. Members should not be removed from anything when being added to another group.

**Comment by nohnaimer** [comment]
```php
/**
     * @param array $objectGuids
     * @return bool
     */
    public function attachGroups($objectGuids): bool
    {
        foreach ($objectGuids as $objectGuid) {
            $group = Group::query()->findByGuid($objectGuid);
            if ($group === null) {
                continue;
            }

            if ($this->groups()->attach($group) === false) {
                return false;
            }
        }

        return true;
    }

/**
     * @param array $objectGuids
     * @return bool
     */
    public function attachUsers($objectGuids): bool
    {
        foreach ($objectGuids as $objectGuid) {
            $user = User::query()->findByGuid($objectGuid);
            if ($user === null) {
                continue;
            }

            if ($this->members()->attach($user) === false) {
                return false;
            }
        }

        return true;
    }
```

**Comment by stevebauman** [comment]
So your logs are reporting that the user is being **added** and then **removed**? Even when you’re only adding a single user to a group?

Is the user being reported in the logs *already* a member of the group?

I need some context of what action is being taken place.

**Comment by nohnaimer** [comment]
> So your logs are reporting that the user is being **added** and then **removed**? Even when you’re only adding a single user to a group?
> 
> Is the user being reported in the logs _already_ a member of the group?
> 
> I need some context of what action is being taken place.

This morning, when adding a user to a group, all users previously added to the group were deleted and only the one that was added remained there. In the logs as the first post, only more appropriations.

**Comment by nohnaimer** [comment]
I try again add user to group and get this log:
<img width="685" alt="Снимок экрана 2020-05-17 в 19 57 34" src="https://user-images.githubusercontent.com/8865830/82154764-c2356c80-9878-11ea-9bbc-0e61385fb80c.png">
id - 4728 create action
id - 4729 delete action
In group it was two employees. Now users are not deleted, but to understand what happened in the morning so that this does not happen again

**Comment by stevebauman** [comment]
Sorry for the troubles @nohnaimer!

Thanks so much for the detailed explanation. You’re right, this is a bug. An `LDAP_MODIFY_BATCH_REPLACE` is being used currently, which is causing this.

Give me a couple hours and I’ll have a tested patch.

**Comment by stevebauman** [comment]
Ok, we're all set. Can you give this a shot using the `dev-master` branch? I created test, and tested this locally on my own AD instance. The proper batch type is now determined from the original value.

- If a value is added, `LDAP_MODIFY_BATCH_ADD` is used.
- If a value is removed, `LDAP_MODIFY_BATCH_REMOVE` is used.
- If a value is added and a value is removed, `LDAP_MODIFY_BATCH_REPLACED` is used.

**Comment by nohnaimer** [comment]
Now delete and create work as they should
<img width="685" alt="Снимок экрана 2020-05-18 в 09 59 27" src="https://user-images.githubusercontent.com/8865830/82183303-66a5c600-98ee-11ea-8f09-dd9b648602ff.png">

**Comment by stevebauman** [comment]
Great thanks for confirming @nohnaimer.

I’ll put out a new release shortly.

**Comment by stevebauman** [comment]
[v1.7.1](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.7.1) has been released with this fix.

Thanks again!
