### ISSUE TITLE
Custom attributes on models

### ISSUE THREAD

**Issue by zoriax** [DirectoryTree/LdapRecord#140]
Hi @stevebauman !

Is there a way to set custom attributes for a model ? I will write an LdapUser model but with only certain attributes and not all in LdapRecord\Models\ActiveDirectory\User.

Thanks for your return !

**Comment by stevebauman** [comment]
Hi @zoriax,

I don't believe I know what you mean, but you can set any attribute on your model by simply setting the attribute:

```php
$user = User::find('cn=John Doe,dc=local,dc=com');

$user->myattribute = 'value';
```

The built-in models do not enforce the setting of any attributes.

You may also find [mutators and accessors useful](https://ldaprecord.com/docs/model-mutators/).

Let me know if this isn't what you were looking for and I will reopen this.

**Comment by zoriax** [comment]
Hi @stevebauman !

Thanks for your replay. 

What I'm looking for is a way to reduce the returned collection because if I get all my users from all() method, it takes about 30 seconds to retrive the entire records. For exemple, I don't need groups in the  model and I don't need certificate. I think I have to bluild my own query with query() method but I rellay need the model

**Comment by zoriax** [comment]
Ok @stevebauman with select() method it works as expected ! 

Thanks
