### ISSUE TITLE
ErrorException: ldap_modify_batch(): A 'values' array must have at least one element

### ISSUE THREAD

**Issue by nohnaimer** [DirectoryTree/LdapRecord#141]
**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.4

My code
```php
        $user = User::query()->findByGuid($this->owner->object_guid);
             $user->userAccountControl = $this->owner->status === DomainUsers::STATUS_ACTIVE ?
                (new AccountControl)->accountIsNormal() : (new AccountControl)->accountIsDisabled();
       $user->save();
```
If save user with (new AccountControl)->accountIsNormal() and the user is already set type (new AccountControl)->accountIsNormal() then get ErrorException: ldap_modify_batch(): A 'values' array must have at least one element in /data/www/ems/vendor/directorytree/ldaprecord/src/Ldap.php:664
Because values = [] - empty array.

Any ideas how to fix?

**Comment by stevebauman** [comment]
Hi @nohnaimer,

That's strange... Let me try this myself and see if I encounter the same issue, thanks!

**Comment by nohnaimer** [comment]
For more details:
<img width="1348" alt="Снимок экрана 2020-05-26 в 18 43 01" src="https://user-images.githubusercontent.com/8865830/82921365-f8fa3980-9f80-11ea-93e8-a8b72db80e79.png">
<img width="1347" alt="Снимок экрана 2020-05-26 в 18 43 28" src="https://user-images.githubusercontent.com/8865830/82921371-fa2b6680-9f80-11ea-829f-e4c00f1dace9.png">
<img width="1316" alt="Снимок экрана 2020-05-26 в 18 43 40" src="https://user-images.githubusercontent.com/8865830/82921376-fb5c9380-9f80-11ea-83d8-66570fb71516.png">

**Comment by stevebauman** [comment]
Thanks @nohnaimer! Just fixed.

You can work around this issue right now by calling `$accountControl->get()` to get the integer value of the `AccountControl` object before setting it on the model attribute.

This was an issue with converting the `AccountControl` object when batch modifications were being built. LdapRecord was recognizing the value as being new, so it applied the wrong type.

A new release will be out shortly that resolves this and I have added a couple of tests to ensure it's fixed 👍
