### ISSUE TITLE
Create new OU?

### ISSUE THREAD

**Issue by malmsteenino** [DirectoryTree/LdapRecord#142]
Sorry but i can't see in the documentation how to create a new OU .
How can I do this?

**Comment by stevebauman** [comment]
Hi @malmsteenino, you create them as you would any other model:

https://ldaprecord.com/docs/models/#creating-amp-updating-models

```php
use LdapRecord\Models\ActiveDirectory\OrganizationalUnit;

$ou = new OrganizationalUnit(['ou' => 'My OU Name']);

$ou->save();
```

**Comment by malmsteenino** [comment]
Oh, sorry for the stupid question...
Thank you very much!

**Comment by stevebauman** [comment]
No such thing as a stupid question @malmsteenino 😄 

I'm happy to help! 👍

**Comment by malmsteenino** [comment]
Thank you !
So can i take advantage of your patience to ask: how can I get a return
value from a $ou->delete() method to be sure that the model is really
deleted?

thanks in advantage

Il giorno mer 27 mag 2020 alle ore 15:06 Steve Bauman <
notifications@github.com> ha scritto:

**Comment by stevebauman** [comment]
The `delete()` method will throw an exception (`LdapRecord\LdapRecordException`) when it fails.

Also, when deletion is successful, the `$model->exists` property is set to `false`.

**Comment by malmsteenino** [comment]
WOW Great man! So i have to use a try/catch block i suppose.

One last question then you will be my hero: is there any way to set the
flag to protected the object from accidental deletion?



Il giorno mer 27 mag 2020 alle ore 17:40 Steve Bauman <
notifications@github.com> ha scritto:

**Comment by stevebauman** [comment]
Yup for sure! Simply:

```php
try {
    $ou->delete();
} catch (\LdapRecord\LdapRecordException $e) {
    // Deletion failed.
}
```

> One last question then you will be my hero: is there any way to set the
flag to protected the object from accidental deletion?

Unfortunately no -- that is not supported in LdapRecord. It involves decoding the complex `ntSecurityDescriptor` attribute and updating it's flags. I'd welcome any PR's that could support this though.

**Comment by malmsteenino** [comment]
Ok thank you very much.
Great framework though.

Il giorno mer 27 mag 2020 alle ore 20:13 Steve Bauman <
notifications@github.com> ha scritto:

**Comment by malmsteenino** [comment]
Hello, i noticed one thing:

If I add a user with setting UserAccountControl = 544 it goes fine and i
have  the flag to "force password change at next login".

If I save the user and then change password the flag to "force password
change at next login" is resetted.

If I try to set UserAccountControl after creating and saving the user I
have an error
ErrorException: ldap_modify_batch(): A 'values' array must have at least
one element in
C:\xampp\htdocs\fwlab\vendor\directorytree\ldaprecord\src\Ldap.php:664
Stack trace: #0 [internal function]:

What's wrong with my method?

Thank you



Il giorno gio 28 mag 2020 alle ore 12:37 Michelangelo Ferilli <
malmsteenino@gmail.com> ha scritto:

**Comment by stevebauman** [comment]
Hi @malmsteenino,

Will need to see your code on how you're currently doing this. I'd also suggest creating another issue so it's easier to track.
