### ISSUE TITLE
toArray() or equivalent in Models

### ISSUE THREAD

**Issue by zoriax** [DirectoryTree/LdapRecord#145]
Hi @stevebauman 

Do you plan to implement a method to get a model as an array ? The same as Laravel collection toArray() ? 

As I can see, the only whay to have the mode is to use
```php
json_decode(json_encode($my_model));
````

It could be really usefull to have a method to retrive the attributes values in "one shot"

Thanks

**Comment by stevebauman** [comment]
Hi @zoriax,

Yup this is already implemented:

https://ldaprecord.com/docs/models/#serialization

https://ldaprecord.com/docs/model-api/#attributesToArray

**Comment by zoriax** [comment]
You are fantastic ! Thank you

**Comment by stevebauman** [comment]
Thanks for the kind words @zoriax! 😄 ❤️
