### ISSUE TITLE
Use of undefined constant LDAP_OPT_PROTOCOL_VERSION

### ISSUE THREAD

**Issue by Braunson** [DirectoryTree/LdapRecord#149]
**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory and OpenLDAP
 - PHP Version: 7.4

**Describe the bug:**

Receiving this on every page.. it's an fatal error:

```
Use of undefined constant LDAP_OPT_PROTOCOL_VERSION - assumed 'LDAP_OPT_PROTOCOL_VERSION' (this will throw an Error in a future version of PHP)
```

**Comment by stevebauman** [comment]
Hi @Braunson,

This means your PHP installation does not have the LDAP extension enabled.

**Comment by Braunson** [comment]
@stevebauman Oh boy, I just noticed after enabling it, I didn't restart my server.. seems resolved now.

**Comment by stevebauman** [comment]
Glad you were able to resolve it @Braunson! 👍

**Comment by imme-emosol** [comment]
Hm.. yes.
I perform filesystem write-actions from my host that runs a minimal php.
I have a read-only docker container that serves my application.
With this additions I was able to publish..
Assuming the functions and constants do not actually effect the publication itself,
perhaps the constants and function checks could be set up in the publish command before publishing..?

```diff
diff --git src/Connection.php src/Connection.php
index b815184b..bde7054a 100644
--- src/Connection.php
+++ src/Connection.php
@@ -12,6 +12,10 @@ use Psr\SimpleCache\CacheInterface;
 use LdapRecord\Events\DispatcherInterface;
 use LdapRecord\Configuration\DomainConfiguration;
 
+if (! defined('LDAP_OPT_PROTOCOL_VERSION')) define('LDAP_OPT_PROTOCOL_VERSION', '17');
+if (! defined('LDAP_OPT_NETWORK_TIMEOUT')) define('LDAP_OPT_NETWORK_TIMEOUT', '20485');
+if (! defined('LDAP_OPT_REFERRALS')) define('LDAP_OPT_REFERRALS', '8');
+
 class Connection
 {
     use DetectsErrors;
diff --git src/Ldap.php src/Ldap.php
index 9a4a02a7..ab42d5fd 100644
--- src/Ldap.php
+++ src/Ldap.php
@@ -2,6 +2,19 @@
 
 namespace LdapRecord;
 
+if (! function_exists('ldap_connect'))
+{
+  function ldap_connect ()
+  {
+  }
+}
+if (! function_exists('ldap_set_option'))
+{
+  function ldap_set_option ()
+  {
+  }
+}
+
 class Ldap extends LdapBase
 {
     /**
```

**Comment by stevebauman** [comment]
Hi @imme-emosol!

I don't think we should be defining functions and constants that are required for LdapRecord to work or be published. The PHP install that is performing the publish or running the application should have the LDAP extension enabled.

Bypassing this requirement could lead to a lot of developer confusion as to why they're actually being defined in the LdapRecord core, but do not actually do anything but prevent errors from occurring on PHP installations that don't have the LDAP extension enabled.

**Comment by imme-emosol** [comment]
I can relate to that. Would an optional extra argument for artisan vendor:publish in LdapRecord-Laravel be acceptable?

**Comment by stevebauman** [comment]
That sounds like it could be doable! How would you implement that? Do you have any thoughts on implementation?

**Comment by imme-emosol** [comment]
Not yet. I will sent a PR to theLdapRecord-Laravel repository if and when I work something out. Thanks so far.
