### ISSUE TITLE
OrganizationalUnit not Found

### ISSUE THREAD

**Issue by kruiz122893** [DirectoryTree/LdapRecord#156]
I have a really problem with the next request

I have 3 active directories and 3 controllers to manage each one

for example Ad1Controller allow me created records on AD1, Ad2Controller allow me created records on AD2 and the same for AD3

I need to created a record on special OU of each Active Directory but i dont found the OU en AD2 or AD3

AD1 works good
![image](https://user-images.githubusercontent.com/26779953/84078913-ef1c0180-a996-11ea-99d6-c11936c3947b.png)

![image](https://user-images.githubusercontent.com/26779953/84078946-fb07c380-a996-11ea-8d20-8051e9663477.png)

BUT AD2 or AD3 :

![image](https://user-images.githubusercontent.com/26779953/84079013-14107480-a997-11ea-8815-5900dcdd60db.png)

![image](https://user-images.githubusercontent.com/26779953/84079336-b4669900-a997-11ea-95a6-550ba758b79a.png)

If i put this on AD2 or AD3  just print the Groups of AD1

![image](https://user-images.githubusercontent.com/26779953/84079153-55088900-a997-11ea-9ad1-987b6ceca5a2.png)

![image](https://user-images.githubusercontent.com/26779953/84079131-491cc700-a997-11ea-8cc0-9850542d4a7c.png)

![image](https://user-images.githubusercontent.com/26779953/84079177-6356a500-a997-11ea-82b6-3adf59bc92a9.png)

**Comment by kruiz122893** [comment]
My solution were: 

![image](https://user-images.githubusercontent.com/26779953/84084760-5343c300-a9a1-11ea-819b-62f39ec48c75.png)

**Comment by stevebauman** [comment]
Great! Glad you were able to resolve it @kruiz122893.

Also, since you're using the built-in `OrganizationalUnit` class, you may need to use the `on()` method to specify the AD connection you would like to use:

```php
$ou = OrganizationalUnit::on('ad2')->findByOrFail('ou=testing,dc=ad2,dc=org');
```

Let me know if you need any further assistance 👍

**Comment by kruiz122893** [comment]
I like your solution, that's why I applied it

Thanks so much
