### ISSUE TITLE
[Bug] Set pwdLastSet value

### ISSUE THREAD

**Issue by nohnaimer** [DirectoryTree/LdapRecord#159]
**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.4.6
 - LdapRecord: 61e6393

**Describe the bug:**
```php
/** @var User $user */
        $user = User::query()->findByGuid($objectGUID);
        if ($user !== null) {
            $user->pwdLastSet = 0;
            $user->save());
        }
```
When run this code take error:
<img width="1668" alt="Снимок экрана 2020-06-10 в 16 33 21" src="https://user-images.githubusercontent.com/8865830/84274099-21189980-ab38-11ea-9751-afbc5d264686.png">
Any ideas?

**Comment by stevebauman** [comment]
[v1.8.0](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.8.0) has been released with this patch. Thanks again!
