### ISSUE TITLE
[Support] Possibility to list filter/directory listing/file listing

### ISSUE THREAD

**Issue by Braunson** [DirectoryTree/LdapRecord#165]
I can't seem to find any methods supporting getting a filter to output a directory or file listing.

**Comment by stevebauman** [comment]
Hi @Braunson,

I’m not sure I understand the question. Can you offer an example of what you’re looking for and what the expected output of this feature would look like?

**Comment by Braunson** [comment]
@stevebauman Apologies, I'm a bit new to working with LDAP. I have a "\\filter" and my end goal is to access a directory and list out files. Can you point me in the right direction if there's a method on doing this in the library?

**Comment by stevebauman** [comment]
No problem @Braunson!

Is LDAP really what you’re looking for? LDAP doesn’t access actual file / folder directories. It accesses company directories of users, computers, groups and more. It’s primarily used to manage user accounts, such as resetting passwords, updating group membership and more.

**Comment by stevebauman** [comment]
Are you looking to mount a network shared drive and access the files and directories inside? If so, this package isn’t what you would use for that. Let me know and I can point you in a direction to do this if so.

**Comment by Braunson** [comment]
@stevebauman Hmm ok, perhaps I got a bit confused. The idea was to validate AD credentials via an API enpoint hosted on a IIS server, then used the credentials to access the "file directories" the user has access to and return a listing of the folders/files in the file server `\\filter0`

**Comment by stevebauman** [comment]
Ok, you wouldn’t use this package. LDAP can’t access an actual file system. It’s basically an API to access a user directory database.

I built a PHP class to do this though, as I needed to access a Windows network share. It may help you:

https://gist.github.com/stevebauman/08025714a7470f387ab34fca4b8e4802
