### ISSUE TITLE
Overuse of static methods

### ISSUE THREAD

**Issue by longshadowdev** [DirectoryTree/LdapRecord#166]
This is more feedback than anything.

Previous user of Adldap2 here looking to upgrade due to an issue I was having with not seeing the reason for authenticating a user not working. For example not being able to see when the password was valid but expired.

I'm starting to use LdapRecord and noting that it heavily uses static methods and static storage. For example in the quick start there is Container::add, which makes Container a god class / global variable structure. It also has Entry::get(), which makes Entry a facade to some 'magic' behind the scenes.

Is it possible to use this framework in an Object Orientated matter instead? For example my Dependency Injection container would ideally be supplied with the container as an object.

**Comment by stevebauman** [comment]
Hi @longshadowdev,

Thanks so much for taking the time to provide feedback, I appreciate it! ❤️ 

> I'm starting to use LdapRecord and noting that it heavily uses static methods and static storage. For example in the quick start there is Container::add, which makes Container a god class / global variable structure.

I've designed LdapRecord around Laravel's Eloquent -- which also uses a static container instance to store database connections and such. The `Container` is basically used to store LDAP connections so models can retrieve them, as well as boot the event listener.

You don't actually have to use the `Container` though. You will just have to override how models get their connection via `resolveConnection` method:

https://github.com/DirectoryTree/LdapRecord/blob/a1ea2387c4813b73f2754a0013267c19ad8245cc/src/Models/Model.php#L320-L350

After that, you can simply use your own container to store your LDAP `Connection`'s, and perform all other tasks through the the `Connection` instances themselves.

> It also has Entry::get(), which makes Entry a facade to some 'magic' behind the scenes.

Yea it's definitely for convenience, but you're free to use the static `Model::query()` method to get a new query instance, or you can call `$connection->query()->model($model)` if you'd prefer.

Here's a full example:

```php
use LdapRecord\Connection;
use LdapRecord\Models\Entry;

$conn = new Connection(['...']);

$model = new Entry();

$query = $model->registerModelScopes(
    $conn->query()->model($model)
);
```

I call the `registerModelScopes` in the above code example as this actually scopes the query by the models `$objectclasses` as well as apply the models global scopes.

> Is it possible to use this framework in an Object Orientated matter instead? For example my Dependency Injection container would ideally be supplied with the container as an object.

I believe so! Like I've mentioned above, you will have to extend the built in models and override the `resolveConnection` method, as well as boot the event listener yourself, but can be done easily.

Does the above answer some of your questions? I truly do value feedback, so let me know! 👍

**Comment by longshadowdev** [comment]
That's an excellent response, yes definitely answers my query. I guess I was trying to work out if it was a deliberate decision or not and seems it is, to make it familiar to Laravel developers.

Your workarounds are definitely sound. I don't intend to use the Model / Active Record part extensively anyway, and your Authentication code in the quick start shows that you can just make a Connection object and attempt to auth against that, which covers my major use case. The above examples definitely show a good workaround too.

Based on this and for now I will just add a connection to my DI container and more or less work off it. When I get to needing Models I will come back to your example, though in the context of using Models the existing API makes more sense to me.

Cheers

**Comment by stevebauman** [comment]
Thanks for your kind words @longshadowdev! It was definitely deliberate. I found using a static container was the easiest way for devs to get up and running, though I understand some feel this is anti-pattern.

That's great that you'll be able to use LdapRecord in the way you want to! I'm always available for discussion and feedback, so please feel welcome to drop by if you have further questions or concerns and I'd be happy to help 👍
