### ISSUE TITLE
[Bug] User must change password at next logon

### ISSUE THREAD

**Issue by Troopster19** [DirectoryTree/LdapRecord#169]
**Environment (please complete the following information):**
 - ActiveDirectory
 - 7.4

**Describe the bug:**
Documentation says to set pwdLastSet to -1 to enable flag but I could only get it to enable when the flag was set to 0.

**Comment by stevebauman** [comment]
Hi @Troopster19,

This is a bug in the docs, apologies! I'll have this fixed momentarily.
