### ISSUE TITLE
[Bug] User::findByGuidOrFail($guid) doesn't work

### ISSUE THREAD

**Issue by MichelFernandes1997** [DirectoryTree/LdapRecord#174]
**Environment (please complete the following information):**
 - LDAP Server Type: Active Directory
 - PHP Version: 7.4

**Describe the bug:**
I need find users in my Active Directory Tree but the method findByGuidOrFail only returns fail. When i use other methods as findByAnrOrFail my user are founded. I have i guid converted and pass this  variable for the method findByGuidOrFail.

try {
    $user = LdapUser::findByGuidOrFail($guid);
} catch (\LdapRecord\Models\ModelNotFoundException $e) {
     dd($e);
}

**Comment by stevebauman** [comment]
Hi @MichelFernandes1997,

Have you ensured that the GUID you are searching for matches identically to the one visible on the returned model using the `findByAnrOrFail` method?

For example, an easy test is this:

```php
try {
    $anrUser = LdapUser::findByAnrOrFail('sbauman');

    $user = LdapUser::findByGuidOrFail($anrUser->getConvertedGuid());
} catch (\LdapRecord\Models\ModelNotFoundException $e) {
    dd($e);
}
```

Also, have you created your own model instance, or are you using the built-in `LdapRecord\Models\ActiveDirectory\User` model?

**Comment by MichelFernandes1997** [comment]
Yeah, my convertedGuid is equals but error persist. My user model is a instance of LdapRecord\Models\Model. Maybe this is the problem?

**Comment by MichelFernandes1997** [comment]
Steve i change my model instance for LdapRecord\Models\ActiveDirectory\User and worked. Sorry for incovenient. I should  see this before. Thanks for your support.

**Comment by stevebauman** [comment]
Awesome @MichelFernandes1997! I’m glad you were able to resolve it. The base model won’t have the configuration needed for Active Directory GUIDs — so that’s why it wasn’t working.

Happy to help! 😄
