### ISSUE TITLE
Get the UserAccountControl in Query[Support]

### ISSUE THREAD

**Issue by RayanAhmadani** [DirectoryTree/LdapRecord#179]
I am trying to run the following search query:
```
$users = $connection->query()->where([
            ['objectclass', '=', 'top'],
            ['objectclass', '=', 'person'],
            ['objectclass', '=', 'organizationalperson'],
            ['objectclass', '=', 'user'],
            ['objectclass', '!=', 'computer'],
        ])->get();
```
The result always omits the attribute 'UserAccountControl ' how I can make it appear in my query result.

**Comment by stevebauman** [comment]
Hi @RayanAhmadani,

If the attribute is missing from your results, the account you have bound to your directory with does not have permission read the attribute, so it is not returned.

Attempt binding with an account that has permission, and that will resolve your issue.
