### ISSUE TITLE
Bypass messages for attach and detach different from error messages returned by OpenLDAP

### ISSUE THREAD

**Issue by dontub** [DirectoryTree/LdapRecord#180]
The methods `attach()` and `detach()` in `HasMany` have bypass messages defined to make nothing happens if attaching an already attached group or detaching a non-attached group. These messages are different from the ones reported by OpenLDAP, though, which results in exceptions.

Attaching an already attached group:
```
[LdapRecord\LdapRecordException (2)]
ldap_mod_add(): Modify: Type or value exists
```

Detaching a non-attached group:
```
[LdapRecord\LdapRecordException (2)]
ldap_mod_del(): Modify: No such attribute
```

Should the bypass messages be configurable?

**Comment by stevebauman** [comment]
Hi @dontub,

Great catch! I do not have an OpenLDAP server, but we must definitely add these exceptions in to bypass them.

Let me update this now.

**Comment by stevebauman** [comment]
Fixed 👍

**Comment by dontub** [comment]
Thanks!
