### ISSUE TITLE
[Bug] getFirstAttribute() does not work with accessor/get mutator

### ISSUE THREAD

**Issue by dontub** [DirectoryTree/LdapRecord#182]
**Environment (please complete the following information):**
 - not relevant

**Describe the bug:**
When an accessor/get mutator is configured `getFirstAttribute()` always returns null because the result of the mutation is passed to `Arr::first()`. The same holds true for attributes configured as dates. For dates it's in any way only possible to access the first date in case there are multiple dates with the same key. I don't know if there is a use case for multiple dates with the same key, though.

**Comment by stevebauman** [comment]
Thanks for the report @dontub! Excellent catch! 👍 

Patching this now 🎉

**Comment by dontub** [comment]
Thanks!
