### ISSUE TITLE
[Bug] hasAttribute() only checks for key existence

### ISSUE THREAD

**Issue by dontub** [DirectoryTree/LdapRecord#183]
**Environment (please complete the following information):**
 - not relevant

**Describe the bug:**
The method `hasAttribute()` only checks for existence of the key in the `$attributes` array. Thus the method returns `true` even if `null` or `[]` is set.

**Comment by stevebauman** [comment]
Hi @dontub, thanks for the report!

I think you're right about this -- it should return `false` with empty values or arrays. Let me patch this now 👍

**Comment by dontub** [comment]
Thanks!
