### ISSUE TITLE
[Feature] Mutators for booleans and numeric values

### ISSUE THREAD

**Issue by dontub** [DirectoryTree/LdapRecord#184]
Similar to dates there could be mutators for booleans and numeric values.

**Comment by dontub** [comment]
I think the transformation should be implemented on a per value basis in difference to the mutators that handle the combination of values. So I would call them de-/normalizer.

Does it make sense to normalize scalars and objects that have a `__toString()` method by default?

**Comment by stevebauman** [comment]
> Similar to dates there could be mutators for booleans and numeric values.

I totally agree with this. 👍 

> Does it make sense to normalize scalars and objects that have a __toString() method by default?

I'm not sure what you mean, could you elaborate a bit and maybe share a code example so I can get a clearer picture?

**Comment by stevebauman** [comment]
Hi @dontub, I've started work on this. Should have this finished in a couple days 👍

**Comment by stevebauman** [comment]
This has been completed. 👍
