### ISSUE TITLE
[Feature] Change name attribute on rename

### ISSUE THREAD

**Issue by dontub** [DirectoryTree/LdapRecord#187]
Renaming a model should change the name attribute as well.
```
$user = User::findOrFail('uid=foo,cn=example,cn=com);
// $user->uid === ['foo']
$user->rename('uid=bar');
// Expectation: $user->uid === ['bar']
```

**Comment by stevebauman** [comment]
Fixed! 🎉 

Thanks for suggestions, fixes and reports @dontub! I really appreciate it. You're helping LdapRecord be the best it can possibly be 👍
