### ISSUE TITLE
[Bug] Import user from Controller : Use of undefined constant STDIN

### ISSUE THREAD

**Issue by jgrunder** [DirectoryTree/LdapRecord#188]
**Environment (please complete the following information):**
 - LDAP Server Type: Active Directory
 - PHP Version: 7.4.5

**Describe the bug:**

Hi,
I want to import a user directly from a controller, but I have an error related to some artisan commands that use something not existing if we don't execute this command through the commandline interface.

Here is my code:
```php
// If the user update was successful in the Active Directory, reimport the user into the local database.
if ($userLdap->update()) {
    Artisan::call('ldap:import ldap ' . $user->username);
    return back()->with('status', 'Profile updated!');
} else {
    return back()->withErrors('Error occured!');
}
```
And the error message (generated from the line `Artisan::call('ldap:import ldap ' . $user->username);` ):
`Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP)`

But if I execute this commande into the terminal, everything is forking fine:
```
vagrant@homestead:~$ php artisan ldap:import ldap jgrunder
Found user [CN=GRUNDER Jonathan].

 Would you like to display the user(s) to be imported / synchronized? (yes/no) [no]:
 >

 Would you like these users to be imported / synchronized? (yes/no) [yes]:
 >

 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Successfully imported / synchronized [1] user(s).
```

Any idea of how can I fix this ? Should I hack artisan file or is there anything to do into LdapRecord artisan command ?

Anyway love this package, thank you for the job!

**Comment by stevebauman** [comment]
Hi @jgrunder,

What class / type of object is the `$userLdap` variable?

I ask because if it is in-fact an LdapRecord model instance, you must use `$userLdap->getFirstAttribute('username')`, because accessing the property itself will *always* return an array which will generate this exception.

Let me know and we can get to the bottom of this 👍 

PS: Thanks so much for your kind words! :smile: I'm glad you like LdapRecord ❤️

**Comment by stevebauman** [comment]
Also, I noticed you are using Active Directory -- you will likely want to use `$userLdap->getFirstAttribute('samaccountname')`, as the `username` attribute does not exist.

**Comment by jgrunder** [comment]
Hi @stevebauman 
Thank you for your quick answer! If only all deposits could be so reactive!

This is my $userLdap variable in an update user method:

```
use LdapRecord\Models\ActiveDirectory\User as LdapUser;

$userLdap = LdapUser::where('samaccountname', $user->username)->firstOrFail(); // $user->username = jgrunder

$userLdap->sn = Str::upper($request->lastname);
$userLdap->givenname = Str::title($request->firstname);
$userLdap->mail = $request->email;
$userLdap->telephonenumber = $request->phone;
$userLdap->physicaldeliveryofficename = $request->office;
$userLdap->description = $request->description;
```
And then we have the update.

I tried with the command `Artisan::call('ldap:import ldap ' . $userLdap->getFirstAttribute('samaccountname'));` and the result is exactly the same.
I've temporary fixed it by adding this line before the Artisan command: `define('STDIN',fopen("php://stdin","r"));` but it is abracadabrantesque

Thanks again ;)

**Comment by stevebauman** [comment]
> Thank you for your quick answer! If only all deposits could be so reactive!

Thanks so much @jgrunder for the sponsorship! I really appreciate it! Let's get your issue fixed 👍 

I'm actually wrong from what I told you above -- you must call it like so:

```php
$args = [
    'provider' => 'ldap',
    'user' => $userLdap->getFirstAttribute('samaccountname'),
    '--no-interaction',
];

Artisan::call('ldap:import', $args);
```

Can you give that a shot and let me know if you succeed?

**Comment by stevebauman** [comment]
I have this programmatic import execution in the docs, but it's missing the `user` argument:

https://ldaprecord.com/docs/laravel/auth/importing/#programmatically-executing

Going to add this in now 👍

**Comment by jgrunder** [comment]
You're awesome!
I missed this part of the documentation, probably because I didn't see any reference to the users, but with the right format the import works correctly, there are no more errors!
I took a sponsor because I'm working on a big AD project for my company and I think I'm going to have some (many) more stupid questions like this :P
Thanks again for your help, and see you (very) soon :D

**Comment by stevebauman** [comment]
Perfect @jgrunder! I'm glad that worked and you were able to resolve it.

> I took a sponsor because I'm working on a big AD project for my company and I think I'm going to have some (many) more stupid questions like this 😅

Wow that's awesome! I'm really glad you chose to use LdapRecord 🎉 . I'll be here every step of the way with whatever questions or concerns you have. Please don't hesitate to create issues and request assistance :smile:
