### ISSUE TITLE
[Feature] Make reload of model on save optional

### ISSUE THREAD

**Issue by dontub** [DirectoryTree/LdapRecord#192]
When a model (wouldn't be record the correct term?) is saved it is re-fetched from LDAP. When it is done a lot of times it harms the performance. Therefore it should be possible to just set `$original` to `$attributes` without re-fetch.

**Comment by stevebauman** [comment]
I agree with this. 👍  My original intention with this was to always keep the attributes up to date. On `$model->update()`'s, a full re-sync should definitely not occur.

The only thing I'm concerned with is virtual attributes not being loaded after a `create()`, such as the users object GUID. So we may only be able to do this after `update()`'s. Thoughts?

**Comment by dontub** [comment]
That  would be fine for me as I'm doing a lot of updates, but only few inserts. Nevertheless there might be use cases where a lot of inserts are done, but the virtual attributes aren't needed.

**Comment by stevebauman** [comment]
Completed -- this will be released in v2, coming soon.

All model changes (inserts, updates, and deletions) will now no longer re-sync the changes with your LDAP server. The model instance will simply be updated with the changes that have been performed locally.

This means, you will now have to call `refresh()` on `create()`, `save()`, `update()`, `createAttribute()`, `deleteAttribute()` and `updateAttribute()`:

```php
$user = User::create(['samaccountname' => 'John Doe']);

$user->refresh();
```

Thanks for your feedback! 👍
