### ISSUE TITLE
[Bug] LDAP time might contain timezone

### ISSUE THREAD

**Issue by dontub** [DirectoryTree/LdapRecord#193]
An LDAP time (`GeneralizedTime`) might contain a timezone, see https://ldapwiki.com/wiki/GeneralizedTime
In that case the conversion to `\DateTime` fails. Though `new \DateTime($value)` should work. When converting `\DateTime` back to `GeneralizedTime` the timezone shouldn't be dropped.

**Comment by stevebauman** [comment]
Thanks @dontub! Going to have a fix for this shortly.

**Comment by stevebauman** [comment]
Done -- timezones are now taken into account when converting to and from LDAP timestamps (LDAP Generalized Time & Windows NT time format).
