### ISSUE TITLE
[Feature] Unlock user account option.

### ISSUE THREAD

**Issue by buczoprazy** [DirectoryTree/LdapRecord#199]
Hi,

I am trying find option to unlock user account.
I could find settings like: 

`'pwdlastset' => -1 `

I can check if user account is locked, but it would be nice to have option to unlock user account please.

```
$user = User::find('cn=John Doe,ou=Users,dc=local,dc=com');

$uac = new AccountControl(
    $user->getFirstAttribute('userAccountControl')
);

if ($uac->has(AccountControl::LOCKOUT)) {
    // This account is locked out.
}

if ($uac->doesntHave(AccountControl::LOCKOUT)) {
    // The account is not locked out.
}
```
[FIX]

```
$ldapUser = User::findByGuid($request->guid);
$ldapUser->lockouttime = 0;
$ldapUser->save();
```

**Comment by stevebauman** [comment]
Hi @buczoprazy,

It wouldn't be worth adding a method for this on the `User`, since you can accomplish this is one line:

```php
$user->update(['lockouttime' => '0']);
```

I've added documentation to cover this though -- thanks!
