### ISSUE TITLE
[Feature] Migrate FreeIPA from Adldap2

### ISSUE THREAD

**Issue by nerdalertdk** [DirectoryTree/LdapRecord#202]
Hi

We use FreeIPA at my work and after some initial startup problems used Adldap2 over a year now.
I just tried using this package and already I see a lot of the same problems as I meet when using Adldap2

Is there any change you guys an migrate your FreeIPA Schema over

https://github.com/Adldap2/Adldap2/blob/master/src/Schemas/FreeIPA.php

**Comment by stevebauman** [comment]
Hi @nerdalertdk,

> I just tried using this package and already I see a lot of the same problems as I meet when using Adldap2

Could you elaborate on this? What problems are you experiencing?

> Is there any change you guys an migrate your FreeIPA Schema over

No -- the schema system was removed in favour of creating your own models. I'd be happy to accept a PR for built-in FreeIPA models! 👍

**Comment by nerdalertdk** [comment]
Yes noticed that, but I think I figured it out

Will make an pull request with my changes

**Comment by stevebauman** [comment]
Ok sounds good!
