### ISSUE TITLE
[Feature] Additional configuration attributes

### ISSUE THREAD

**Issue by leenooks** [DirectoryTree/LdapRecord#207]
Hi, I've started using your library in an updated version of phpldapadmin, and one thing I would like to have is a `name`, being free form text that can be used with a configuration. I'll use this name to show the server name in an LDAP tree.

Currently, if I add a name configuration in ldap.conf, I get an exception *Option name does not exist*.

IE:
```
    'connections' => [
        'default' => [
            'hosts' => [env('LDAP_HOST', '127.0.0.1')],
           ...
            'name' => env('LDAP_NAME','LDAP Server'),
        ],
```

Could you add a new attribute to `src/Configuration/DomainConfiguration.php` (unless there is a better way of doing this?)

**Comment by nerdalertdk** [comment]
you can use the `connections` name.

I've changed `default` to our TLD

**Comment by stevebauman** [comment]
Hi @leenooks, @nerdalertdk is right, you must use the array key storing the connections configuration for the connections name. Hope this helps!

**Comment by leenooks** [comment]
Hmm,, it doesnt :( The connections array key is a key - eg "prod", "dev", "default". I was hoping for an free form text name that can be associated with the key, eg: "prod" = "Production Server in AWS", "dev" = "Development OpenLDAP 2.4", "default" = "OpenLdap Readonly Replica at XXX".

Throughout my code, if I want reference an LDAP server connection - I'd rather be referencing it by its (short) key, not its (long) name.

Is this something that wont be considered?

**Comment by stevebauman** [comment]
Hi @leenooks, I'm not particularly against it, but I haven't heard of any other requests for this, and I also haven't really seen this type of configuration be used in Laravel or Symfony (setting a `name` option in database connection configuration).

You could do this right now by making the association yourself:

```php
$servers = [
    'prod' => 'Production Server in AWS',
    'dev' => 'Development OpenLDAP 2.4',
    'default' => 'OpenLdap Readonly Replica at XXX',
];

$connection = Container::getConnection($name = 'prod');

// 'Production Server in AWS'
$connectionName = $servers[$name];
```

I feel it'd be strange having two names for connections built into the framework. Could you point me to some examples of other packages/libraries/frameworks utilizing this type of configuration so I could gain some knowledge on it's usefulness?

**Comment by leenooks** [comment]
Hi Steve,

Examples of existing packages, where a DB configuration has a "name" associated with it - yes, phpldapadmin: http://olddemo.phpldapadmin.org/ - look at the drop down toggle "select your server".

I'd prefer to have all the configuration in the same place - I'm the developer of phpLDAPadmin - and asking my users to update this in 2 places (if they want to associate a name to an LDAP server, and have more than 1) is not a direction I'm wanting to go.

I'm updating PLA with modern frameworks and methods - and I was exploring including your library in it - saves me from reworking updating my existing library. That's not set in stone yet, as I'm still learning what you've created and its suitability for PLA (but on the surface it seemed a good fit).

If this is not something you wanting to add to your library - no problem, as I'll probably work something out.

**Comment by stevebauman** [comment]
Hi @leenooks!

I've just added this in. It will be released in v2.0 (which should be out in the next couple weeks).

Here's how it works:

```php
use LdapRecord\Connection;
use LdapRecord\Configuration\DomainConfiguration;

// Add an option available to be set in the configuration:
DomainConfiguration::extend('name', $default = null);

// Create a new DomainConfiguration object:
$config = new DomainConfiguration(['name' => 'Domain 1']);

// Or, simply create a new Connection with your new configuration option:
$connection = new Connection([
    'name' => 'Domain 1',
    '...',
]);

// Then, you can retrieve the value anytime from the configuration object:
// Returns "Domain 1":
$config->get('name');
```

Will that work for you?

**Comment by stevebauman** [comment]
This has been added in [v2.0.0](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.0.0).

**Comment by leenooks** [comment]
Steve, sorry, its been a long time before I've had a chance to come back to this - you know life keeps us occupied :(

Thank you for this - it works well.

Just for folks who are using larval and want to use this - you just need to add this to your `AppServiceProvider::register()` method:

```php
    public function register()
    {
		// Add a new option available to be set in the configuration:
		DomainConfiguration::extend('name', $default = null);
    };
```

🙇‍♂️
