### ISSUE TITLE
[Bug] Pagination returns not more than one page

### ISSUE THREAD

**Issue by dontub** [DirectoryTree/LdapRecord#208]
**Environment (please complete the following information):**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 7.4

**Describe the bug:**

When using `paginate()` the result contains no more than one page. It works as expected if the limit is set to `0` instead of the page size
https://github.com/DirectoryTree/LdapRecord/blob/5d239cb7ca0aec218cf05c2b91fddb25672053cf/src/Query/Builder.php#L424

Actually limit should be handled differently when using pagination. It should be applied on the complete result, e.g. if page size is 100 and limit is 123, the returned collection should not contain more than 123 entries, even though the second page contains more than 23 entries.

**Comment by stevebauman** [comment]
Hi @dontub,

> Actually limit should be handled differently when using pagination. It should be applied on the complete result, e.g. if page size is 100 and limit is 123, the returned collection should not contain more than 123 entries, even though the second page contains more than 23 entries.

**Comment by dontub** [comment]
> I'm not sure what you mean here. Do you mean the returned collection should not contain more than 100 entries when the limit is 100 and the page size is 123?

For example *page size* is 100 and the complete number of entries including all pages is 345.

* Running pagination with *limit* set to 0 would return all 345 entries.
* Running pagination with *limit* set to 400 would return all 345 entries.
* Running pagination with *limit* set to 123 would return the first 123 entries.

> I'm not experiencing this issue you describe -- all entires are returned for me.

The OpenLDAP server has version 2.4.44. Which one do you use?

To reproduce:
* Add 2 entries.
* Use `paginate()` with page size 1.

Result: Only 1 entry is returned.

**Comment by stevebauman** [comment]
> The OpenLDAP server has version 2.4.44. Which one do you use?

I'm using Active Directory. I don't have an OpenLDAP server to test upon, so this type of support has been implemented by the community.

Strange though, I don't receive any errors upon removing the set property. I'll remove this and make a new release. I'm assuming this may be an artifact from Adldap2, or simply my bad implementation.

As always, thanks for the reports @dontub!

**Comment by stevebauman** [comment]
I've created a new release ([v1.11.1](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.11.1)). Thanks again! 🎉
