### ISSUE TITLE
Displaying LDAP Error Messages

### ISSUE THREAD

**Issue by IsraH** [DirectoryTree/LdapRecord#218]
Im trying to display automatically ldap error messages I followed the steps one by one , but it doesn't work, the only message is 'these credentials does not match our records'.
In AuthServiceProvider the Auth needs an import, but only works the use Illuminate\Support\Facades\Auth;, 
when I try to import the LdapRecord\Laravel\Middleware\Auth; it doesnt find it
Fortify::authenticateUsing(function ($request) {
            $validated = **Auth**::validate([
                'samaccountname' => $request->username,
                'password' => $request->password

Please your help

**Comment by stevebauman** [comment]
Hi @IsraH,

You are importing the correct Auth class. The class you mentioned: `LdapRecord\Laravel\Middleware\Auth` does not exist.

If you are receiving an error message attempting to login, please read the [debugging guide](https://ldaprecord.com/docs/laravel/debugging/) and check your applications logs to see what issue may be occurring.

Hope this helps!
