### ISSUE TITLE
Fetch date of last password change (Pwd-Last-Set attribute) [Feature]

### ISSUE THREAD

**Issue by dirkam** [DirectoryTree/LdapRecord#221]
Is it possible to fetch the Pwd-Last-Set and/or PwdChangedTime attribute with a query? (Active Directory)

If it's not possible yet, can you please consider adding this functionality?

**Comment by stevebauman** [comment]
Hi @dirkam,

This is definitely already possible, and will be returned with user objects -- **as long as the account you are binding to your Active Directory server has permissions to read the attribute**.

Here's an example of retrieving the users `pwdLastSet` attribute:

```php
$user = User::find('cn=John Doe,dc=local,dc=com');

$passwordLastSet = $user->getFirstAttribute('pwdlastset');
```

Hope this helps!

**Comment by dirkam** [comment]
That's great, thanks!

Any chance to get this with queries made on the connection directly without using the User model?

**Comment by stevebauman** [comment]
Happy to help @dirkam! Yes absolutely:

```php
$results = $connection->query()->whereHas('pwdlastset')->get();

foreach ($results as $user) {
    echo $user['pwdlastset'][0] . PHP_EOL;
}
```

**Comment by dirkam** [comment]
And it just works! Thank you.
