### ISSUE TITLE
[Bug] Groups don't return members if they have the group set as their primary group in Active Directory

### ISSUE THREAD

**Issue by anthonyi91** [DirectoryTree/LdapRecord#223]
- LDAP Server Type:  ActiveDirectory
 - PHP Version: 7.4

The members of a group aren't being returned when the group is set to their primary group in Active Directory. This appears to be similar to issue #119 using v1.12.0. I've tested and it appears it was working between version 1.7.2 & 1.11.1.

- Returns empty:
`$group = Group::where('samaccountname', '=', 'Domain Users')->first();`
`$group->members()->get()`

- Returns the 'Domain Users' group, showing the user is in the group correctly:
`$user = User::where('samaccountname', '=', 'Test User')->first();`
`$user->groups()->get()`

Whilst trying to help narrow down this issue, it appears to be last working in commit bddcd26, using the same code for group member, it returns all of the user models as expected.

In 4bb2113 it returns null, I've manually added each change to my test project and it appears to be the change to src/Models/Relations/Relation.php that causes the error. Hopefully that's enough for you to go on! If there's anything else I can do to help, please let me know.

**Comment by stevebauman** [comment]
Thanks for the report @anthonyi91! I've just patched this, alongside a test. We're all set 👍 .

I'll have a new release created shortly.

**Comment by stevebauman** [comment]
[v1.12.1](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.12.1) has been released with this fix 🎉

**Comment by jzapater** [comment]
In the last release v2.13 I have the same problem with this method:

$user->groups()->recursive()->get();

The method not get recursive the groups of user's Primary Group.

Can you check it ?

Thanks.
