### ISSUE TITLE
Documentation link results in 403 Error[Bug]

### ISSUE THREAD

**Issue by maggz69** [DirectoryTree/LdapRecord#226]
**Environment (please complete the following information):**
 - LDAP Server Type: [e.g. ActiveDirectory / OpenLDAP / FreeIPA]
 - PHP Version: [e.g. 7.2 / 7.3 / 7.4]

**Describe the bug:**

Clicking the link to documentation / quickstart results in a Forbidden error

**Comment by stevebauman** [comment]
Fixed, thanks! Sorry about that.
