### ISSUE TITLE
Import users from Ldap to save in my local DB

### ISSUE THREAD

**Issue by kruiz122893** [DirectoryTree/LdapRecord#229]
Hi @stevebauman  i have little problem with the importing users

auth.php

![image](https://user-images.githubusercontent.com/26779953/100486222-abde5800-30c8-11eb-9eac-2138234bc484.png)

AtributeHandler.php

![image](https://user-images.githubusercontent.com/26779953/100486245-bb5da100-30c8-11eb-87ce-398428643c8d.png)

Error:

The problem is:

I can't save the users which was imported
![image](https://user-images.githubusercontent.com/26779953/100486188-95380100-30c8-11eb-8a30-2b2f51684caa.png)

**Comment by kruiz122893** [comment]
![image](https://user-images.githubusercontent.com/26779953/100486446-8271fc00-30c9-11eb-86ae-39a169f02a0f.png)

**Comment by stevebauman** [comment]
Hi @kruiz122893,

You must insert the trait and interface on your database model:

https://ldaprecord.com/docs/laravel/v1/auth/quickstart/#database-user-model-setup

Also make sure you publish the migration included in the above setup guide.

That should get it working 👍

**Comment by kruiz122893** [comment]
Model:


![image](https://user-images.githubusercontent.com/26779953/100487398-0201ca00-30ce-11eb-862b-30e622593da3.png)


Oh perfect, but i don't want to save on users table, i want to save on this schema


![image](https://user-images.githubusercontent.com/26779953/100487386-f2828100-30cd-11eb-979c-0404754e609b.png)



The error now is:
Column not found: 1054 Unknown column 'guid_column'

![image](https://user-images.githubusercontent.com/26779953/100487422-1cd43e80-30ce-11eb-8d30-6bccb1126f21.png)

**Comment by stevebauman** [comment]
You're returning the wrong column names by suffixing them with `_column`. You also don't need to override those methods unless you have them set differently in the migration.

Simply remove the `getLdapDomainColumn()` and `getLdapGuidColumn()` methods and you're all set 👍
