### ISSUE TITLE
[Bug] Removing groups generates PHP warnings

### ISSUE THREAD

**Issue by Troopster19** [DirectoryTree/LdapRecord#230]
**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.4

**Describe the bug:**

    $group = Group::whereEquals('cn', '_<mygroupname>_')->first();
    $user = User::whereEquals('samaccountname', '_<myusername>_')->first();

    $user->groups()->detach($group);

Gives these warnings when calling the detach:

    PHP Warning:  array_diff(): Expected parameter 2 to be an array, string given in vendor\directorytree\ldaprecord\src\Models\Model.php on line 1172

    PHP Warning:  array_values() expects parameter 1 to be array, null given in vendor\directorytree\ldaprecord\src\Models\Model.php on line 1172

This started after updating from v1.12.1 to v2.0.0 - my code has stayed the same.

**Comment by stevebauman** [comment]
Hi @Troopster19! Thanks for the report 👍 

Can you try `dev-master` and give it another shot? The latest patch should resolve this issue. Once confirmed, I'll put out another release.

**Comment by Troopster19** [comment]
Thanks for the fast reply. I will test tonight after hours and will let you know.

**Comment by Troopster19** [comment]
Looks like that fixed it. Thanks again!

**Comment by stevebauman** [comment]
Happy to help @Troopster19! Thanks again for the detailed report, it really helped me narrow the issue down immediately 👍 

I've just released [v2.0.1](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.0.1) that includes this fix! 🎉
