### ISSUE TITLE
[Question] LDAP with SSL

### ISSUE THREAD

**Issue by alekbless** [DirectoryTree/LdapRecord#232]
Hello!

I was wondering if HTTPS w/certificate must be enabled to use LDAPS? 

For example could my NGINX webserver serve http and when the user logs in, the server authenticates the user with SSL to ldaps://ldap.example.com?

**Comment by stevebauman** [comment]
Hi @alekbless!

No you don't need to serve an HTTPS endpoint for your PHP application to use LDAPS.

Since your web server itself is communicating with your LDAP server and not the client, it's absolutely possible.

Hope this helps! If you have any further questions or concerns let me know! 👍
