### ISSUE TITLE
[Feature] Getting status of a Computer-account (is Disabled?)

### ISSUE THREAD

**Issue by NordicAT** [DirectoryTree/LdapRecord#233]
Hello,

I am testing LdapRecord for the first time and I am using Version v2.0.3.
I worked through the docs multiple times.

I want to retrieve Computer-objects from Microsoft Active Directory and I am using the computer model simply like:

`$AdComputers = Computer::get();`

I am looping through the object and I want to know, if the Computer-account is disabled.
In the docs I find at least information on how to get information about disabled accounts for users. I tried it for users like this:

```
$user = User::find('CN=MyUser,OU=Personal,DC=domain,DC=local');

$status = new AccountControl(
    $user->getFirstAttribute('userAccountControl')
);

if ($status->has(AccountControl::ACCOUNTDISABLE)) {
    echo "The account is locked!";
}
```

This is working fine, but I can not find any information on how to do the same for Computer-objects.

If this is currently not possible I want to know, if it would be able to implement it?

Thank you

**Comment by stevebauman** [comment]
Hi @NordicAT,

You should be able to do the exact same example with a `Computer` model. Have you given it a shot?

**Comment by NordicAT** [comment]
Hello Steve,

Thank you very much for the confirmation. :v:

Shame on me. :pensive:
Of course I tried it before posting, but it seems that I did make a mistake. (Copy & Paste error :grimacing:)
Yes it is working this way.

Just for the record:

```
...    
use LdapRecord\Models\ActiveDirectory\Computer;
use LdapRecord\Models\Attributes\AccountControl;

$AdComputers = Computer::get();

foreach ($AdComputers as $AdComputer) {

	$Status = new AccountControl(
		$AdComputer->getFirstAttribute('userAccountControl')
	);

	if ($Status->has(AccountControl::ACCOUNTDISABLE)) {
		echo "<br>The account is locked! (" . $AdComputer->getFirstAttribute("name") . ")";
	} else {
		echo "<br>The account is NOT locked. (" . $AdComputer->getFirstAttribute("name") . ")";
	}	

}
```

Thank you

**Comment by stevebauman** [comment]
Awesome! No worries at all — always happy to help 😄 

Glad it’s working and you’re up and running 👍.
