### ISSUE TITLE
[Bug] 'LDAP operation [rename] failed.' OpenLdap

### ISSUE THREAD

**Issue by nohnaimer** [DirectoryTree/LdapRecord#237]
**Environment (please complete the following information):**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 7.4.14
 - LdapRecord 2.0.4

```php
Exception 'LdapRecord\LdapRecordException' with message 'LDAP operation [rename] failed.'

in /Users/and1/phpProjects/www/ems/vendor/directorytree/ldaprecord/src/LdapRecordException.php:26

Caused by: Exception 'Exception' with message 'LDAP operation [rename] failed.'

in /Users/and1/phpProjects/www/ems/vendor/directorytree/ldaprecord/src/Ldap.php:914

Stack trace:
#0 /Users/and1/phpProjects/www/ems/vendor/directorytree/ldaprecord/src/Ldap.php(642): LdapRecord\Ldap->executeFailableOperation(Object(Closure))
#1 /Users/and1/phpProjects/www/ems/vendor/directorytree/ldaprecord/src/Query/Builder.php(1711): LdapRecord\Ldap->rename('cn=\xD0\xA0\xD0\xBE\xD0\xBC\xD0\xB0\xD0\xBD\xD0\xB5...', 'cn=\xD0\xA0\xD0\xBE\xD0\xBC\xD0\xB0\xD0\xBD\xD0\xB5...', 'ou=\xD0\x93\xD1\x80\xD0\xBE\xD0\xB4\xD0\xBD\xD0\xBE...', true)
#2 /Users/and1/phpProjects/www/ems/vendor/directorytree/ldaprecord/src/Connection.php(311): LdapRecord\Query\Builder->LdapRecord\Query\{closure}(Object(LdapRecord\Ldap))
#3 /Users/and1/phpProjects/www/ems/vendor/directorytree/ldaprecord/src/Connection.php(268): LdapRecord\Connection->runOperationCallback(Object(Closure))
#4 /Users/and1/phpProjects/www/ems/vendor/directorytree/ldaprecord/src/Query/Builder.php(1712): LdapRecord\Connection->run(Object(Closure))
#5 /Users/and1/phpProjects/www/ems/vendor/directorytree/ldaprecord/src/Models/Model.php(1237): LdapRecord\Query\Builder->rename('cn=\xD0\xA0\xD0\xBE\xD0\xBC\xD0\xB0\xD0\xBD\xD0\xB5...', 'cn=\xD0\xA0\xD0\xBE\xD0\xBC\xD0\xB0\xD0\xBD\xD0\xB5...', 'ou=\xD0\x93\xD1\x80\xD0\xBE\xD0\xB4\xD0\xBD\xD0\xBE...', true)
#6 /Users/and1/phpProjects/www/ems/common/models/behaviors/AddressBookEmployeeBehavior.php(178): LdapRecord\Models\Model->rename('cn=\xD0\xA0\xD0\xBE\xD0\xBC\xD0\xB0\xD0\xBD\xD0\xB5...')
#7 /Users/and1/phpProjects/www/ems/common/models/behaviors/AddressBookEmployeeBehavior.php(120): common\models\behaviors\AddressBookEmployeeBehavior->update()
#8 [internal function]: common\models\behaviors\AddressBookEmployeeBehavior->afterUpdate(Object(yii\db\AfterSaveEvent))
#9 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/base/Component.php(628): call_user_func(Array, Object(yii\db\AfterSaveEvent))
#10 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1000): yii\base\Component->trigger('afterUpdate', Object(yii\db\AfterSaveEvent))
#11 /Users/and1/phpProjects/www/ems/common/models/Employee.php(341): yii\db\BaseActiveRecord->afterSave(false, Array)
#12 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/db/BaseActiveRecord.php(825): common\models\Employee->afterSave(false, Array)
#13 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/db/ActiveRecord.php(681): yii\db\BaseActiveRecord->updateInternal(NULL)
#14 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/db/BaseActiveRecord.php(681): yii\db\ActiveRecord->update(true, NULL)
#15 /Users/and1/phpProjects/www/ems/console/models/SyncProsellerModel.php(69): yii\db\BaseActiveRecord->save()
#16 /Users/and1/phpProjects/www/ems/console/controllers/EmployeeController.php(155): console\models\SyncProsellerModel->sync('/Users/and1/Des...')
#17 [internal function]: console\controllers\EmployeeController->actionSync()
#18 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#20 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('sync', Array)
#21 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('sync', Array)
#22 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('employee/sync', Array)
#23 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('employee/sync', Array)
#24 /Users/and1/phpProjects/www/ems/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
#25 /Users/and1/phpProjects/www/ems/yii(27): yii\base\Application->run()
```
When rename record like in manual - https://ldaprecord.com/docs/core/v2/model-api/#rename get error.
Any ideas?

**Comment by stevebauman** [comment]
Hi @nohnaimer,

Can you post your code where renaming is taking place?

Also a couple things I would check:

- Ensure the name that you are renaming the object to is not already in use in the same container that the object resides in
- Ensure the account that you are using to run the LDAP rename operation has permissions to rename the object you are attempting to rename

**Comment by nohnaimer** [comment]
Hi @stevebauman 

> Can you post your code where renaming is taking place?

```php
        $user = User::query()->setDn($this->getBaseDN())->findBy('EmployeeID', $this->owner->id);
        if ($user === null) {
            $this->create();
            return;
        }

        if ($this->isRenameNeed) {
            $user->rename('cn=' . $this->owner->getFullName());
            $user->refresh();
        }
```
User - \LdapRecord\Models\OpenLDAP\User
rename - LdapRecord/src/Models/Model
https://github.com/DirectoryTree/LdapRecord/blob/29e5a95ef66db6d28f272085f50973768942338f/src/Models/Model.php#L1223

> Ensure the name that you are renaming the object to is not already in use in the same container that the object resides in

The object has one cn and I change to different cn, The names are different

> Ensure the account that you are using to run the LDAP rename operation has permissions to rename the object you are attempting to rename

I use admin openldap server account

**Comment by stevebauman** [comment]
Thanks for posting your code @nohnaimer! Everything looks fine in your code 👍

> A little addition: if the object's cn and the new cn are equal, will there be such an error? That is, before calling the method rename, I need to check that the cn are not equal, something like this:

Yes I believe it will throw an error, depending on the LDAP server.

Are you able to successfully rename **any** user object in your LDAP server with your `User` LdapRecord model?

I would try running a raw rename command to see if you encounter this only with models:

```php
$connection = User::getConnection();

$result = $connection->query()->rename(
    'cn=John Doe,ou=Users,dc=local,dc=com',
    'cn=Suzy Doe',
    'ou=Users,dc=local,dc=com',
    $deleteOldRdn = true,
);

var_dump($result);
```

Can you give the above a shot and let me know the result?

**Comment by nohnaimer** [comment]
You right if cn are equal get error LDAP operation [rename] failed.

When I try this code:
```php
$connection = User::getConnection();
```
I get error
<img width="1787" alt="Снимок экрана 2021-01-27 в 11 11 46" src="https://user-images.githubusercontent.com/8865830/105962787-45a68f00-6091-11eb-9a46-48bb18b36640.png">

But this code work fine even with my model
```php
$result = \common\models\ldap\open\User::query()->rename(
            'cn=Suzy Doe,ou=Personnel,dc=local,dc=com',
            'cn=John Doe',
            'ou=Personnel,dc=local,dc=com',
            $deleteOldRdn = true,
        );

        debug($result);
```
When I run at first time I get back true. But if try run second time I get error LDAP operation [rename] failed.
<img width="1787" alt="Снимок экрана 2021-01-27 в 11 15 16" src="https://user-images.githubusercontent.com/8865830/105963134-af269d80-6091-11eb-9eb1-efc43f3712cf.png">

Will you fix the bug or should I add checks to my code?

**Comment by stevebauman** [comment]
Ah okay thank so much for the detailed issue @nohnaimer!

I'm going to fix this bug. A rename request should not be sent to your LDAP server when the name has not actually been changed/updated.

Once I've pushed out a fix and made a new release, I will close this out to notify you 👍 .

**Comment by stevebauman** [comment]
Fixed in release [v2.1.3](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.1.3) 🎉

**Comment by wilfredofermin** [comment]
with laravel the same error is maintained with version 2.5

**Comment by stevebauman** [comment]
Hi @wilfredofermin, please create a new bug report with your environment and project information, as well as a re-produceable code example so I can take a look, thanks!
