### ISSUE TITLE
[Support] guid and domain aren't store in users database

### ISSUE THREAD

**Issue by satyakresna** [DirectoryTree/LdapRecord#239]
Hi @stevebauman, after I success save the user data in issue #238, I got another issue. The value of field `guid` and `domain` aren't store in users table. I'm using only one LDAP connection and in the [ldap record documentation](https://ldaprecord.com/docs/core/v2/models/#connections) say that by default it will set `default` as value of `$connection`. I try around 3 times to store user into database and ldap, it success but it doesn't generate `guid` and `domain` value in users database.

Here's the code snippets.

**UserController.php**

```php
public function store(StoreUserRequest $request)
    {
        $user = new User;
        
        // DB Dashboard
        $user->name = $request->name;
        $user->identifier = $request->identifier;
        $user->email = $request->email;
        $user->username = $request->username;
        $user->password = Hash::make('rahasia321');
        $user->save();

        // LDAP
        $openldap_user = new OpenLdapUser;
        $openldap_user->givenName = $request->name;
        $openldap_user->cn = $request->identifier;
        $openldap_user->sn = $request->name;
        $dn = "uid=".$request->username.",ou=users,dc=foo,dc=bar,dc=com";
        $openldap_user->setDn($dn);
        $openldap_user->mail = $request->email;
        $openldap_user->uid = $request->username;
        $openldap_user->userPassword = "{MD5}".base64_encode(hex2bin(md5('rahasia321')));
        $openldap_user->save();

        return redirect()->route('users.index');
    }
```

**OpenLdapUser**

```php
<?php

namespace App\Models;

use LdapRecord\Models\Model;

class OpenLdapUser extends Model
{
    public static $objectClasses = [
        'eduPerson',
        'inetOrgPerson',
        'organizationalPerson',
        'person',
        'top',
        'unudPerson',
    ];
}
```

**Comment by stevebauman** [comment]
Hi @satyakresna!

There's a couple issues here:

1. Since you're using the OpenLDAP, I would suggest extending the default, built-in OpenLDAP LdapRecord `Entry` model, as it includes the required `$guidKey` property which provides the ability for LdapRecord-Laravel to identify and save LDAP objects into your database:

```php
namespace App\Models;

use LdapRecord\Models\OpenLDAP\Entry;

class OpenLdapUser extends Entry
{
    public static $objectClasses = [
        'eduPerson',
        'inetOrgPerson',
        'organizationalPerson',
        'person',
        'top',
        'unudPerson',
    ];
```

2. To import LDAP objects into your database, you must leverage the `Synchronizer`, and ensure that your `User` model implements the required interface and trait mentioned here:

https://ldaprecord.com/docs/laravel/v2/importing/

- `LdapRecord\Laravel\LdapImportable`
- `LdapRecord\Laravel\ImportableFromLdap`

Looking at your code, it appears you're creating a new LDAP user during the creation of an Eloquent user. You must first create the LDAP user so the `entryUUID` exists.

```php
use App\Models\User;
use App\Models\OpenLdapUser;
use LdapRecord\Laravel\Import\Synchronizer;
use LdapRecord\Models\ActiveDirectory\Group as LdapGroup;

// ...
$openldap_user->save();

// Refresh the LDAP users attributes, pulling in the UUID.
$openldap_user->refresh();

// Create the synchronizer and setup the sync attributes:
$synchronizer = new Synchronizer(User::class, $config = [
    'sync_attributes' => [
        'name' => 'givenName',
        'email' => 'mail',
        'username' => 'uid',
        'identifier' => 'cn',
    ],
]);

// Import the user from the OpenLDAP directory.
$synchronizer->run($openldap_user)->save();
```

Give that a shot and let me know your results!

**Comment by satyakresna** [comment]
Hi @stevebauman, thanks! It works now. But, when I try this method the flow to store user data is change. It starts from store user data into OpenLDAP and then sync to database. 

Is it possible to change the flow? Store the user data into database => sync to openldap => fetch the guid and domain value from openldap => set guid and domain value to specific user (update the user data). This flow intended in case the OpenLDAP server connection is down.

If it is possible then I have another problem about `password` attribute. In users table database and users in open ldap. In users table the password is `required` and the value using Hash provided by Laravel. In other side in OpenLDAP, the password stored using MD5.

**Comment by satyakresna** [comment]
> 
> 
> Hi @stevebauman, thanks! It works now. But, when I try this method the flow to store user data is change. It starts from store user data into OpenLDAP and then sync to database.
> 
> Is it possible to change the flow? Store the user data into database => sync to openldap => fetch the guid and domain value from openldap => set guid and domain value to specific user (update the user data). This flow intended in case the OpenLDAP server connection is down.
> 
> If it is possible then I have another problem about `password` attribute. In users table database and users in open ldap. In users table the password is `required` and the value using Hash provided by Laravel. In other side in OpenLDAP, the password stored using MD5.

Hi @stevebauman, I think I find the solution. After run `$openldap_user->refresh()` I can see the `entryuuid` attribute. And use this attribute to update `guid` value in user table.

```php

       // DB Dashboard
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->username = $request->username;
        $user->identifier = $request->identifier;
        $user->password = Hash::make(User::DEFAULT_PASSWORD);
        $user->save();

       // OpenLDAP
        $openldap_user->save();

        // Refresh the LDAP users attributes, pulling in the UUID.
        $openldap_user->refresh();


        $user->guid = $openldap_user->entryuuid[0];
        // By default connection to openldap only one connection
        // And the value of that is `default`
        $user->domain = 'default';
        $user->save();
```

How do you think?

**Comment by stevebauman** [comment]
Hi @satyakresna, that definitely works if you prefer having your own synchronization mechanism. 👍

The LdapRecord synchronizer and importer only works in one direction:

**LDAP** -> **Database**

And (unfortunately) not:

**Database** -> **LDAP**

This is due to requiring a GUID and domain from the LDAP object to be able to save it in the database record, so we know which LDAP object it actually belongs to.

I've never actually ran into this specific use case before (Database -> LDAP), so it's definitely interesting to see!

> If it is possible then I have another problem about password attribute. In users table database and users in open ldap. In users table the password is required and the value using Hash provided by Laravel. In other side in OpenLDAP, the password stored using MD5.

Are you planning on being able to authenticate OpenLDAP users into your application? Or are you looking to store the LDAP users password inside of a user database record?

Once I know what you're looking to achieve in your application then I can jump into the implementation details with you 😄

**Comment by satyakresna** [comment]
Hi @stevebauman, thanks for your reply. I'm planning on being able to authenticate OpenLDAP users in my application. In big picture, I with the team have a plan to store users data in OpenLDAP and use it authentication SSO using [Keycloak](https://www.keycloak.org/).

**Comment by stevebauman** [comment]
> I'm planning on being able to authenticate OpenLDAP users in my application.

Ok great. In that case, you could do the following to achieve this:

1. Configure LdapRecord as a Laravel [authentication provider](https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#introduction) in your application.
2. Enable [password sync](https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#database-password-sync) (if needed)
3. Use [attribute handlers](https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#database-attribute-handlers) if you need additional control over synchronizing your Eloquent user models attributes with their LDAP object.
4. Use the `ldap:import` [command](https://ldaprecord.com/docs/laravel/v2/auth/database/importing/) to bulk-import your OpenLDAP users into your application
5. Leverage the `Import\Completed` [event](https://github.com/DirectoryTree/LdapRecord-Laravel/blob/master/src/Events/Import/Completed.php or the `Import\Saved` [event](https://github.com/DirectoryTree/LdapRecord-Laravel/blob/master/src/Events/Import/Saved.php) to perform any additional operations during the import of your OpenLDAP users.

I hope this helps! Let me know if you have any additional questions 👍

**Comment by satyakresna** [comment]
> 
> 
> > I'm planning on being able to authenticate OpenLDAP users in my application.
> 
> Ok great. In that case, you could do the following to achieve this:
> 
>     1. Configure LdapRecord as a Laravel [authentication provider](https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#introduction) in your application.
> 
>     2. Enable [password sync](https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#database-password-sync) (if needed).
> 
>     3. Use [attribute handlers](https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#database-attribute-handlers) if you need additional control over synchronizing your Eloquent user models attributes with their LDAP object.
> 
>     4. Use the `ldap:import` [command](https://ldaprecord.com/docs/laravel/v2/auth/database/importing/) to bulk-import your OpenLDAP users into your application.
> 
>     5. Leverage the `Import\Completed` [event](https://github.com/DirectoryTree/LdapRecord-Laravel/blob/master/src/Events/Import/Completed.php or the `Import\Saved` [event](https://github.com/DirectoryTree/LdapRecord-Laravel/blob/master/src/Events/Import/Saved.php) to perform any additional operations during the import of your OpenLDAP users.
> 
> 
> I hope this helps! Let me know if you have any additional questions 👍

Noted, thanks a lot Steve!
