### ISSUE TITLE
Can't load libraries after install

### ISSUE THREAD

**Issue by bradjtrammell** [DirectoryTree/LdapRecord#24]
- Adldap2 Version: (LdapRecord)
- LDAP Type: Active Directory
- PHP Version: 7.2

### Description:
When installing the composer file, I am getting an error after everything is installed, it appears as if the libraries are not loading properly. The error is:

`Fatal error: Uncaught Error: Class 'LdapRecord\Connections\Connection' not found in /home/sso/www/_test.php:9 Stack trace: #0 {main} thrown in /home/sso/www/_test.php on line 9`

The entire contents of the file is:
require __DIR__ . '/vendor/autoload.php';

use LdapRecord\Connections\Container;
use LdapRecord\Connections\Connection;
use LdapRecord\Models\ActiveDirectory\Group;

$connection = new Connection(['hosts' => ['192.168.1.1'], 'base_dn' => 'dc=acme,dc=org', 'username' => 'user', 'password' => 'secret',]);

I should at least get an error message that it can't connect if it was loading the libraries properly.

### Steps To Reproduce:
Using the following command to install:
`runuser -l sso -c "composer install-v --working-dir=/home/sso/www"`

I have downloaded the composer.json file and adjusted it as I was getting and error about a dependency. It's exactly the same as the original, except I changed `"phpunit/phpunit": "*",`

**Comment by stevebauman** [comment]
Hi @bradjtrammell,

You don't need to download the LdapRecord composer file. This is likely the issue. You must create your own `composer.json` file for your project, and then insert / require your dependencies inside.

If your root directory is `home/sso/www`, then create a `composer.json` file with the following contents:

```json
{
    "require": {}
}
```

Then, open a command and `cd` into your `www` directory, and run the command:

```bash
composer require directorytree/ldaprecord
```

Once you do that, composer will create a `home/sso/www/vendor` folder will be created containing LdapRecord, and its dependencies.

Afterwards, in your `www/index.php` file (or whatever file is the root of your project), insert;

```php
<?php

require DIR . '/vendor/autoload.php';

// Start using LdapRecord:

use LdapRecord\Connection;

$config = ['...'];

$connection = new Connection($config);
```

If you still encounter issues, please let me know and I'd be glad to help you get up and running :smile:

**Comment by bradjtrammell** [comment]
Do you have a "cookbook" available for the documentation, like for example this code can authenticate a user, this code can check a group for a user, etc. 

I'm getting auth errors, it says invalid credentials. I'm assuming it's just not talking with the server.

`Fatal error: Uncaught Exception: Invalid credentials in /home/sso/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php:122 Stack trace: #0 /home/sso/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php(143): LdapRecord\Auth\Guard->bind('**OMITTED**', '**OMITTED**') #1 /home/sso/www/vendor/directorytree/ldaprecord/src/Connection.php(149): LdapRecord\Auth\Guard->bindAsConfiguredUser() #2 /home/sso/www/_tests/bindAD.php(21): LdapRecord\Connection->connect() #3 {main} Next LdapRecord\Auth\BindException: Invalid credentials in /home/sso/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php:127 Stack trace: #0 /home/sso/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php(143): LdapRecord\Auth\Guard->bind('**OMITTED**', '**OMITTED**') #1 /home/sso/www/vendor/directorytree/ldaprecord/src/Connection.php(149): LdapRecord\Auth\Guard->bindAsConfiguredUser() #2 /home/sso/www/_tests/bindAD.php(21): LdapRecord\Connection->connect() #3 {main} thrown in /home/sso/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php on line 127`

Here's what I got, it's basically what you posted above:

```
require $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
use LdapRecord\Connection;

// Create a new connection:
$connection = new \LdapRecord\Connection([
    'hosts' => [**OMITTED**],
    'port' => 389,
    'username' => '**OMITTED**',
    'password' => '**OMITTED**',
    'base_dn' => '**OMITTED**',
]);

// Connect to your server:
$connection->connect();
```

**Comment by stevebauman** [comment]
> Do you have a "cookbook" available for the documentation, like for example this code can authenticate a user, this code can check a group for a user, etc.

Of course:

- [Binding Users](https://ldaprecord.com/docs/master/connections#binding)
- [User Group Management(https://ldaprecord.com/docs/master/user-management#group-management)

Is your LDAP server accessible from your web server?

**Comment by bradjtrammell** [comment]
> Is your LDAP server accessible from your web server?

Yes. They are visible and accessible to each other. I have another LDAP connection to this very same server using a different platform.

**Comment by stevebauman** [comment]
Is your server accessible over the standard 389 port? Checking all the boxes before going further.

**Comment by stevebauman** [comment]
Also, for the `hosts` option, are you using IP address or host name?

**Comment by bradjtrammell** [comment]
> Is your server accessible over the standard 389 port? Checking all the boxes before going further.
Yes, it's using the standard 389 port. The server contains a barebones LDAP check that checks the user's entered credentials to allow access to a SSO portal. That appears to be working fine (it's using the standard php ldap authentication module for php)

> Also, for the `hosts` option, are you using IP address or host name?
I have tried both. Same result.

**Comment by stevebauman** [comment]
Give it another shot from my above edit. Can you confirm which username format you're attempting to connect with?

**Comment by bradjtrammell** [comment]
I am now getting this error:



`Fatal error: Uncaught LdapRecord\ContainerException: The connection connection 'default' does not exist. in /home/sso/www/vendor/directorytree/ldaprecord/src/Container.php:151 Stack trace: #0 /home/sso/www/vendor/directorytree/ldaprecord/src/Models/Model.php(243): LdapRecord\Container->get('default') #1 /home/sso/www/vendor/directorytree/ldaprecord/src/Models/Model.php(217): LdapRecord\Models\Model::resolveConnection('default') #2 /home/sso/www/vendor/directorytree/ldaprecord/src/Models/Model.php(206): LdapRecord\Models\Model->newQueryWithoutScopes() #3 /home/sso/www/vendor/directorytree/ldaprecord/src/Models/Model.php(98): LdapRecord\Models\Model->newQuery() #4 /home/sso/www/vendor/directorytree/ldaprecord/src/Models/Model.php(111): LdapRecord\Models\Model->__call('findBy', Array) #5 /home/sso/www/_tests/bindAD.php(23): LdapRecord\Models\Model::__callStatic('findBy', Array) #6 {main} thrown in /home/sso/www/vendor/directorytree/ldaprecord/src/Container.php on line 151`

Which leads me to believe it passed authentication, but for some reason can't query?

Here's the code I have below the connection section:

```
$user = \LdapRecord\Models\ActiveDirectory\User::findBy('samaccountname', 'brad.trammell');
$group = \LdapRecord\Models\ActiveDirectory\Group::findBy('name', 'Administrators');

if ($user->groups()->exists($group)) {
    echo "User in group";
} else {
	echo "Missing from group";
}
```

To answer your previous question, I am connecting using the DistinguishedName style of username entry.

**Comment by stevebauman** [comment]
Ah you must add your connection to the container to begin queries. It's shown in the [quick start](https://ldaprecord.com/docs/master#quick-start):

```php
// Create a new connection:
$connection = new \LdapRecord\Connection([
    'hosts' => ['192.168.1.1'],
    'port' => 389,
    'username' => 'user',
    'password' => 'secret',
    'base_dn' => 'dc=local,dc=com',
]);

// Connect to your server:
$connection->connect();

// Add the connection to the container:
\LdapRecord\Container::getInstance()->add($connection);

// Get all objects:
$objects = \LdapRecord\Models\Entry::get();
```

**Comment by bradjtrammell** [comment]
That worked. I'm still a bit confused by the documentation though.

**Comment by stevebauman** [comment]
What in particular are you confused with?

**Comment by bradjtrammell** [comment]
Essentially, I need to be able to authenticate a user based on a PHP login form (I'm building an AD SSO Portal), if the user is authorized and not disable, they should be permitted to continue. Then we will have menu items that will displayed based on the groups the user is a member of, to use examples from your documentation. Accounting members will only see accounting functions, and not things for Support, or Administrators.

I'm proficient enough with PHP to be able to do all of the sessioning and getting the portal setup. I just need to be able to get the result of the queries from AD, mainly:

- Check AD against what the logs in with, return with a boolean so we can differentiate. 
- Check AD for user's membership to a single dynamic group.
- Acquire various AD User information on Login (username, first name, last name, display name, email address, and a few other smaller pieces of information). 

- Eventually I want to be able to make it so the user can also update specific fields, such as last name, phone number, address, etc. But that's not a top priority right now.

I was able to accomplish all of this with ADLDAP2, minus the ability to see what groups the user was in, which is a required feature of this portal.

**Comment by stevebauman** [comment]
Have you read much through the documentation with how the models work and how to authenticate?

https://ldaprecord.com/docs/master/connections#binding

> Acquire various AD User information on Login (username, first name, last name, display name, email address, and a few other smaller pieces of information).

https://ldaprecord.com/docs/master/models#attributes

> Check AD against what the logs in with, return with a boolean so we can differentiate.

```php
// Create a new connection:
$connection = new \LdapRecord\Connection([
    'hosts' => ['192.168.1.1'],
    'port' => 389,
    'username' => 'user',
    'password' => 'secret',
    'base_dn' => 'dc=local,dc=com',
]);

// Connect to your server:
$connection->connect();

// Add the connection to the container:
\LdapRecord\Container::getInstance()->add($connection);

// Get the user attempting to authenticate:
$user = \LdapRecord\Models\ActiveDirectory\User::findBy('samaccountname', 'jdoe');

if ($user) {
    // User exists, check if their enabled:
    $uac = new \LdapRecord\Models\Attributes\UserAccountControl($user->userAccountControl);

    if (!$uac->has(AccountControl::ACCOUNTDISABLE)) {
        // User is not disabled. Check users group membership:
        $group = \LdapRecord\Models\ActiveDirectory\Group::findByOrFail('name', 'Accounting');

        if ($user->groups()->exists($group)) {
            // User is inside our 'Accounting' group. Attempt authentication:
            if ($connection->auth()->attempt($user->getDn(), 'the-users-password')) {
                    // Username and password are good. Setup session.
                    // ...
            }
            
            // User failed authentication.
        }
        
        // User is not a member of the group.
    }

    // User is disabled.
}

// User not found.
```

**Comment by bradjtrammell** [comment]
This is more of what I was referring to when I mentioned a cook book, an in-place example that could be taken and modified.

```
// Create a new connection:
$connection = new \LdapRecord\Connection([
    'hosts' => ['192.168.1.1'],
    'port' => 389,
    'username' => 'user',
    'password' => 'secret',
    'base_dn' => 'dc=local,dc=com',
]);

// Connect to your server:
$connection->connect();

// Add the connection to the container:
\LdapRecord\Container::getInstance()->add($connection);

// Get the user attempting to authenticate:
$user = \LdapRecord\Models\ActiveDirectory\User::findBy('samaccountname', 'jdoe');

if ($user) {
    // User exists, check if their enabled:
    $uacValue = $user->getFirstAttribute('userAccountControl');

    $uac = new \LdapRecord\Models\Attributes\AccountControl($uacValue);

    if (!$uac->has(\LdapRecord\Models\Attributes\AccountControl::ACCOUNTDISABLE)) {
        // User is not disabled. Check users group membership:
        $group = \LdapRecord\Models\ActiveDirectory\Group::findByOrFail('name', 'Accounting');

        if ($user->groups()->exists($group)) {
            // User is inside our 'Accounting' group. Attempt authentication:
            if ($connection->auth()->attempt($user->getDn(), 'the-users-password')) {
                // Username and password are good. Setup session.
                // ...
            }
            
            // User failed authentication.
        }
        
        // User is not a member of the group.
    }

    // User is disabled.
}

// User not found.
```

I am getting this error:
Fatal error: Uncaught Error: Class 'LdapRecord\Models\Attributes\UserAccountControl' not found.

Is there a namespace that is required to access UAC?

**Comment by bradjtrammell** [comment]
I have read a bit of your documentation, but I feel it's best to dive in and learn the error of my ways through failed attempts Haha. My apologies for any annoyance or stupid questions.

**Comment by stevebauman** [comment]
> Is there a namespace that is required to access UAC?

Yup that’s my bad, I modified the above example, I made several mistakes while writing it originally that I fixed.

It’s located in the following namespace:

```php
\LdapRecord\Models\Attributes\AccountControl
```

Sorry about that!

Also no worries! I’m still working on more examples - I have all of the API documentation done, but I’m definitely going to be adding more examples from your suggestions.

**Comment by bradjtrammell** [comment]
No worries at all, there is a learning curve to any new implementation. I'm going to have to read through the documentation a little more. Haha. 

The example you provided works beautifully. Thank you for all your hard work!
