### ISSUE TITLE
[Bug] unicodepwd is not saving correct on Active Directory database

### ISSUE THREAD

**Issue by VGzsysadm** [DirectoryTree/LdapRecord#242]
**Environment (please complete the following information):**
 - Windows server 2019 Standard Edition - Active Directory
 - PHP 7.4.8 (cli) (built: Jul  9 2020 11:30:33) ( NTS Visual C++ 2017 x64 )
 - "directorytree/ldaprecord": "^2.1"

Greetings.

I have some problems in order to saving a user enabled with the correct password.

This is my test code.
```
<?php

require __DIR__ . '/vendor/autoload.php';

use LdapRecord\Container;
use LdapRecord\Connection;
use LdapRecord\Models\Entry;
use LdapRecord\Models\ActiveDirectory\User;
use LdapRecord\Models\ActiveDirectory\Group;

$connection = new Connection([
    'hosts' => ['192.168.1.21'],
    'port' => 636,
    'base_dn' => 'dc=Users,dc=sysadm,dc=local',
    'username' => 'SYSADM\Administrador',
    'password' => 'MyPassword',
    'use_ssl'          => true,
    'use_tls'          => false,
    'version'          => 3,
    'timeout'          => 5,
    'options' => [
        // See: http://php.net/ldap_set_option
        LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_NEVER
    ]
]);

try {
    $connection->connect();

    echo "Successfully connected!";
} catch (\LdapRecord\Auth\BindException $e) {
    $error = $e->getDetailedError();

    echo $error->getErrorCode();
    echo $error->getErrorMessage();
    echo $error->getDiagnosticMessage();
}

\LdapRecord\Container::getInstance()->add($connection);

###################

$user = (new User)->inside('ou=groups,dc=sysadm,dc=local');

$user->cn = 'Joe';
$user->unicodePwd = 'Pl@intext2021';
$user->samaccountname = 'j.joe';
$user->userPrincipalName = 'j.joe@sysadm.local';

$user->save();

// Enable the user.
$user->userAccountControl = 512;

try {
    $user->save();
} catch (\LdapRecord\LdapRecordException $e) {
    // Failed saving user.
}
```

The user is created as expected

```
F:\ldap>php script.php
Successfully connected!
```

Even selecting userAccountControl 512, the user is disabled when is created, the password can pass the policy password because is "complex" style, if manually enables the user and try to logon, the message is "invalid password", mainly this happens because the parameter $user->unicodePwd = is not saving the password encoded correctly.
![](https://i.ibb.co/fr3FCt9/imagen.png|width=50)

Thanks.

Kind regards.

**Comment by stevebauman** [comment]
Hi @VGzsysadm!

Could you try `refresh()`'ing the user before setting their account control value and saving?

Here's an example:

```php
// ...
$user->save();

// Refresh the user attributes.
$user->refresh();

// Enable the user.
$user->userAccountControl = 512;

try {
    $user->save();
} catch (\LdapRecord\LdapRecordException $e) {
    // Failed saving user.
}
```

If it still doesn't work -- can you dump the users attributes (with any sensitive attributes removed) after the last `save()` you perform (using `var_dump($user))` and post the result here?

Also, the `unicodePwd` attribute _should_ be set properly. You can take a look at the source here:

https://github.com/DirectoryTree/LdapRecord/blob/master/src/Models/Concerns/HasPassword.php

To see the batch modification that is added to the user, you can `var_dump` the users modifications after setting the users `unicodePwd` attribute by calling the `getModifications()` method on the model:

```php
$user-> unicodePwd = 'new-password';

// The dumped array should contain a single batch 'replace'
// modification for the "unicodepwd" attribute:
var_dump($user->getModifications());
```

https://github.com/DirectoryTree/LdapRecord/blob/90f0f3be18178a5ec2b79afa47cc86f5592c20d0/src/Models/Concerns/HasPassword.php#L99-L108

Does the batch modification appear in the dumped array?

**Comment by VGzsysadm** [comment]
Greetings @stevebauman 

The refresh did the trick

// Refresh the user attributes.
$user->refresh();

Thanks for you help.

Kind regards.

**Comment by stevebauman** [comment]
Awesome @VGzsysadm! Glad that worked. This is likely due to how LDAP modifications are generated on LdapRecord models.

After creating a non-existent object using `save()`, the `userAccountControl` property does not actually exist in the LdapRecord model's `$attributes` array. Since it does not exist inside of the model's attributes, LdapRecord will assume it's a **_new_** attribute, and send a `LDAP_MODIFY_BATCH_ADD` to the `userAccountControl` property, instead of a `LDAP_MODIFY_BATCH_REPLACE`, likely causing this issue here.

I'll update the documentation to reflect this -- thanks for the detailed report @VGzsysadm!
