### ISSUE TITLE
[Bug] Documentation says to use 'hides' to prevent serialization of attributes, but should be 'hidden'

### ISSUE THREAD

**Issue by misenhei** [DirectoryTree/LdapRecord#243]
Your documentation to hide a variable from serialization says to use 'hides':
https://ldaprecord.com/docs/core/v2/models/#hiding-attributes 

but to hide attributes from serialization in Laravel 8.x the variable is 'hidden', not 'hides:
https://laravel.com/docs/8.x/eloquent-serialization#hiding-attributes-from-json

Using 'hides' does not work, but when changed to 'hidden' in the model the attributes are not in the serialized output.
I did not test or look into the addHidden() method but it should be verified to functions as expected.

**Comment by stevebauman** [comment]
Great catch @misenhei! Thanks for letting me know about this ❤️ . You are absolutely correct, the property is indeed `$hidden` and not `$hides`.

I've just fixed this in the documentation. It should be live on the website in a couple minutes while a new build is generated 👍
