### ISSUE TITLE
Non-static method LdapRecord\Container [Support]

### ISSUE THREAD

**Issue by gnewmann** [DirectoryTree/LdapRecord#244]
Hey @stevebauman,

I'm facing a problem, where I am not shure if it (only) belongs to LDAPRecord.. but maybe you can help me out. 

I cloned my Repo to a linux test server, to get my laravel installation up and running. 
I installed all needed dependencies and composer. 

When I'm trying to "composer install" I receive following error message:

Non-static method LdapRecord\Container::getEventDispatcher() should not be called statically

  at app/Providers/EventServiceProvider.php:39
```
     35▕     public function boot()
     36▕     {
     37▕         parent::boot();
     38▕
  ➜  39▕         $dispatcher = Container::getEventDispatcher();
     40▕
     41▕         foreach ($this->listen as $event => $listeners) {
     42▕             foreach (array_unique($listeners) as $listener) {
     43▕                 $dispatcher->listen($event, $listener);
```

Since this is working on my previous test-system (on a local machine), I'm not shure if I'm missing something.

Maybe you got me some advice. 

The version I'm using:
PHP 7.3.19 (Zend Engine v3.3.19)
Composer v1.8.4 (pretty old --> i used apt-get on debian)

Thank you in advance.

Regards Greg

**Comment by stevebauman** [comment]
Hey @gnewmann, thanks so much for the sponsorship!

Can you post your `composer.json` file here so I can take a look and help you debug?

**Comment by gnewmann** [comment]
Hey @stevebauman , thanks for the quick response, of course:
`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3.0",
        "ext-json": "*",
        "directorytree/ldaprecord-laravel": "^1.2",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/legacy-factories": "^1.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^3.0",
      "ext-http": "*"
    },
    "require-dev": {
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "laravel/dusk": "^6.8",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}`

Thank you

**Comment by stevebauman** [comment]
No problem! Ok great, can you upload your composer.lock` file? It will show me what specific versions of LdapRecord-Laravel and LdapRecord you have installed 👍

**Comment by gnewmann** [comment]
Yes of course :)

Here we go:

        {
            "name": "directorytree/ldaprecord",
            "version": "v1.12.1",
            "source": {
                "type": "git",
                "url": "https://github.com/DirectoryTree/LdapRecord.git",
                "reference": "4dd945db58a78eb2768477905b7ebb473dc782dc"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/DirectoryTree/LdapRecord/zipball/4dd945db58a78eb2768477905b7ebb473dc782dc",
                "reference": "4dd945db58a78eb2768477905b7ebb473dc782dc",
                "shasum": ""
            },
            "require": {
                "ext-json": "*",
                "ext-ldap": "*",
                "illuminate/contracts": "^5.0|^6.0|^7.0|^8.0",
                "nesbot/carbon": "^1.0|^2.0",
                "php": ">=7.2",
                "psr/log": "^1.0",
                "psr/simple-cache": "^1.0",
                "tightenco/collect": "^5.0|^6.0|^7.0|^8.0"
            },
            "require-dev": {
                "mockery/mockery": "^1.0",
                "phpunit/phpunit": "^8.0"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "LdapRecord\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Steve Bauman",
                    "email": "steven_bauman@outlook.com",
                    "role": "Developer"
                }
            ],
            "description": "A fully-featured LDAP ORM.",
            "homepage": "https://www.ldaprecord.com",
            "keywords": [
                "active directory",
                "ad",
                "adLDAP",
                "adldap2",
                "directory",
                "ldap",
                "ldaprecord",
                "orm",
                "windows"
            ],
            "support": {
                "docs": "https://ldaprecord.com",
                "email": "steven_bauman@outlook.com",
                "issues": "https://github.com/DirectoryTree/LdapRecord/issues",
                "source": "https://github.com/DirectoryTree/LdapRecord"
            },
            "funding": [
                {
                    "url": "https://github.com/stevebauman",
                    "type": "github"
                }
            ],
            "time": "2020-11-08T20:25:00+00:00"
        },
        {
            "name": "directorytree/ldaprecord-laravel",
            "version": "v1.7.3",
            "source": {
                "type": "git",
                "url": "https://github.com/DirectoryTree/LdapRecord-Laravel.git",
                "reference": "6cdaed0895e2847feca4ce675550eca7b449e467"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/DirectoryTree/LdapRecord-Laravel/zipball/6cdaed0895e2847feca4ce675550eca7b449e467",
                "reference": "6cdaed0895e2847feca4ce675550eca7b449e467",
                "shasum": ""
            },
            "require": {
                "directorytree/ldaprecord": "^1.8.2",
                "ext-ldap": "*",
                "illuminate/support": "^5.6|^6.0|^7.0|^8.0",
                "php": ">=7.2"
            },
            "require-dev": {
                "mockery/mockery": "~1.0",
                "orchestra/testbench": "~3.7|~4.0|~5.0|~6.0",
                "phpunit/phpunit": "~7.0|~8.0|~9.0"
            },
            "type": "project",
            "extra": {
                "laravel": {
                    "providers": [
                        "LdapRecord\\Laravel\\LdapServiceProvider",
                        "LdapRecord\\Laravel\\LdapAuthServiceProvider"
                    ]
                }
            },
            "autoload": {
                "psr-4": {
                    "LdapRecord\\Laravel\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "description": "LDAP Authentication & Management for Laravel.",
            "keywords": [
                "adldap2",
                "laravel",
                "ldap",
                "ldaprecord"
            ],
            "support": {
                "issues": "https://github.com/DirectoryTree/LdapRecord-Laravel/issues",
                "source": "https://github.com/DirectoryTree/LdapRecord-Laravel/tree/v1.7.3"
            },
            "funding": [
                {
                    "url": "https://github.com/stevebauman",
                    "type": "github"
                }
            ],
            "time": "2020-09-26T21:51:56+00:00"
        },

**Comment by stevebauman** [comment]
Thanks @gnewmann! This is a bug that came from a recent patch. I'm assuming your local install of LdapRecord is different from your servers, since you likely used `composer update` on your local machine and `composer install` on your server.

I'll have a patch out in 2 hours! 👍

**Comment by gnewmann** [comment]
Great, thanks a lot @stevebauman keep on the good work! It's great :)

**Comment by stevebauman** [comment]
Thanks so much for your kind words @gnewmann! I've just pushed release [v1.12.5](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.12.5) with a fix for this 🎉 .

Can you `composer update` to it on your server and local machine and attempt running your application again on your test server? Let me know how it goes! 😄

**Comment by gnewmann** [comment]
It worked like a charm @stevebauman Thanks alot!

**Comment by stevebauman** [comment]
Awesome! Happy to help @gnewmann! Thanks for letting me know you're up and running 👍
