### ISSUE TITLE
[Bug] unicodepwd is not being encoded 

### ISSUE THREAD

**Issue by raysn0w** [DirectoryTree/LdapRecord#248]
**Environment (please complete the following information):**
 - LDAP Server Type: [ActiveDirectory]
 - PHP Version: [7.4.3]

Hi Steve,

I realized that my users were being created with a blank password, upon checking the automatic encoding it looks like I'm not getting the expected results as stated in the docs:

```
$user = new User();
$user->unicodepwd = 'secret';
$modification = $user->getModifications()[0];
echo "<pre>";
var_dump($modification);
echo "</pre>";`
```

This is the result:

```
array(3) {
  ["attrib"]=>
  string(10) "unicodepwd"
  ["modtype"]=>
  int(3)
  ["values"]=>
  array(1) {
    [0]=>
    string(16) ""secret""
  }
}
```

Any ideas what could be wrong? I'm using Laravel v8.28 / LdapRecord v2.1.3

**Comment by stevebauman** [comment]
Hi @raysn0w,

What `User` model are you using? Are you using a custom model? If so, can you post your models code?

**Comment by raysn0w** [comment]
Hi Steve,

I'm using the User model from "LdapRecord\Models\ActiveDirectory".

Funny enough, this worked for me when creating the user:

```
$user->save();
$user->refresh();
$user->unicodePwd = 'somethingsomething';
$user->save();
```

Even tho the encoding test still fails, it looks like it actually doing it.  Weird.
