### ISSUE TITLE
[Bug] calling method refresh() sets the attributes of the parent record when refresh() returns true

### ISSUE THREAD

**Issue by misenhei** [DirectoryTree/LdapRecord#249]
**Environment (please complete the following information):**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 7.3
 - Larval 8.x
- directorytree/ldaprecord           v2.1.3   A fully-featured LDAP ORM.
- directorytree/ldaprecord-laravel   v2.1.1   LDAP Authentication & Management for Laravel.

**Describe the bug:**

The `refresh()` method is actually returning the attributes and object classes of the parent of the record being requested to be refreshed.

Steps in tinker to reproduce:

```php
$ldapuser = LdapUser::query()->where('uid', '=', '<valid uid>')->first();

// Returns expected dn
$ldapuser->getDn(); 

// Returns the expected record attributes
$ldapuser->getAttributes();

// Returns true
$ldapuser->refresh();

// Returns expected dn
$ldapuser->getDn();

// Returns the attributes, including the object classes, of the
// parent even though getDn() returns the user dn. In this
// case ou=people instead of the attributes of the
// ldapuser record that is under ou=people.
$ldapuser->getAttributes();
```

LdapUser has a scope set to restrict it to look under `ou=people` and has `public static $objectClasses = [];`

Further digging I am able to retrieve the parents calling the fresh() method. Instead of calling refresh() I performed the following:

```php
$ldapuser = LdapUser::query()->where('uid', '=', '<valid uid>')->first();

// Returns expected dn
$ldapuser->getDn();

// Returns the attributes of the parent ou (ou=people) instead
// of matching $ldapuser->getAttributes(). Unlike refresh()
// of course the fresh() method dose not actually set
// the attributes to what is returned.
$ldapuser->fresh()->getAttributes();
```

**Comment by stevebauman** [comment]
Hi @misenhei,

> LdapUser has a scope set to restrict it to look under ou=people and has public static $objectClasses = [];

Can you post your scope that you've added to your `LdapUser` model?

**Comment by misenhei** [comment]
LdapUser
```
namespace App\Ldap;

use LdapRecord\Models\Model;
use App\Ldap\Scopes\OnlyLdapPeople;

class LdapUser extends Model
{
    public static $objectClasses = [];
    
    protected $hidden = [
        'userpassword',
    ];
    
    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope(new OnlyLdapPeople);       
    }
}
```

OnlyLdapPeople
```
namespace App\Ldap\Scopes;

use LdapRecord\Models\Model;
use LdapRecord\Models\Scope;
use LdapRecord\Query\Model\Builder;

class OnlyLdapPeople implements Scope
{
    public function apply(Builder $query, Model $model)
    {
        $query->in('ou=people,dc=test,dc=com');
        $query->select([
            '*',
            'pwdpolicysubentry',
            'pwdchangedtime',
            'pwdaccountlockedtime',
            'pwdfailuretime',
            'memberof',
        ]);
    }
}

```

**Comment by stevebauman** [comment]
Thanks for the report @misenhei! I was able to reproduce this in my own environment and in test cases.

I've just made a new release that contains the patch for this bug ([v2.2.2](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.2.2)).

Run `composer update` and you're all set!
