### ISSUE TITLE
[Support] How to create OrganizationalUnit

### ISSUE THREAD

**Issue by cyrakuse** [DirectoryTree/LdapRecord#254]
Hi,

I'm a newbie with ldaprecord and i can't understand how to create OrganizationalUnit.
I'm using Active Directory.

i tried this : 
`    $parent=OrganizationalUnit::findBy('description', "720");

    $ou= new OrganizationalUnit();
    $ou->createAttribute('cn',"my OU name");
    $ou->createAttribute('description',"my OU description text");
    $ou->inside($parent->getDn());
    $ou->save();`

but it doesn't work. 

Someone can help me please ?

**Comment by stevebauman** [comment]
Hi @cyrakuse,

You can't call the `createAttribute` method on a non-existent object. You instead need to set the attributes, and then call `save()`.

The `OrganizationalUnit`'s name attribute is `ou` and not `cn`. For example:

```php
$ou= (new OrganizationalUnit)->inside($parent->getDn());

$ou->ou = 'My Ou';
$ou->description = 'My OU description';

$ou->save();
```

Hope this helps! Let me know if you need further assistance 👍
