### ISSUE TITLE
[Bug] Group whereNotEquals returns nothing

### ISSUE THREAD

**Issue by HepplerDotNet** [DirectoryTree/LdapRecord#256]
- LDAP Server Type:  ActiveDirectory
 - PHP Version: 8.0.3

```php
$query = Group::query();

return $query->setDn('OU=Acme,dc=example,dc=com')
->where('objectClass', 'group')
->whereNotContains('dn', 'CN=MyGroup,OU=Acme,dc=example,dc=com')->get();
```
Results in an empty LdapRecord\Models\Collection.

```php
$query = Group::query();

return $query->setDn('OU=Acme,dc=example,dc=com'
)->where('objectClass', 'group')->get();
```
Returns a  LdapRecord\Models\Collection containing all groups within DN inclusive the group 'MyGroup' with DN = "CN=MyGroup,OU=Acme,dc=example,dc=com"

**Comment by stevebauman** [comment]
Hi @HepplerDotNet!

This won't work -- you (unfortunately) can't use the `dn` property in LDAP filters.

You will instead have to utilize the `member` attribute:

```php
return $query->setDn('OU=Acme,dc=example,dc=com')
    ->whereNotContains('member', 'CN=MyGroup,OU=Acme,dc=example,dc=com')
    ->get();
```

If you need to search nested group memberships, use this attribute instead:

```php
return $query->setDn('OU=Acme,dc=example,dc=com')
    ->whereNotContains('member:1.2.840.113556.1.4.1941:', 'CN=MyGroup,OU=Acme,dc=example,dc=com')
    ->get();
```

There are currently query builder methods for these attributes (`Group::whereMemberOf($dn)`), but not the inverse (which is what you're looking for). I'll keep this open so I can patch these additional query builder methods in so you will be able to do this easier:

```php
return $query->setDn('OU=Acme,dc=example,dc=com')
    ->whereNotMemberOf('CN=MyGroup,OU=Acme,dc=example,dc=com', $nested = true)
    ->get();
```

**Comment by HepplerDotNet** [comment]
@stevebauman 
```
return $query->setDn('OU=Acme,dc=example,dc=com')
    ->whereNotEquals('member', 'CN=MyGroup,OU=Acme,dc=example,dc=com')
    ->get();
```
Returns MyGroup too. Unescaped Query:
`(&(objectclass=top)(objectclass=group)(!(member=MyGroup,OU=Acme,dc=example,dc=com)))`

 
```
return $query->setDn('OU=Acme,dc=example,dc=com')
    ->whereNotEquals('member:1.2.840.113556.1.4.1941:', 'CN=MyGroup,OU=Acme,dc=example,dc=com')
    ->get();
```
Returns MyGroup too. Unescaped Query:
`(&(objectclass=top)(objectclass=group)(!(member:1.2.840.113556.1.4.1941:=MyGroup,OU=Acme,dc=example,dc=com)))`

**Comment by stevebauman** [comment]
Ah my mistake -- I think I misread (or misunderstood) your issue. If you're looking to retrieve all groups *except* for `My Group`, then you'll have to exclude it by name (`cn`):

```php
return $query->setDn('OU=Acme,dc=example,dc=com')
    ->whereNotEquals('cn', 'MyGroup')
    ->get();
```

The above will get you all descendants of `OU=Acme,dc=example,dc=com`. If you only want immediate children, then use the `listing()` method:

```php
return $query->setDn('OU=Acme,dc=example,dc=com')
    ->whereNotEquals('cn', 'MyGroup')
    ->listing()
    ->get();
```

There is the option of using an Object GUID as well, but there isn't an easy way to use GUID's in `where` clauses (I'm going to add this feature in as well):

```php
use LdapRecord\Utilities;

$excludedGroup = Group::findOrFail('CN=MyGroup,OU=Acme,dc=example,dc=com');

$groupGuid = Utilities::stringGuidToHex($excludedGroup);

$groups = Group::whereRaw('objectguid', '!=', $groupGuid)->get();
```

Can you give those a shot?

**Comment by HepplerDotNet** [comment]
@stevebauman 
```php
return $query->setDn('OU=Acme,dc=example,dc=com')
    ->whereNotEquals('cn', 'MyGroup')
    ->get();
```
Works perfect. Thank you so much!

**Comment by stevebauman** [comment]
Awesome! No problem, happy to help! 😄
