### ISSUE TITLE
[Question] How to create (manage) group scope and group type?

### ISSUE THREAD

**Issue by nohnaimer** [DirectoryTree/LdapRecord#264]
How to create/update type = Distribution and scope = Domain local group in Active Directory via ldaprecord?

**Comment by stevebauman** [comment]
Hey @nohnaimer!

According to some docs online, I believe you would set this manually like so:

```php
use LdapRecord\Models\ActiveDirectory\Group;

$group = new Group();

$group->groupType = 4;

$group->save();
```

References:

- https://ldapwiki.com/wiki/GroupType
- https://docs.microsoft.com/en-us/windows/win32/adschema/a-grouptype

INT | Hex | Description
-- | -- | --
0 | 0x00000000 | MSDN says it could be 0 but not what "0" is.
1 | 0x00000001 | Specifies a group that is created by the system.
2 | 0x00000002 | Specifies a group with Global Group.
4 | 0x00000004 | Specifies a group with Domain Local Group.
8 | 0x00000008 | Specifies a group with Universal Group.
16 | 0x00000010 | Specifies an APP_BASIC group for Windows Server Authorization Manager.
32 | 0x00000020 | Specifies an APP_QUERY group for Windows Server Authorization Manager.
2147483648 | 0x80000000 | Specifies a Security Group. If this bit is not set, then the group is a Distribution Group.

--- 

Can you give that a shot?

**Comment by nohnaimer** [comment]
Thank you! Works.

**Comment by stevebauman** [comment]
Awesome! Happy to help. Glad you’re up and running 😄
