### ISSUE TITLE
[Support] whereContains and orWhereContains aren't work as expected

### ISSUE THREAD

**Issue by satyakresna** [DirectoryTree/LdapRecord#269]
Hi @stevebauman, when I try to search a user by more than 1 one words it doesn't work.

Example.

```
User

Name: Charlie Brown => as givenname
ID Pengenal: 123456 => as cn
Email: charlie@snoopy.com => as mail
```

I search with entry text `charlie` or `Charlie` it works. But, when I search with entry text `charlie brown` or `Charlie Brown` it doesn't work. Also, this entry text is flexible. It can be use as a string to search `givenname`, `cn` and `mail`. I also try to search with entry text `123` or `123456` but it doesn't work.

Here's my code.

```php
<?php

namespace App\Ldap;

use LdapRecord\Models\Model;

class User extends Model
{

    public function scopeSearch(Builder $query, $search)
    {
        if (!empty($search)) {
            return $query->whereContains('givenname', $search)
                ->orWhereContains('mail', $search)
                ->orWhereContains('cn', $search);
        }
    }
}
```

I was expect that the search works like `%$search%` in SQL but it doens't. Could you please give a solution about this case? Thanks.

**Comment by stevebauman** [comment]
Hi @satyakresna,

> I search with entry text charlie or Charlie it works. But, when I search with entry text charlie brown or Charlie Brown it doesn't work.

Which directory server are you connecting to (Active Directory, OpenLDAP, etc.)?

> It can be use as a string to search givenname, cn and mail. I also try to search with entry text 123 or 123456 but it doesn't work.

You'll want to nest this search in an `orFilter` for it to work as you're intending:

```php
public function scopeSearch(Builder $query, $search)
{
    if (!empty($search)) {
        return $query->orFilter(function ($q) use ($search) {
            return $q
                ->whereContains('givenname', $search)
                ->whereContains('mail', $search);
                ->whereContains('cn', $search);
        });
    }
}
``` 

This will create the below filter:

```
(|(givenname=*search*)(mail=*search*)(cn=*search*))
```

Can you give this a shot?

**Comment by satyakresna** [comment]
Hi Steve. I'm using OpenLDAP. Is it possible with the solution above?

**Comment by satyakresna** [comment]
Hi Steve. Your solution is perfect in OpenLDAP! Thanks a lot.

**Comment by stevebauman** [comment]
Awesome @satyakresna! Really glad you're up and running! And no problem -- always happy to help 😄
