### ISSUE TITLE
[Support] How to set password of user using User OpenLDAP model?

### ISSUE THREAD

**Issue by satyakresna** [DirectoryTree/LdapRecord#272]
Hi @stevebauman, in User OpenLDAP model `LdapRecord\Models\OpenLDAP\User` it has `setPassword` method. The question is how to set a password with `md5` encryption using `setPassword` method? Does like this?

```php
$user = new LdapRecord\Models\OpenLDAP\User;

$user->setPassword('mysecretpassword, 'md5');
```

I check in docs doesn't explain how to set password for OpenLDAP?

**Comment by stevebauman** [comment]
Hi @satyakresna!

You're right -- the docs are lacking on OpenLDAP specifics. I don't have an OpenLDAP server to easily test on, so I've been relying on the community and their knowledge.

To answer your question, you will have to create your own model and extend the current one. There's two properties you can override on the `User` model:

- `$passwordAttribute` - The name of the attribute that contains the users password
- `$passwordHashMethod` - The hashing method (`ssha`, md5`, `encode`, etc.)

https://github.com/DirectoryTree/LdapRecord/blob/ed79f7fc18355fbfde305793cffcad39bd1deed6/src/Models/OpenLDAP/User.php#L14-L26

For your case, you would override the `$passwordHashMethod` and set it to `md5`:

```php
use LdapRecord\Models\OpenLDAP\User as BaseUser;

class User extends BaseUser
{
    protected $passwordHashMethod = 'md5';
}
```

All of the available hashing mechanisms are listed here in the docs:

https://ldaprecord.com/docs/core/v2/helpers/#passwords

Let me know if you need any further information! 👍

**Comment by satyakresna** [comment]
Hi @stevebauman, it works great! Thank you.
