### ISSUE TITLE
[Feature] Translate error messages

### ISSUE THREAD

**Issue by sotten** [DirectoryTree/LdapRecord#283]
Thank you for this wonderful package. 
Is it possible to make the error messages translatable in Laravel?
For example for:
https://github.com/DirectoryTree/LdapRecord/blob/e31ba6088989969fbf93a8ea6e43a9dc281863c5/src/DetectsErrors.php#L16

**Comment by stevebauman** [comment]
Hi @sotten, thanks so much for your kind words! I'm glad you find LdapRecord useful 😄 

In regards to your question, these error messages are from PHP's LDAP exception. To my knowledge, PHP does not throw exceptions with messages in other languages.

Can you walk me through your use-case a bit as to why you would need these messages translatable?

**Comment by sotten** [comment]
I use LdapRecord-Laravel for authentication in Laravel with Jetstream and Livewire. There is the possibility to translate errors there. See: https://github.com/DirectoryTree/LdapRecord-Laravel/blob/master/resources/lang/en/errors.php

It would be useful from my point of view to show connection errors in local language as well, since the complete website does not use English. Many people can't read English or their letters.

**Comment by stevebauman** [comment]
Hi @sotten,

I understand. In this case, you will have to handle the `LdapException` that is thrown and attempt to translate the message yourself. Since this package is standalone (i.e. makes no assumptions or requirements as to what PHP framework you use), we can't implement the capabilities of translation into the LdapRecord core.

However, you can implement this yourself quickly using Laravel's [exception handler](https://laravel.com/docs/8.x/errors#the-exception-handler) and [JSON translation files](https://laravel.com/docs/8.x/localization#using-translation-strings-as-keys):

```php
// app/Exceptions/Handler.php

use LdapRecord\LdapRecordException;

/**
 * Register the exception handling callbacks for the application.
 *
 * @return void
 */
public function register()
{
    $this->renderable(function (LdapRecordException $e, $request) {
        return response(__($e->getMessage()) , 500);
    });
}
```

Then, inside your language file (for example, a French translation file: `resources/lang/fr.json`):

```js
{
    "Can't contact LDAP server": "Impossible de contacter le serveur LDAP."
}
```

Let me know if your have any further questions!

**Comment by sotten** [comment]
Hi @stevebauman,

Unfortunately, the solution you suggested did not work. I think there is a connection with [this issue](https://github.com/DirectoryTree/LdapRecord-Laravel/issues/196).
I did the following with [jetstream altering response](https://ldaprecord.com/docs/laravel/v2/auth/database/laravel-jetstream/#altering-the-response) and [breeze altering response](https://ldaprecord.com/docs/laravel/v2/auth/database/laravel-breeze/#altering-the-response):

```
// app/Providers/AuthServiceProvider.php

/**
* Register any authentication / authorization services.
*
* @return void
*/
public function boot()
{
    // ...

    BindFailureListener::setErrorHandler(function ($message, $code = null) {
        if ($message === "Can't contact LDAP server") {
            throw ValidationException::withMessages([
                'email' => __("Can't contact LDAP server"),
            ]);
        }
    });
}
```
```
// resources/lang/xx.json

{
    "Can't contact LDAP server": "LDAP-Server kann nicht kontaktiert werden"
}
```
it is not very nice, but I have not found another solution. If there is a better solution, let me know.
You can see my starting point [here](https://github.com/sotten/ldap).
I have another [problem](https://github.com/DirectoryTree/LdapRecord-Laravel/issues/287) with Jetstream and LDAP, maybe it is a similar case.

Thank you for your help, this is a fantastic extension!

**Comment by stevebauman** [comment]
Apologies for the late reply, going through all the issues today on the LdapRecord repo. I'm glad you were able to resolve this! And thanks for your kind words! 😄
