### ISSUE TITLE
[Support] Cannot get the correct data of Groups

### ISSUE THREAD

**Issue by satyakresna** [DirectoryTree/LdapRecord#285]
Hi @stevebauman, I cannot get the correct data of Groups in OpenLDAP. Here's the code

#### Model

```php
<?php

namespace App\Ldap;

use LdapRecord\Models\Model;
use LdapRecord\Models\OpenLDAP\Group as BaseGroup;

class Group extends BaseGroup
{
    public function members()
    {
        return $this->hasMany([
            Group::class, User::class
        ], 'memberof')->using($this, 'member');
    }
}
```

#### Controller

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ldap\Group;

class GroupController extends Controller
{
    public function index()
    {
        dd(Group::get());
    }
}
```

#### Current Result

![not-expected-result](https://user-images.githubusercontent.com/11099186/119440812-984e3a00-bd57-11eb-8c54-92f727e32bf3.PNG)

##### Expected Result

I expect result that has `ou=groups`

![ldap-keycloak](https://user-images.githubusercontent.com/11099186/119440782-879dc400-bd57-11eb-893e-495ff7e270f3.PNG)

Could you please help about this case?

**Comment by stevebauman** [comment]
Hi @satyakresna!

It looks like you're actually looking to fetch these groups inside of the `groups` OU, not retrieve them as members of an LDAP object.

You can retrieve these by setting the base DN of your search by using the `in()` or `setDn`() method on the query builder:

```php
use LdapRecord\Models\OpenLDAP\Group;

$groups = Group::in('ou=groups,{base}')->get();
```

> Note: The `{base}` string will be automatically substituted for your configured `base_dn`.

If this doesn't return all of the groups inside of the OU, inspect each of the group's object classes to ensure they all contain the same attributes.

For example, these are the default object classes included in LdapRecord's `Group` model:

https://github.com/DirectoryTree/LdapRecord/blob/13879553fed736db3d5225662337cb99ec5662ba/src/Models/OpenLDAP/Group.php#L12-L15

If these differ from your LDAP server, create your own model and set the `objectclasses` static property with the ones that match:

```php
namespace App\Ldap;

use LdapRecord\Models\Model;
use LdapRecord\Models\OpenLDAP\Group as BaseGroup;

class Group extends BaseGroup
{
    public static $objectClasses = ['top', 'group'];

    // ...
}
```

Can you give that a shot?

**Comment by satyakresna** [comment]
Hi @stevebauman, thanks for your support! It works great right now by update `$objectClasses` static property below:

```php
public static $objectClasses = ['top', 'groupOfNames'];
```

The result like what I expected.
