### ISSUE TITLE
deleteAttribute ErrorException

### ISSUE THREAD

**Issue by SamuelWei** [DirectoryTree/LdapRecord#291]
**Environment (please complete the following information):**
 - LDAP Server Type: OpenLDAP
 - LdapRecord-Laravel Major Version: v2
 - PHP Version: 7.4

**Describe the bug:**

Trying to call deleteAttribute on a LdapRecord\Models\OpenLDAP\User object fails if parameter is a string or array

```
        DirectoryEmulator::setup('default');
        $user = User::create([
            'givenName'              => 'John',
            'sn'                     => 'Doe',
            'cn'                     => 'John Doe',
            'mail'                   => 'john.doe@example.com',
            'uid'                    => 'johnd',
            'role'                   => 'test',
        ]);

        /**
         * ErrorException : Array to string conversion
            \vendor\directorytree\ldaprecord-laravel\src\Testing\Emulated\EmulatesModelQueries.php:82
            \vendor\directorytree\ldaprecord\src\Models\Model.php:1183
         */
        $user->deleteAttribute('role');

        /**
         * ErrorException : Undefined offset: 0
            \vendor\directorytree\ldaprecord\src\Models\Model.php:1196
         */
        $user->deleteAttribute(['role']);
```

**Comment by stevebauman** [comment]
Okay I've just patched this: 443be902a44bbf58b264fe16685c5f1e78e5a9c3, 92b46a15d34736c8a28ac551b436fe3ad0ca9be0

I'm going to make a new release tomorrow morning with fresh eyes to ensure it's clean 👍 . I'll comment here once I've created the release so you're aware.

**Comment by SamuelWei** [comment]
Thank you @stevebauman

**Comment by stevebauman** [comment]
[Release has been created](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.4.7)! 🎉

**Comment by SamuelWei** [comment]
@stevebauman I still have the issue when calling:

```
deleteAttribute($attribute); 
deleteAttribute([$attribute]); 
deleteAttribute([$attribute => []]); 
```

`ErrorException : Array to string conversion \vendor\directorytree\ldaprecord-laravel\src\Testing\Emulated\EmulatesModelQueries.php:82`

I call this function in a laravel unit test.

**Comment by stevebauman** [comment]
Thanks @SamuelWei, I've just patched this in LdapRecord-Laravel -- 06244ce.

Once the tests pass I'll create a new release 👍 

Let me know if it works!

**Comment by stevebauman** [comment]
[Release](https://github.com/DirectoryTree/LdapRecord-Laravel/releases/tag/v2.3.2) has been created 🎉

**Comment by SamuelWei** [comment]
Thank you @stevebauman . It is fixed, my tests are running again :)

**Comment by stevebauman** [comment]
Awesome @SamuelWei, glad to hear it! Happy to help 😄
