### ISSUE TITLE
Testing OpenLDAP models

### ISSUE THREAD

**Issue by gjm** [DirectoryTree/LdapRecord#292]
Is there a way to test OpenLDAP models? Reading the docs I can only see some shallow docs to test authentication attempts.

I would like to test code that looks something like this:
```php
$user = new User(['dn' => 'john', 'cn' => 'John Doe']);
$user->save();

$user2 = User::find('dn=john,dc=local,dc=com');
$this->assertEquals($user, $user2);
```

Is there a way to do something like this?

**Comment by stevebauman** [comment]
Hi @gjm,

To perform identity checks against models, you can use the `is()` method:

```php
$user = new User(['dn' => 'john', 'cn' => 'John Doe']);
$user->save();

$user2 = User::find('dn=john,dc=local,dc=com');

$this->assertTrue($user->is($user2));
```

The `is()` method checks that the users distinguished name and connection name are identical (compared strictly).

Does this answer your question?

**Comment by gjm** [comment]
@stevebauman sorry I probably didn't make myself clear. I want to fake the connections. I want to be able to test it out without actually connecting to the server. I thought that was implied.
