### ISSUE TITLE
[Bug] Auth::user()->ldap object has attributes which are supposed to be "hidden" when using Laravel 

### ISSUE THREAD

**Issue by mgiritli** [DirectoryTree/LdapRecord#295]
**Environment (please complete the following information):**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 7.4

In my user model I got:

```
use LdapRecord\Models\OpenLDAP\User as Model;
class User extends Model
{
...
protected $hidden = ['userPassword', 'sshpublickey' ];
...
}
```

So I expect not to see those attributes when I pull the users entry from LDAP server. However, it seems that hidden property has no effect when I get the user object through Auth::user()->ldap in Laravel. I still get the attributes userPassword and sshpublickey. Is there anything I can do to hide these attributes when getting user info this way? Am I missing something here or is this a bug?

Many thanks in advance :-)

**Comment by stevebauman** [comment]
Hi @mgiritli, as such with Laravel's Eloquent, the `$hidden` property only omits the defined properties from being included in results when `json_encode`'ed.

For example:

```php
$user = User::find('cn=John Doe,dc=local,dc=com');

// Will not include the the `userPassword` or `sshpublickey` property.
echo json_encode($user);
```

This is described in the documentation: https://ldaprecord.com/docs/core/v2/models/#serialization

> You may want to exclude certain attributes from being **included in the serialization of your model**, such as `userPassword` for OpenLDAP.

Hope this helps! 👍
