### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by Guillermocen** [DirectoryTree/LdapRecord#302]
I am trying to install ldap record in a project and it shows me the following error during installation:

![image](https://user-images.githubusercontent.com/22781509/122487363-1d202280-cfa9-11eb-98b8-858496cf1f10.png)

how can i solve it please
php v 7.4.7
laravel v 8.40
php ldap extension enabled

**Comment by stevebauman** [comment]
Hi @Guillermocen,

It looks like you’re upgrading from Adldap2 — is that correct? Make sure you delete the Adldap2 configuration file and then publish the LdapRecord config file.

**Comment by Guillermocen** [comment]
yes, I just uninstalled ldap2 and installed ldap record and there was no problem, thanks for the attention
