### ISSUE TITLE
[Support] UAC - passwordCannotBeChanged - Not working

### ISSUE THREAD

**Issue by mazacmartin** [DirectoryTree/LdapRecord#303]
**Environment:**
 - LDAP Server Type: MS ActiveDirectory
 - PHP Version: 7.3.22

**Describe the bug:**

the function to set the attribute for the user account "cannot change password" does not work, here is a code sample

```php

function lr_set_acc_atr($user)
{

    $uac = new AccountControl();

    // Disable User Must Change Password at Next Logon
    //$user->update(['pwdlastset' => -1]);

    // The user account password cannot be changed
    $uac->passwordCannotBeChanged();

    // The user account is normal, enabled account
    $uac->accountIsNormal();

    // The user account password does not expire
    $uac->passwordDoesNotExpire();

    // UAC builder
    $user->userAccountControl = $uac;

    $user->save();
}

```

this function works because when it triggers this: 

```php
$uac->passwordDoesNotExpire();
```
is applied

here is a picture of exactly what happens to me after running the function:

![image](https://user-images.githubusercontent.com/45457229/122554093-d4b04580-d038-11eb-95af-5bd42878fc05.png)

also I try by init:

```php
$user->userAccountControl = 64;
```

**Comment by Mateusz2598** [comment]
You need to use security connection with your ldap server. In non-security connection password change is not possible.

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2?redirectedfrom=MSDN

**Comment by mazacmartin** [comment]
> You need to use security connection with your ldap server. In non-security connection password change is not possible.
> 
> https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2?redirectedfrom=MSDN

Thanks for the feedback.
I don't try to change the password (yes I know that I need a securyty connection to the ldap SSL/TLS server to work with the password).   
I'm having a problem with the property/checkbox "User cannot change password" as is visible on screen.

**Comment by stevebauman** [comment]
Hi @mazacmartin,

What happens when you attempt to save the user? Do you receive an exception? Or the UAC value you set is simply ignored by your AD server?

**Comment by mazacmartin** [comment]
> Hi @mazacmartin,
> 
> What happens when you attempt to save the user? Do you receive an exception? Or the UAC value you set is simply ignored by your AD server?

Hi @stevebauman 

as I wrote in the assignment I will use this code where this is done and this is not done no error nothing

```php

# This works
$uac->passwordDoesNotExpire();

# This doesnt work
$uac->passwordCannotBeChanged();

# or I try it as alternative and this also doesnt work
$user->userAccountControl = 64;
```

thank you for your interest and if I can supply some logs please info how to get them because my apache or php log on this topic is silent

**Comment by vascocarreira** [comment]
Hi, all.

I'm having an issue with UAC and it may be related to this one.

After creating a user, I try to set the account as normal but it returns the following error:
**ldap_modify_batch(): Batch Modify: Type or value exists**

This happens in version 2.4.0, but the same code works in version 1.7.6.

Is there any change in version 2.4 and I need to adapt my code or is this an issue of the package?

**Comment by stevebauman** [comment]
Hi @vascocarreira,

Please create a new issue and post the entire code you have written which causes the exception.
