### ISSUE TITLE
[Bug] Query whereEndsWith seems to be incompatible with distinguishedname

### ISSUE THREAD

**Issue by wmmarcus** [DirectoryTree/LdapRecord#311]
**Environment (please complete the following information):**
 - LDAP Server Type: [Active Directory]
 - PHP Version: [7.3.28]

**Describe the bug:**
Trying to make the distinguishedname field part of a simple text query. For test user they have the attribute:
`"distinguishedname":["CN=Rick Edwards,OU=Users,OU=PWDApp,DC=acmelabs,DC=local"]`

However the code:
```
$users = User::whereEndsWith('distinguishedname','DC=acmelabs,DC=local')->get();
print "$users\n";
```

Returns only empty brackets.
`[]`

I know there are other ways to do this, but I am trying to layer this with testing multiple attributes once the simple check works.

**Comment by stevebauman** [comment]
Hi @wmmarcus,

LDAP directories cannot be filtered by object's distinguished name (with the caveat of object relationship attributes that contain distinguished names, such as `manager`, `member` and `memberof`).

You must instead perform a search with the root set in the distinguished name you're looking to query:

```php
$users = User::in('DC=acmelabs,DC=local')->get();
```

Hope this helps!
