### ISSUE TITLE
[Bug] groups()->recursive()->get() results in endless loop when you have LDAP groups member of each other

### ISSUE THREAD

**Issue by karstennilsen** [DirectoryTree/LdapRecord#319]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - LdapRecord-Laravel Major Version: 2.3.3
 - PHP Version: 7.4

Group A members:
 - User
 - Group B

Group B members:
 - Group A

When you do Auth::user()->ldap->groups()->recursive()->get(), it results in an endless loop.
Active directory groups member of each other is uncommon but supported.

**Comment by stevebauman** [comment]
Thanks for the report @karstennilsen! I've just patched this. A new release will be out today with this fix included 👍
