### ISSUE TITLE
Searching for all objects in an OU

### ISSUE THREAD

**Issue by drifter104** [DirectoryTree/LdapRecord#333]
I'm attempting to return all objects in an OU but seem to be hitting a wall.

First I tried the following and this returned the expected object

```php
Container::getDefaultConnection()->query()->where('distinguishedname','CN= group,OU=Manager,OU=Applications,OU=Security,OU=Security Groups,DC=example,DC=com')->get()
```

Then I tried; but this returned no results, I expected the same result as above at this point.

```php
Container::getDefaultConnection()->query()->whereContains('distinguishedname','CN= group,OU=Manager,OU=Applications,OU=Security,OU=Security Groups,DC=example,DC=com')->get()
```

I had assumed the following could return all objects in the OU

```php
Container::getDefaultConnection()->query()->whereContains('distinguishedname','OU=Manager,OU=Applications,OU=Security,OU=Security Groups,DC=example,DC=com')->get()
```

I'm assuming "whereContains" can be used to search within distinguishedname, is that wrong? If so how would you return all objects or a specific type of object within an OU.

**Comment by stevebauman** [comment]
Hi @drifter104,

LDAP does not support querying object distinguished names.

To get all of the objects inside of an OU, set the DN of the query equal to the OU's DN (using either the `in()` or `setDn()` query builder method), and then call `get()`:

```php
$objects = Container::getDefaultConnection()
    ->query()
    ->in('OU=Manager,OU=Applications,OU=Security,OU=Security Groups,DC=example,DC=com')
    ->get();
```

Let me know if you still have issues and I'll re-open this. 👍

**Comment by drifter104** [comment]
Hi @stevebauman 

I've changed my code a little. I'm basically trying to check to see what groups in a particular OU as user is a member of.

This returns the objects I wanted but I always get "domain users" returned and it definitely isn't in the OU that I'm requesting.

`		$groups = $username->groups()->in('OU=Manager,OU=Applications,OU=Security Groups,OU=CWP Security Groups,DC=example,DC=com')->get();
		dd($groups);` 
![dd_groups](https://user-images.githubusercontent.com/47455948/134161436-df6c85b7-5b1c-4c27-b555-a20bc7c65106.png)

Is this just an LDAP/Active DIrectory thing?
