### ISSUE TITLE
[Support] Support php 8.1

### ISSUE THREAD

**Issue by nohnaimer** [DirectoryTree/LdapRecord#359]
**Environment:**
 - LDAP Server Type: ActiveDirectory and OpenLDAP
 - PHP Version: 8.1

Hi,
When can you add support php 8.1? Can't update my project due to errors LdapRecord:
<img width="1462" alt="Снимок экрана 2021-11-29 в 11 54 11" src="https://user-images.githubusercontent.com/8865830/143836965-625753d2-5a89-484d-9de4-aa940459d63b.png">
Thank you.

**Comment by stevebauman** [comment]
Thanks for the report @nohnaimer! I'll have a patch out today 👍

**Comment by nohnaimer** [comment]
Not working...
<img width="1792" alt="Снимок экрана 2021-11-30 в 20 55 52" src="https://user-images.githubusercontent.com/8865830/144101754-00e6bc02-9c1e-4b60-b006-48ba8430dfee.png">
Need update tightenco/collect...

**Comment by stevebauman** [comment]
Ah okay -- it appears it's being worked on:

https://github.com/tighten/collect/issues/261

**Comment by mattstauffer** [comment]
@stevebauman @nohnaimer Fixed on the Collect side. Thanks for your patience!

**Comment by stevebauman** [comment]
Awesome, thanks @mattstauffer! 😄

**Comment by nohnaimer** [comment]
@stevebauman hi,
collect fixed - updating your Collect dependency to 8.68.0 or higher...
Thank you.
