### ISSUE TITLE
[Bug] is_resource() always returns false with PHP 8.1

### ISSUE THREAD

**Issue by villfa** [DirectoryTree/LdapRecord#369]
**Environment:**
 - LDAP Server Type: n/a
 - PHP Version: 8.1

From the [PHP 8.1 migration guide](https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.resource2object):

    The LDAP functions now accept and return LDAP\Connection objects instead of ldap link resources.
    The LDAP functions now accept and return LDAP\Result objects instead of ldap result resources.
    The LDAP functions now accept and return LDAP\ResultEntry objects instead of ldap result entry resources.

So it means that `is_resource()` will always return *false* on these objects.

There are 2 ways to fix that while maintaining compatibility with PHP 8.1 and below:

1. by only checking if the value is truthy:
   ```diff
   -if (is_resource($result)) {
   +if ($result) {
       // do something
    }
    ```
2. by checking if the value is a resource or the expected object:
   ```diff
   -if (is_resource($result)) {
   +if (is_resource($result) || $result instanceof LDAP\Result) {
       // do something
    }
    ```

IMHO the option 2 is better since it prevents passing wrongs objects.

**Comment by stevebauman** [comment]
Hey @villfa, I agree with option 2 👍 , I'll have a patch out shortly. Thanks for the detailed issue!
