### ISSUE TITLE
[Support]

### ISSUE THREAD

**Issue by testlorenzospa** [DirectoryTree/LdapRecord#375]
**Environment:**
 - LDAP Server Type: LdapRecord
 - PHP Version: 7.4

Hello.

With ADLDAP2, I can find a user with the below code
$provider->search()->users()->find("XXX");

and then I can get the DN with the function
getDn();

With LdapRecord, how I can find a user to get the DN?
I have try with
$connection->query()->where("CN","=", "XXX")->get();

but this return an array.

Can you have an exemple to search a user to get his DN?

Thanks.

**Comment by stevebauman** [comment]
Hi @testlorenzospa,

LdapRecord uses an Active Record style syntax, meaning you have to execute queries on [models](https://ldaprecord.com/docs/core/v2/models) themselves.

I'm not sure which LDAP server you're connecting to (you inserted `LdapRecord` as the server type), but if you're connecting to an Active Directory server, then you can use the `ActiveDirectory\User` model:

```php
use LdapRecord\Models\ActiveDirectory\User;

$users = User::where('cn', '=', 'XXX')->get();

foreach ($users as $user) {
    // Get the users distinguished name.
    echo $user->getDn();
}
```

Hope this helps! Closing as this should answer your question 👍

**Comment by testlorenzospa** [comment]
Hi @stevebauman.

Thanks for this reply.

I'll try your suggestion.

Thanks again.

**Comment by stevebauman** [comment]
Happy to help @testlorenzospa, let me know if you need any further assistance 👍
