### ISSUE TITLE
[Support] Getting members of a group

### ISSUE THREAD

**Issue by testlorenzospa** [DirectoryTree/LdapRecord#376]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.4

Hello.

I call the method
$group = Group::where("cn","=","XXX");

to retrive a specific group.
Following the documentation, then I call
 $group->members()->get()

to get the members but I have the below error

Fatal error: Uncaught BadMethodCallException: Call to undefined method LdapRecord\Query\Model\ActiveDirectoryBuilder::members()

How I can get the members of a specific group?

Many thanks.

**Comment by stevebauman** [comment]
Hi @testlorenzospa,

You have to call `first()` to retrieve the first result after adding a where clause with the LdapRecord query builder:

```php
$group = Group::where("cn","=","XXX")->first();

$members = $group->members()->get();
```

https://ldaprecord.com/docs/core/v2/models/#retrieving-models

**Comment by testlorenzospa** [comment]
Hello @stevebauman.

Thanks.

It is works.

Thanks again.
