### ISSUE TITLE
[Support] Schema

### ISSUE THREAD

**Issue by testlorenzospa** [DirectoryTree/LdapRecord#377]
**Environment:**
 - LDAP Server Type: ActiveDirectory / OpenLDAP
 - PHP Version: 7.4

Hello.

In Adldap2, if I pass the schema in the configuration settings I can get the right attribute for a user (e.g. uid instead userprincipalname).

With LdapRecord, how I can get the right attribute (uid instead the userprincipalname) if the scheme of a LDAP server is OpenLDAP?

Thanks.

**Comment by stevebauman** [comment]
Hi @testlorenzospa,

To get a users `uid`, you access it directly off the model instead of using a method. For example:

```php
use LdapRecord\Models\ActiveDirectory\User;

$user = User::find('cn=john,dc=local,dc=com');

echo $user->uid[0] ?? null;

// Or:

echo $user->getFirstAttribute('uid');
```

Hope this helps! Let me know if you have any further questions 👍

**Comment by testlorenzospa** [comment]
Hi @stevebauman.

Sorry for the late of this response.

Thanks.
Now it is clear.

Thanks again.
