### ISSUE TITLE
[Bug] Query chunking stops after returning the first page of results

### ISSUE THREAD

**Issue by bmw27** [DirectoryTree/LdapRecord#388]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.1

**Describe the bug:**
When I use the `chunk` method, the query stops after returning only one page of results. So for the query below, I'd get one page of 500 entries, but nothing more. I've tried changing the page size to different values like 10 or 1000, but still only get one page of results back.

```php
use App\Models\Person;
use LdapRecord\Models\ActiveDirectory\Entry;
use LdapRecord\Query\Builder;

Entry::query()
    ->select([
        'cn',
        'mail',
    ])
    ->where(...)
    ->where(...)
    ->orFilter(function (Builder $query) {
        $query
            ->where(...)
            ->where(...)
            ->where(...);
    })
    ->chunk(500, function ($entries) {
        foreach ($entries as $entry) {
            Person::create([
                "name" => $entry->getFirstAttribute("cn"),
                "email" => $entry->getFirstAttribute("mail"),
            ]);
        }
    });
```

**Comment by stevebauman** [comment]
Hi @bmw27,

I'm not able to reproduce this on my own Active Directory server on PHP 8.0 or PHP 8.1.

Can you dive into the source and see if the resource is for some reason returning `false` or `null` here?

https://github.com/DirectoryTree/LdapRecord/blob/cece84322d1c5199a48a910ad9974692f648ea57/src/Query/Pagination/LazyPaginator.php#L23

**Comment by bmw27** [comment]
Thanks for the response. I ran `composer update`, but unfortunately that didn't fix it. I was able to figure out that the `$resource` variable is being initialized as an `LDAP\Result` object. Here's what it shows when I `var_dump` the `$resource` variable:

```php
object(LDAP\Result)#1078 (0) {
}
```

My guess is that there's some configuration on the Active Directory server itself that's messing with the `chunk` method, and I don't have access to this particular server to check 😅

**Comment by bmw27** [comment]
Same result. I set it to chunk by 250, but then it stopped after the first page of 250 records.

**Comment by bmw27** [comment]
@stevebauman I just tried a free test ldap server (ldap.forumsys.com) and it worked just fine with chunking, which makes me think it's a problem with the specific server I'm using, and not the package. The main difference between the test server and the production one, is that the production server uses SSL.

**Comment by stevebauman** [comment]
Hmmm — can you post your configuration with sensitive details omitted?

**Comment by bmw27** [comment]
Btw, I should have mentioned this earlier...I'm using LdapRecord-Laravel in case that matters.

Here are my env variables:

```
LDAP_LOGGING=true
LDAP_CONNECTION=default
LDAP_HOST=example.com
LDAP_USERNAME="uid=username,ou=Users,dc=example,dc=com"
LDAP_PASSWORD=password
LDAP_PORT=636
LDAP_BASE_DN="ou=People,dc=eaxmple,dc=com"
LDAP_TIMEOUT=5
LDAP_SSL=true
LDAP_TLS=false
```

And here's my config file (I haven't changed this from the default output):

```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default LDAP Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the LDAP connections below you wish
    | to use as your default connection for all LDAP operations. Of
    | course you may add as many connections you'd like below.
    |
    */

    'default' => env('LDAP_CONNECTION', 'default'),

    /*
    |--------------------------------------------------------------------------
    | LDAP Connections
    |--------------------------------------------------------------------------
    |
    | Below you may configure each LDAP connection your application requires
    | access to. Be sure to include a valid base DN - otherwise you may
    | not receive any results when performing LDAP search operations.
    |
    */

    'connections' => [

        'default' => [
            'hosts' => [env('LDAP_HOST', '127.0.0.1')],
            'username' => env('LDAP_USERNAME', 'cn=user,dc=local,dc=com'),
            'password' => env('LDAP_PASSWORD', 'secret'),
            'port' => env('LDAP_PORT', 389),
            'base_dn' => env('LDAP_BASE_DN', 'dc=local,dc=com'),
            'timeout' => env('LDAP_TIMEOUT', 5),
            'use_ssl' => env('LDAP_SSL', false),
            'use_tls' => env('LDAP_TLS', false),
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | LDAP Logging
    |--------------------------------------------------------------------------
    |
    | When LDAP logging is enabled, all LDAP search and authentication
    | operations are logged using the default application logging
    | driver. This can assist in debugging issues and more.
    |
    */

    'logging' => env('LDAP_LOGGING', true),

    /*
    |--------------------------------------------------------------------------
    | LDAP Cache
    |--------------------------------------------------------------------------
    |
    | LDAP caching enables the ability of caching search results using the
    | query builder. This is great for running expensive operations that
    | may take many seconds to complete, such as a pagination request.
    |
    */

    'cache' => [
        'enabled' => env('LDAP_CACHE', false),
        'driver' => env('CACHE_DRIVER', 'file'),
    ],

];
```

**Comment by stevebauman** [comment]
Are you able to try chunking without SSL on your server? Since I'm not able to reproduce, I can't help much besides pure speculation.

**Comment by bmw27** [comment]
Looking at the logs, without SSL, the connection basically hangs trying to bind to the LDAP server. It never times out or throws an error.

**Comment by stevebauman** [comment]
Strange... Can you try this application on a different PHP version or server to make sure something isn't funky with the LDAP extension?

**Comment by bmw27** [comment]
Unfortunately that didn't work either. I found out that the cookie coming back from the LDAP server is "0", which is why the do/while condition here is evaluating to `false`:

https://github.com/DirectoryTree/LdapRecord/blob/cece84322d1c5199a48a910ad9974692f648ea57/src/Query/Pagination/LazyPaginator.php#L30

"0" is an odd choice for a cookie, but I was able to get some working example code using PHP's built-in LDAP functions. I'm going to close this issue since it not a problem with this package or PHP's LDAP extension, just a weird default set on the LDAP server. I'm going to contact the group that manages this server to see if I can get a better cookie that isn't considered empty in PHP lol.

@stevebauman Thank you for your help! I've learned a decent bit more about LDAP in the last few days lol.

**Comment by stevebauman** [comment]
Thanks for reporting your results @bmw27 -- are you able to modify that line you mentioned to see if changing the condition will actually fetch further results?

For example:

```php
} while ($this->fetchCookie() !== null); 
```

I can certainly modify the condition if so. It's possible this is a bug in LdapRecord if that change does work for you.

**Comment by bmw27** [comment]
That fixes it 😄 I was able to get all the results back by using your example.

**Comment by stevebauman** [comment]
Ah perfect! Thanks @bmw27 -- let me patch this right now and create a release so you can keep working along 👍 

I'll post here once the release has been created.

**Comment by stevebauman** [comment]
Ok [new release is out](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.9.3)! Let me know if it works so I can make sure you're up and running 👍

**Comment by bmw27** [comment]
Still works after the update. Thanks again for your help and for all the work you do on this project. Makes working with LDAP in PHP a breeze 😃.

**Comment by stevebauman** [comment]
Ok excellent! Appreciate the quick follow up 🙏 

And thank you! I'm so glad you find LdapRecord useful! 😄
