### ISSUE TITLE
[Feature] Add suport for Laravel 9

### ISSUE THREAD

**Issue by makurtu** [DirectoryTree/LdapRecord#394]
**Describe the feature you'd like:**

Well, this package requires `"illuminate/contracts": "^5.0|^6.0|^7.0|^8.0"` and Laravel 9 overrides it.

Please, can you add `^9.0` to `illuminate/contracts`?

Thanks!

**Comment by stevebauman** [comment]
Added https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.9.4 👍
