### ISSUE TITLE
[Feature] Bump required psr/simple-cache to 3.0

### ISSUE THREAD

**Issue by devhubpl** [DirectoryTree/LdapRecord#397]
**Describe the feature you'd like:**
Could you bump version of psr/simple-cache to 1.0|2.0|3.0 to be compatible with laravel's package requirement

**Comment by stevebauman** [comment]
Hi there @devhubpl!

If you can figure out how to make `ArrayCacheStore` compatible with all versions, then I will for sure bump the version to 3.0:

https://github.com/DirectoryTree/LdapRecord/blob/master/src/Query/ArrayCacheStore.php

**Comment by hamrak** [comment]
PHP 7.3 is not maintened, PHP 7.4 is under Security fixes only to December 2022.
Why not make it compatible with PHP >= 8.0?

**Comment by stevebauman** [comment]
We can bump the minimum version to 7.4, but bumping it to 8.0 is major breaking change, meaning I will have to tag an LdapRecord 3.0. I’m not yet done making other breaking changes for 3.0 (but am close).

**Comment by stevebauman** [comment]
Completed in [v3](https://github.com/DirectoryTree/LdapRecord/tree/v3.0) branch.
