### ISSUE TITLE
Number of imported LDAP users

### ISSUE THREAD

**Issue by stevebauman** [DirectoryTree/LdapRecord#411]
### Discussed in https://github.com/DirectoryTree/LdapRecord/discussions/410

<div type='discussions-op-text'>

<sup>Originally posted by **Dimawesome** February 25, 2022</sup>
Hello everybody,

I'm trying to import LDAP users, using `php artisan ldap:import users` command. After `directorytree/ldaprecord v2.10.0` update, only 1000 users can be imported, although there are much more of them. As far as I noticed, changes in `src/Query/Pagination/Paginator.php` file led to this result.
So, how could I fix this problem? 

Any help would be appreciated. Thank you. </div>

**Comment by stevebauman** [comment]
Hi @Dimawesome, could you run `composer update` and then try your import again?

I've just released a patch that resolves this issue: https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.10.1

**Comment by Dimawesome** [comment]
@stevebauman, user import now works correctly. Thank you!

**Comment by stevebauman** [comment]
Excellent, thanks for confirming @Dimawesome! 🙏
