### ISSUE TITLE
[Bug] Reading members from large group fails

### ISSUE THREAD

**Issue by klepptor** [DirectoryTree/LdapRecord#425]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.1.4 (Windows, XAMPP)

**Describe the bug:**

Hi!

I'm using ldaprecord to read all members of an AD group to get their mail adresses. This works quite well with groups containing up to 1200 users. But I've a group with ~1700 users, there it does not. If I remove some users from the group (I haven't exactly tested the limits, but 1442 works ;) )

The code is below:

```
use LdapRecord\Container;
use LdapRecord\Connection;
//use LdapRecord\Models\Entry;
use LdapRecord\Models\ActiveDirectory\Group;
use LdapRecord\Models\ActiveDirectory\Entry;
use LdapRecord\Models\ActiveDirectory\User;

echo "<table border=1>\n";
echo "<tr><th>Gruppen CN</th><th>Gruppen DN</th><th>Gruppen Mitglieder</th><th>Anzahl Mitglieder</th></tr>\n";
foreach($ad_gruppen as $schluessel => $innen) {
    foreach($innen as $innerer_schluessel => $groupDN) {
        $groupCN = Entry::find($groupDN);
        $groupName = $groupCN->cn;
        $mitglieder = Entry::find($groupDN);
        $anzahl = 0;
        echo "<tr>\n<td valign=top>" . $innerer_schluessel . "</td>\n";
        echo "<td valign=top>$groupDN</td>\n";      
        echo "<td>";
        foreach ($mitglieder->member as $mitglied) {
        $anzahl++;
        $user = User::find($mitglied);
            foreach ($user->mail as $email) {
                $cn = $user->cn;
                echo "$email<br>";
            }
        }
        echo "</td>";
    }
    echo "<td valign=top>$anzahl</td>";
    echo "</tr>\n";
}
echo "</table>\n";
```

There is no error in the browser nor in the logs, so I think it's a bug...

**Comment by stevebauman** [comment]
Hi @klepptor,

What happens when you dump the group's `member` attribute, does anything appear?

My assumption is that there is likely a limit you're hitting in your LDAP server.

Can you try attempting a [`chunk()`](https://ldaprecord.com/docs/core/v2/searching/#chunking) and see if that works?

> **Important**: You must locate your group via the `Group` model, as it provides the `members()` [relationship required for chunking.](https://github.com/DirectoryTree/LdapRecord/blob/56cf46e9b7714d66d2d4018afcb100684016f783/src/Models/ActiveDirectory/Group.php#L29-L43)

```php
use LdapRecord\Models\Model;
use LdapRecord\Models\ActiveDirectory\Group;

$mitglieder = Group::find($groupDN);

$mitglieder->members()->chunk(function (Model $member) {
    // ...

    echo $member->getFirstAttribute('mail');
});
```

**Comment by AlexMteam** [comment]
> you try attempting an

Hello I attempt the same issue.
Your code fail, method each does not exist.

**Comment by stevebauman** [comment]
@AlexMteam Can you try chunking?

```php
use LdapRecord\Models\Model;
use LdapRecord\Models\ActiveDirectory\Group;

$mitglieder = Group::find($groupDN);

$mitglieder->members()->chunk(500, function (Model $member) {
    // ...

    echo $member->getFirstAttribute('mail');
});
```

**Comment by AlexMteam** [comment]
> @AlexMteam Can you try chunking?
> 
> ```
> use LdapRecord\Models\Model;
> use LdapRecord\Models\ActiveDirectory\Group;
> 
> $mitglieder = Group::find($groupDN);
> 
> $mitglieder->members()->chunk(500, function (Model $member) {
>     // ...
> 
>     echo $member->getFirstAttribute('mail');
> });
> ```

Hello thnx for answer.
Checked now, and did not work, receive error [**Array to string conversion**]

**Comment by stevebauman** [comment]
That's great to hear @klepptor! Appreciate the follow up. I'll close this out.
