### ISSUE TITLE
[Support]

### ISSUE THREAD

**Issue by masmos** [DirectoryTree/LdapRecord#435]
Hi Team,
I've installed LDAP Record in Laravel 9 and its working fine, The help i need is how to modify this model **'model' => LdapRecord\Models\ActiveDirectory\User** so i can include other parameters like phone Number and UserName while importing user from LDAP Server.

**Environment:**
 - LDAP Server Type: [ActiveDirectory]
 - PHP Version: [8.1]
 - Laravel 9

**Comment by stevebauman** [comment]
Hi @masmos,

You’re looking for “sync attributes” — here is the documentation link:

https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#sync-attributes

**Comment by masmos** [comment]
> Hi @masmos,
> 
> You’re looking for “sync attributes” — here is the documentation link:
> 
> https://ldaprecord.com/docs/laravel/v2/auth/database/configuration/#sync-attributes

It worked like charm, You are the best

**Comment by stevebauman** [comment]
Happy to help @masmos! 😄
