### ISSUE TITLE
Error adding user in AD

### ISSUE THREAD

**Issue by issamjrfadel** [DirectoryTree/LdapRecord#440]
Hello,

I am getting an error when trying to add a user into AD server. It seems that I am able to connect to the server as I am able to run a basic query and view the results. However I am having trouble with trying to add a new user.

 #diagnosticMessage: 
 0000202B: RefErr: DSID-031007F9, data 0, 1 access points

#message: 
"ldap_add(): Add: Referral"

Any support is appreciated.

Thank you.

**Comment by stevebauman** [comment]
Hi @issamjrfadel,

I'm going to need to see your code creating the user to be able to assist you 👍

**Comment by issamjrfadel** [comment]
Thanks for the reply. Here is the code

`$conn = new Connection([
        'hosts' => ['ldaps.url'],
        'username' => 'username',
        'password' => 'password',
        'port' => 389,
        'base_dn' => 'OU=Testing,DC=Test',
        'use_ssl' => false,
        'use_tls' => true,
        'follow_referrals' => false
        ]);

try {
            $conn->connect();

            $user = (new LDAPUser)->inside('OU=Testing,DC=Test');
            
            $user->cn = 'Test Account';
            $user->sAMAccountName="test";
            $user->userPrincipalName = 'test';
           
            $user->save();
           
        } catch (\LdapRecord\Exceptions\InsufficientAccessException $ex) {
            // The currently bound LDAP user does not
            // have permission to change passwords.
            dd("Insufficient Access", $ex);
        } catch (\LdapRecord\Exceptions\ConstraintException $ex) {
            // The users new password does not abide
            // by the domains password policy.
            dd("constraint Error", $ex);
        } catch (\LdapRecord\LdapRecordException $ex) {
            // Failed changing password. Get the last LDAP
            // error to determine the cause of failure.
            $error = $ex->getDetailedError();
            echo $error->getErrorCode();
            echo $error->getErrorMessage();
            echo $error->getDiagnosticMessage();
        }`

**Comment by stevebauman** [comment]
Are you sure your `base_dn` is correct? To my knowledge, there must be at least two domain components (`DC=Test,DC=com`).

**Comment by issamjrfadel** [comment]
Yes there is two, sorry I left that out. It would be in this format `OU=Testing,DC=Test,DC=com`

**Comment by stevebauman** [comment]
Ok. Have you also added the connection to the container after connecting? For example:

```php
use LdapRecord\Container;

$conn = new Connection([
    // ...
]);

Container::addConnection($conn);

try {
    $conn->connect();

    // ...
}
```

**Comment by issamjrfadel** [comment]
Thanks Steve! This worked.

**Comment by stevebauman** [comment]
Excellent! Glad you’re up and running @issamjrfadel. 🎉
