### ISSUE TITLE
Can't contact LDAP server error intermittently 

### ISSUE THREAD

**Issue by icsy7867** [DirectoryTree/LdapRecord#441]
Brand new user here.  I am unfortunately not versed in Laravel and I have imported manually.  Everything seems to work fine about 2/3 of the time (Testing via page refreshes).  Currenlty using the php-apache docker container.

My setup is very simple at the moment and using the latest verion.  Just pulled via composer earlier today.

```
require '/var/www/html/vendor/autoload.php';
use LdapRecord\Connection;

$connection = new Connection([
    // Mandatory Configuration Options
    'hosts'            => ['ad.company.com'],
    'base_dn'          => 'DC=org,DC=company,DC=com',
    'username'         => 'CN=LDAP,OU=Service,OU=Protected Accounts,DC=org,DC=company,DC=com',
    'password'         => 'MySecretPassword',

    // Optional Configuration Options
    'port'             => 3269,
    'use_ssl'          => true,
    'use_tls'          => false,
    'version'          => 3,
    'timeout'          => 8,
    'follow_referrals' => false,
]);

try {
    $connection->connect();
    echo "Successfully connected!";
} catch (\LdapRecord\Auth\BindException $e) {
    $error = $e->getDetailedError();

    echo $error->getErrorCode();
    echo $error->getErrorMessage();
    echo $error->getDiagnosticMessage();
}
```

On most page loads I see what one would expect:
`Successfully connected!`

However about 1/3 of the time I get:
`-1Can't contact LDAP server(unknown error code)`

I have tried increasing the timeout a bit.  But im not sure what would be causing the code to fail to conect the ldap servers.  I also tried different servers, and different servers in different forests within the org.  All with the same results.  Just curious if anyone had any suggestions/guidance

**Comment by icsy7867** [comment]
I'm an idiot.  My php container I was using had a very old tag.  It was running debian 9... Yikes...

Rebuilt the container on debian 11 and everything is working like a charm.

**Comment by stevebauman** [comment]
Excellent, glad to hear you have resolved it @icsy7867!
