### ISSUE TITLE
[Feature] Make `determineModelFromRelated` more flexible

### ISSUE THREAD

**Issue by yakatz** [DirectoryTree/LdapRecord#442]
The current implementation of `determineModelFromRelated` requires every possible `objectClass` to match the model in order for it to be converted from `Entry`. This becomes an issue when, for example, not every `User` has the same classes. In our case, this is because a user might have a class that shows they are linked to another organization (and the class adds additional required attributes).

objectClasses in `LdapRecord\Models\FreeIPA\User`:
```php
public static $objectClasses = [
    'top',
    'person',
    'inetorgperson',
    'organizationalperson',
];
```

objectClasses actually returned from a user (capitalization added back to make it easier to read):
```
array:17 [▼
  0 => "personInCompanyB"
  2 => "hasWindowsAccount"
  3 => "inetorgperson"
  4 => "inetuser"
  5 => "ipaobject"
  6 => "ipasshgroupofpubkeys"
  7 => "ipasshuser"
  8 => "ipauserauthtypeclass"
  9 => "krbprincipalaux"
  10 => "krbticketpolicyaux"
  11 => "mailrecipient"
  12 => "organizationalperson"
  13 => "person"
  14 => "posixaccount"
  15 => "systemquotas"
  16 => "top"
]
```

Not every user would have `personInCompanyB` or `hasWindowsAccount`, so I can't add them to the Model, but otherwise it seems I need to convert them manually.

Possible solution - steps:
1. [Sort the list of `$related` models](https://github.com/DirectoryTree/LdapRecord/blob/6241c03cfa90757e423e715eeea90582d2930c6b/src/Models/Relations/Relation.php#L315-L317)  by size of `objectClass` list - this would make the most specific matches be checked first.
2. Check if [each of the `$related` models](https://github.com/DirectoryTree/LdapRecord/blob/6241c03cfa90757e423e715eeea90582d2930c6b/src/Models/Relations/Relation.php#L344-L353) is a subset of the objectClasses returned in the `Entry`.

Thoughts? Any other options for how to do this? Chance of a PR being accepted?

**Comment by yakatz** [comment]
I ended up just trying something out - it seems to work fine with every test I could come up with

**Comment by stevebauman** [comment]
Can be done now via `Relation::resolveModelsUsing(fn () => ...)`.
