### ISSUE TITLE
[Bug] Recursive Groups don't return members if they have the group set as their primary group in Active Directory

### ISSUE THREAD

**Issue by jzapater** [DirectoryTree/LdapRecord#447]
At least in the latest release v2.13 I have one problem with this method:

$user->groups()->recursive()->get();

The method not get recursive the groups of user's Primary Group.

Can you check it ?

Thanks.

**Comment by stevebauman** [comment]
Hi @jzapater,

Does the user account you are binding to your LDAP server with have access to read from the primary group?

**Comment by jzapater** [comment]
The problem is not the bind user because I change the primary group of the user and the groups returned are different.

**Comment by stevebauman** [comment]
Ok, but does the user you are binding to your LDAP server with have access to the groups that should be returned in the result (i.e. the ones missing)?

Also, please fill out the initial bug report data. I need more information to be able to do anything with this other than "doesn't work".

**Comment by jzapater** [comment]
If change the primary group of user the result is different.

There are groups that come out in one query and different ones in another.

**Comment by stevebauman** [comment]
I'm not sure what to tell you with this limited set of information.

This seems very environment specific. I have no idea what LDAP server your running, version of LdapRecord, or PHP version.

Please fill out the information that is requested when you create a bug report, and also share some more information about your environment, and if possible -- produce a failing test case illustrating the problem.

**Comment by jzapater** [comment]
Detailed example of the bug:

LdapRecord v2.13
AD with samba 4.15.7

PHP Example:
$user = User::find('CN=user ....');
$groups = $user->groups()->recursive()->get();
foreach ($groups as $group) {
    echo $group->getName() . "\n";
}

Create four groups:
- group 1
- group 2
- group 3
- group 4
In group 1->memberof -> group3
In group 2->memberof -> group4
Create user:
In user->member of group1 and group2

1º Assign group1 to primary group of user: 
Result (missing group 4):
group 1
group 2
group 3

2º Assign group2 to primary group of user: 
Result (missing group 3):
group 1
group 2
group 4

Problem: not recursive the assigned primary group.
