### ISSUE TITLE
UAC option not found

### ISSUE THREAD

**Issue by danilodecanini** [DirectoryTree/LdapRecord#45]
- LdapRecord Version: latest
- LDAP Server Type: Active Directory
- PHP Version: 7.3

### Description:
How can I set the User Account Option "The user must change the password at next logon", because usually when we reset the password the need to check this option to user change his password for whatever he wants. Is it possible? I search in the documentation but I didn't find anything.

**Comment by stevebauman** [comment]
Hi @danilodecanini,

Here's the documentation: https://ldaprecord.com/docs/tutorials/user-management/#user-account-control

If you search "User Account Control" it shows up in the search bar.

Hope this helps!

**Comment by danilodecanini** [comment]
Hi @stevebauman ,

I did what I wanted, thank you!

**Comment by stevebauman** [comment]
Great! Any other questions feel free to ask :smile:
