### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by useronkel** [DirectoryTree/LdapRecord#455]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 7.4.19

**Describe the bug:**
Latest commit includes calls to str_contains() which is a pure PHP8 function and I didn't find any if(!function_exists() :-)

**Comment by stevebauman** [comment]
Hi @useronkel!

Thanks for keeping an eye on this — though I’ve added Symfony’s PHP 8.0 polyfill to ensure this method is available:

https://github.com/DirectoryTree/LdapRecord/blob/14fb1773c99536096e86f946c7a2c21b3123b5e9/composer.json#L40

**Comment by useronkel** [comment]
Ty.
I'am using the src-Directory, not composer. My bad :-(
