### ISSUE TITLE
[Bug] ldap_search(): Passing null to parameter #8 ($deref) of type int is deprecated

### ISSUE THREAD

**Issue by pepperfm** [DirectoryTree/LdapRecord#464]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.1.6

**Describe the bug:**
In the `directorytree/ldaprecord/src/Ldap.php` file the search() method set `null` for 7th parameter `$deref` as default value.
`public function search($dn, $filter, array $fields, $onlyAttributes = false, $size = 0, $time = 0, $deref = null, $serverControls = [])`
But php method `ldap_search()` expects only int:
```
/*
 * ...
 * @param int $deref <p>
 * Specifies how aliases should be handled during the search. It can be
 * one of the following:
 * <b>LDAP_DEREF_NEVER</b> - (default) aliases are never
 * dereferenced.</p>
 * ...
 */
#[PhpVersionAware(['8.1' => 'LDAP\Result|array|false'], default: 'resource|false')]
function ldap_search(
    #[PhpVersionAware(['8.1' => 'LDAP\Connection'], default: 'resource')] $ldap,
    array|string $base,
    array|string $filter,
    array $attributes = [],
    int $attributes_only = 0,
    int $sizelimit = -1,
    int $timelimit = -1,
    int $deref = 0,
    #[Available(from: '7.3')] #[PhpVersionAware(["8.0" => "null|array"], default: "array")] $controls = null
) {}
```
So i gets the error `"ldap_search(): Passing null to parameter #8 ($deref) of type int is deprecated"`
I guess your method should set 0 for `$deffer` param as default:
`public function search($dn, $filter, array $fields, $onlyAttributes = false, $size = 0, $time = 0, $deref = 0, $serverControls = [])`
Just suggestions. Coz its work for me, when i set 0 as default:
```
PASS  Tests\Unit\LdapServiceTest

  ✓ 001 users

  Tests:  1 passed
  Time:   4.31s
```

**Comment by stevebauman** [comment]
Thanks for the report @pepperfm, I'll have a patch out today for this 👍

**Comment by stevebauman** [comment]
Oh excellent, thanks for looking into that for me 🙏
