### ISSUE TITLE
require ext-ldap it is missing from your system.

### ISSUE THREAD

**Issue by adchir12** [DirectoryTree/LdapRecord#465]
I am getting the following error even after installing ldap.
PHP 7.3.33

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - directorytree/ldaprecord-laravel[v2.5.0, ..., v2.5.6] require ext-ldap * -> it is missing from your system. Install or enable PHP's ldap extension.
    - Root composer.json requires directorytree/ldaprecord-laravel ^2.5 -> satisfiable by directorytree/ldaprecord-laravel[v2.5.0, ..., v2.5.6].
`

**Comment by stevebauman** [comment]
Hi @adchir12, this is a composer installation error.

Make sure that `composer` is targeting the same PHP version and installation that your local web server is targeting. 👍
