### ISSUE TITLE
error to publish in lumen

### ISSUE THREAD

**Issue by marianoka** [DirectoryTree/LdapRecord#469]
Hi!
I have installed ldaprecord in lumen. Had no problems with install but I cannot publish vendor to create ldap.php file
I get this error :
In Application.php line 223:

  Class "LdapRecord\Lumen\LdapServiceProvider" not found
after running this command:
php artisan vendor:publish --provider="LdapRecord\Laravel\LdapServiceProvider"
Also, I haved edited bootstrap/app.php to register the classes.
$app->register(\LdapRecord\Lumen\LdapServiceProvider::class);
$app->register(\LdapRecord\Lumen\LdapAuthServiceProvider::class);

Any idea what should I do to get it working
Thx
Mariano

**Comment by stevebauman** [comment]
Hi @marianoka,

Have you read the installation docs?

https://ldaprecord.com/docs/laravel/v2/lumen

Make sure you have installed LdapRecord Lumen, register the service provider, then run `php artisan make:ldap-config`.

That will get you up and running 👍

**Comment by marianoka** [comment]
Thanks!!! that works!!

**Comment by marianoka** [comment]
I could install ldaprecord, but whe trying to get users from my openldap I get this mesagge
Undefined constant "LdapRecord\Models\Attributes\LDAP_ESCAPE_FILTER"
