### ISSUE TITLE
LDAP_ESCAPE_FILTER

### ISSUE THREAD

**Issue by marianoka** [DirectoryTree/LdapRecord#470]
I could install ldaprecord, but whe trying to get users from my openldap I get this mesagge
Undefined constant "LdapRecord\Models\Attributes\LDAP_ESCAPE_FILTER"
LDAP Server: OpenLDAP
WS: nginx
PHP: 8.1
Lumen: 8.1.2

**Comment by stevebauman** [comment]
Hi @marianoka,

This means that your web server is not using the same PHP installation that your Composer installation is using.

Make sure that your web server is using a PHP installation with the LDAP extension enabled, and that will resolve your issue.
