### ISSUE TITLE
[Bug] Use the users account to change its own ldap password 

### ISSUE THREAD

**Issue by kantmn** [DirectoryTree/LdapRecord#479]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - LdapRecord-Laravel Major Version: 2.5
 - PHP Version: 8.0

**Describe the bug:**

Hi there,

i am trying to change my users password via ldaprecord/laravel on the ldap server.

this was tested with an admin user account as ldap binding, but i would prefer to use a non admin account for security reasons.

That is why i was looking for a way to use the users own account to change its password itself, so bind the user account to ldap while password change or even better in bind in general to the user after login.

I have searched your docs for this, but i could not find a way to do this. I have also tried to switched the connection parameters, exchange the username/password from admin to logged in user but it seems not apply these settings to the connection.

The result is always "ldap_modify_batch(): Batch Modify: Insufficient access" which should not be the case as we use a user who has the permissions, tested via console ldappasswd and also used the user itself as configured user instead of the admin which works also when changing the password.

so what is not working as expect:
User logs in -> binds via a service account (not admin, would prefer to login as user and bind the user) -> user->ldap->password update fails with given message

Best regards and many thanks

**Comment by stevebauman** [comment]
I've just created a [test case](https://github.com/DirectoryTree/LdapRecord/commit/297a98ab2ad6c9b14786592add8657348a304718) against a [real OpenLDAP server](https://github.com/DirectoryTree/LdapRecord/runs/7024272938?check_suite_focus=true).

Closing, as the above should work for you. Let me know if you encounter further issues and I can reopen.

**Comment by kantmn** [comment]
okay sounds good, i did not know about this construct
`\LdapRecord\Models\OpenLDAP\User::resolveConnection()->auth()->bind($user->getDn(), $validated['oldpassword']);`

so this line is kicking the previous connection, and creating a new conenct with as user credentials, is this correct? is this connection limited to the user object or in general for all further queries from here on?

also i had to change this
`$user->password = [$validated['oldpassword'], $validated['newpassword']];`
into this 
`$user->password = $validated['newpassword'];`
otherwise it was screaming about "unable to extract salt", where $validated['...'] is my validate form data

after this change it works, the user is able to change its own password, so no feature just unknown functions for me :)

great job, thank you

**Comment by stevebauman** [comment]
> so this line is kicking the previous connection, and creating a new conenct with as user credentials, is this correct? is this connection limited to the user object or in general for all further queries from here on?

Yes that's correct, any further LDAP operations executed after that statement will be run underneath that user.

If you want to revert *back* to the user you have configured inside your `.env`, you can run:

```php
$connection->auth()->bindAsConfiguredUser();
```

> otherwise it was screaming about "unable to extract salt", where $validated['...'] is my validate form data

This means that the `$user` does not contain the `userPassword` attribute. I've experienced this inside the OpenLDAP integration tests. This will occur if the user does not have a password, or that you have recently created the user with a password.

You can check to see if this attribute is in-fact missing by dumping the users attributes via a `dd()`:

```php
dd($user->getAttributes());
```

If it is missing, try using `$user->refresh()` to re-load the users attributes to see if the `userPassword` attribute is populated.

I'm glad you're up and running -- always happy to help!

**Comment by kantmn** [comment]
> This means that the $user does not contain the userPassword attribute. I've experienced this inside the OpenLDAP integration tests. This will occur if the user does not have a password, or that you have recently created the user with a password during the same request.
i guess this is because of laravel, inside the user model password is defined as hidden attribute, so it will not be displayed when retrieving the object. the user model between laravel and ldap is in fact synced 

but reviewing the code i am not sure if i have missed to add the password inside the sync attributes handler or have removed it as this is done anyway and caused an issue... 

This is a lovely option :-) 
`$connection->auth()->bindAsConfiguredUser();`
i guess this requires pre definition for $connection as $connection = Container::getDefaultConnection(); ?
