### ISSUE TITLE
Connection doesn't exist error after successful test

### ISSUE THREAD

**Issue by kirkaracha** [DirectoryTree/LdapRecord#487]
When I run `php artisan:test` the default connection is successful, but when I run `php artisan` I get an error saying the connection doesn't exist. 

![image](https://user-images.githubusercontent.com/3633070/178843746-bdba9e18-6ca7-404c-99ca-e804b0a6c484.png)

Laravel 9.19
PHP 8.1
directorytree/ldaprecord-laravel 2.5.6

I uninstalled and reinstalled LdapRecord with the same result.

**Comment by kirkaracha** [comment]
config/ldap.php settings:

`'default' => env('LDAP_CONNECTION', 'default'),`

````
    'connections' => [
        'default' => [
            'hosts' => [env('LDAP_HOST', '127.0.0.1')],
            'username' => env('LDAP_USERNAME', 'cn=user,dc=local,dc=com'),
            'password' => env('LDAP_PASSWORD', 'secret'),
            'port' => env('LDAP_PORT', 389),
            'base_dn' => env('LDAP_BASE_DN', 'dc=local,dc=com'),
            'timeout' => env('LDAP_TIMEOUT', 5),
            'use_ssl' => env('LDAP_SSL', false),
            'use_tls' => env('LDAP_TLS', false),
        ],
    ],
````

.env settings (username and password copied from working environment)
![image](https://user-images.githubusercontent.com/3633070/178844811-22caf9c1-ed54-455e-90f7-c6b75aaf9a9f.png)

**Comment by stevebauman** [comment]
Hi @kirkaracha,

It looks like you've configured your connections through both the `.env` and configuration based options:

https://ldaprecord.com/docs/laravel/v2/configuration

![Screenshot 2022-07-14 at 11 43 36 AM](https://user-images.githubusercontent.com/6421846/179022704-f9200b04-cddf-4b2b-872f-d4c31e9e9853.png)

You must use one, or the other. You cannot combine both.

Either delete the `config/ldap.php` file, or remove the connection being defined dynamically through your `.env`, and use the `.env` params defined in the `config/ldap.php` file.
