### ISSUE TITLE
[Bug] password not encoded if using custom model

### ISSUE THREAD

**Issue by vatsake** [DirectoryTree/LdapRecord#504]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version:8.0

**Describe the bug:**

For some reason $user->unicodepwd is not automatically encoded IF I'm using custom model.

```
use LdapRecord\Models\Model;

class User extends Model
{
    /**
     * The object classes of the LDAP model.
     *
     * @var array
     */
    public static $objectClasses = [
        'top',
        'person',
        'organizationalperson',
        'user',
    ];

    protected $casts = [
        'accountexpires' => 'datetime:windows-int',
    ];
}
```

```
 $user = (new User());
$user->unicodepwd = $request->input('password');
dd($user->getModifications());
```

```
array:3 [
    "attrib" => "unicodepwd"
    "modtype" => 1
    "values" => array:1 [
      0 => "testpassword"
    ]
```

**Comment by stevebauman** [comment]
Hi @vatsake,

If you create your own custom `User` Active Directory model, you should either extend the built-in `ActiveDirectory\User` model, or implement the interface and traits that currently exist on that model, namely the `HasPassword` trait:

https://github.com/DirectoryTree/LdapRecord/blob/8ad10c26a992b46a265ff84b2d1845003c910a6e/src/Models/ActiveDirectory/User.php#L14-L32

```php
use LdapRecord\Models\Model;
use LdapRecord\Models\Concerns\HasPassword;
use LdapRecord\Models\Types\ActiveDirectory;

class User extends Model implements ActiveDirectory
{
    use HasPassword;

    protected $passwordHashMethod = 'encode';

    protected $passwordAttribute = 'unicodepwd';

    // ...
}
```

I'd recommend extending the default `User` model if you can, as it provides a lot of scaffolding out-of-the-box:

```php
use LdapRecord\Models\ActiveDirectory\User as BaseModel;

class User extends BaseModel
{
    // ...
}
```

This will resolve your password encoding issue 👍

**Comment by stevebauman** [comment]
Hi @vatsake,

I don't believe you can set a password during creation of an ActiveDirectory account -- it must be set after the account exists. Can you confirm if setting the password using your own model actually creates the user with the password you've provided?

Also, can you try re-extending the base `User` model and attempt setting the password after creation?

I.e.

```php
$user = new User();

// ...

$user->save();

$user->update([
    'unicodepwd' => $request->input('password'),
    'userAccountControl' => 512,
    'pwdlastset' => 0,
]); 
```

**Comment by stevebauman** [comment]
Thanks for confirming that @vatsake,

I think this is a bug. Here in LdapRecord we're making the assumption that an existing password will be overwritten via a batch `REPLACE` modification:

https://github.com/DirectoryTree/LdapRecord/blob/8ad10c26a992b46a265ff84b2d1845003c910a6e/src/Models/Concerns/HasPassword.php#L136-L153

We can update this to check if the user exists to properly set the batch `ADD` modification:

```php
$batch = $this->exists
    ? LDAP_MODIFY_BATCH_REPLACE
    : LDAP_MODIFY_BATCH_ADD;

$this->addModification(
    $this->newBatchModification(
        $attribute,
        $batch,
        [$password]
    )
);
```

Going to patch this, thanks for the report 🙏

**Comment by stevebauman** [comment]
Can you confirm you're on the new version (v2.17.2)? You can find out by searching your `composer.lock` file for `directorytree/ldaprecord`

**Comment by stevebauman** [comment]
Hmm that's strange -- as that would be the same batch modification generated on the root `Model` without extending the `User` model. I've just added a test case to ensure this is the case: https://github.com/DirectoryTree/LdapRecord/commit/3e5af5583a4d7f68f54d90d97183fd32ae1bc7c7

Can you revert to using your own custom model (without extending `ActiveDirectory\User`) and then dump the batch modifications prior to `$user->save()` and post them here?

Ex:

```php
$user = new User();

$user->unicodepwd = $request->input('password');
$user->pwdlastset = -1;

var_dump($this->getModifications());

// $user->save();
```

**Comment by stevebauman** [comment]
@vatsake Can you post how you're encoding the password manually? The password is properly encoded on my end using the code below:

```php
use LdapRecord\Models\ActiveDirectory\User;

$user = new User;

$user->password = 'foobar';

dd($user->getModifications());

// array:1 [
//   0 => array:3 [
//     "attrib" => "unicodepwd"
//     "modtype" => 1
//     "values" => array:1 [
//       0 => ""\x00f\x00o\x00o\x00b\x00a\x00r\x00"\x00"
//     ]
//   ]
// ]
```

**Comment by stevebauman** [comment]
> The password is correctly encoded with both custom and ActiveDirectory\User classes.

Thanks for confirming that @vatsake 🙏 

> `// This fails because the password is not set?`

Can you explain this line? The password won't be sent in the subsequent `update()` call because the model was previously saved above it, clearing any modifications to the user.

> However if I set password like this:

Thanks for confirming that this approach works 🙏
