### ISSUE TITLE
Connect with a domain controller

### ISSUE THREAD

**Issue by testlorenzospa** [DirectoryTree/LdapRecord#528]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.1

Hello.

For connect to a LDAP server I should use a domain controller.
Can I connect to a LDAP server with a domain controller?

Thanks.

**Comment by stevebauman** [comment]
Hi @testlorenzospa,

Yes -- your domain controller is an LDAP server.

```php
use LdapRecord\Connection;

$connection = new Connection([
     'hosts'    => ['dc1.local.com'],
     'username' => 'cn=user,dc=local,dc=com',
     'password' => 'secret',
]);

$connection->connect();
```

https://ldaprecord.com/docs/core/v2/connections#introduction

**Comment by testlorenzospa** [comment]
Hi @stevebauman 

Thanks for your reply.
I have found the issue (my only problem).

Thanks again.
