### ISSUE TITLE
[Bug][Deprecated]Warning

### ISSUE THREAD

**Issue by SK-DE** [DirectoryTree/LdapRecord#530]
**Environment:**
 - PHP Version: 8.1.12

**Describe the bug:**
With PHP 8.1 i get the following deprecated warning, if the login in laravel fails:
str_contains(): Passing null to parameter #1($haystack) of type string is deprecated in .../directorytree/ldaprecord/src/DetectsErrors.php on line 66

**Comment by stevebauman** [comment]
Thanks for the report @SK-DE! I'll have this patched shortly 👍

**Comment by stevebauman** [comment]
Fixed in [v2.19.1](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.19.1). Let me know if you encounter any further issues 🙏
