### ISSUE TITLE
[Support] Displaying LDAP Error Messages not work

### ISSUE THREAD

**Issue by Virtute90** [DirectoryTree/LdapRecord#536]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 8.1

First of all thank you for your work, it's making my life easier 😄 

I was able to correctly configure with laravel/ui my application that logs into my LDAP server.

Now I would like to customize the error messages: following the guide

https://ldaprecord.com/docs/laravel/v2/auth/plain/laravel-ui/#displaying-ldap-error-messages

i can't get the messages to appear.

I noticed that the folder it reports for the errors.php file is

> /resources
>      /lang
>          /vendor
>              /ldap
>                  /en
>                      errors.php

but in laravel 9 the "lang" folder is in root and not in resources anymore.

If I log in incorrectly, the error it returns is `auth.failed`

How can I fix?

Thank you!

**Comment by stevebauman** [comment]
Hi @Virtute90,

Thanks for letting me know about the lang folder changes! I've just updated the documentation.

> If I log in incorrectly, the error it returns is auth.failed

This is intended. You can see this taking place here:

https://github.com/DirectoryTree/LdapRecord-Laravel/blob/f567f77a91c860a9098b7afcea9688cea3bb1215/src/Auth/ListensForLdapBindFailure.php#L86-L90

If you want to adjust the authentication failure message, you must change it in the standard Laravel location as shown (`auth.failed`). This is to keep consistency with the default Laravel auth scaffolding.

Other LDAP errors will fall into the `default` switch case, which is where the translation file will come into play:

https://github.com/DirectoryTree/LdapRecord-Laravel/blob/f567f77a91c860a9098b7afcea9688cea3bb1215/src/Auth/ListensForLdapBindFailure.php#L92-L96

You can also adjust this translation mapping inside of the same trait by overriding the `ldapDiagnosticCodeErrorMap()` method:

https://github.com/DirectoryTree/LdapRecord-Laravel/blob/f567f77a91c860a9098b7afcea9688cea3bb1215/src/Auth/ListensForLdapBindFailure.php#L162-L174

Let me know if you have any further questions! 👍
