### ISSUE TITLE
[Bug] Syntax error in Relation.php

### ISSUE THREAD

**Issue by Jaradard** [DirectoryTree/LdapRecord#537]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - LdapRecord-Laravel Major Version: v2.6
 - PHP Version: 7.3

Hi,

A php error appear when reading directorytree/ldaprecord/src/Models/Relations/Relation.php file

`ERROR: syntax error, unexpected '=' syntax error, unexpected '=' at vendor/directorytree/ldaprecord/src/Models/Relations/Relation.php:91)`

Maybe remove the two '??'

**Comment by stevebauman** [comment]
Ah thanks @Jaradard! The null coalescing assignment operator was added in PHP 7.4, but I see you're using PHP 7.3 (LdapRecord must support this with it's current version).

I'll have a patch out today 🙏

**Comment by Jaradard** [comment]
You're welcome 😉
Thanks for the quick fix.
