### ISSUE TITLE
[Question] createTimestamp and modifyTimestamp not being fetched

### ISSUE THREAD

**Issue by ajibarra** [DirectoryTree/LdapRecord#540]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 8.1

**Describe the bug:**

When a user or group is fetched I have no way to get the createTimestamp or modifyTimestamp. Not sure if I am missing something but it looks it should be fetched. 

If I navigate to the server with PHPLdapAdmin, I do see them under internal attributes.

**Comment by stevebauman** [comment]
Hi @ajibarra,

Can you post your code example? Also, have you tried dumping the model to see if the timestamps are visible?

```php
use LdapRecord\Models\OpenLDAP\User;

dd(User::first());
```

LdapRecord fetches all attributes by default:

https://github.com/DirectoryTree/LdapRecord/blob/3557d500b24b331852e4c9ebea1e712b7629cb09/src/Query/Builder.php#L238

If the attributes are virtual, you may have to request them:

```php
use LdapRecord\Models\OpenLDAP\User;

$user = User::get(['*', 'createTimestamp', 'modifyTimestamp'])->get();
```

Can you give the above a shot as well and let me know the result?

**Comment by ajibarra** [comment]
```$user = User::get(['*', 'createTimestamp', 'modifyTimestamp'])->get();```

Adding the additional attributes to get (or select in my case) made the magic. 

Thank you for the quick response! 

Amazing plugin!

**Comment by stevebauman** [comment]
Awesome! Happy to help @ajibarra.

Thanks for your kind words, I’m so glad you enjoy LdapRecord ❤️ 😄.
