### ISSUE TITLE
test with docker

### ISSUE THREAD

**Issue by vahidalvandi** [DirectoryTree/LdapRecord#549]
i want to test this package with docker . please 

First, explain how I can create an openldap account in it and how I can log in to Laravel with it.

[](https://github.com/DirectoryTree/LdapRecord/blob/master/docker-compose.yml)

**Comment by stevebauman** [comment]
Hi @vahidalvandi,

You can take a look at the project's `docker-compose.yml` file for a OpenLDAP docker instance:

https://github.com/DirectoryTree/LdapRecord/blob/221e5d78372c434313feae1ce2d209aec9e62a94/docker-compose.yml#L14-L15

As well as how it's used inside of the integration test cases:

https://github.com/DirectoryTree/LdapRecord/blob/221e5d78372c434313feae1ce2d209aec9e62a94/tests/Integration/TestCase.php#L10-L19

And here's documentation for Laravel:

https://ldaprecord.com/docs/laravel/v2/auth
