### ISSUE TITLE
Unable to create a new user

### ISSUE THREAD

**Issue by danilodecanini** [DirectoryTree/LdapRecord#55]
- LDAP Server Type: Active Directory
- PHP Version: 7.3

### Description:
When I'm trying to create a new user, I got a fatal error:

`Fatal error: Uncaught ErrorException: ldap_add(): Add: No such attribute in C:\inetpub\wwwroot\portal\vendor\directorytree\ldaprecord\src\Ldap.php:842 Stack trace: #0 [internal function]: LdapRecord\Ldap->LdapRecord\{closure}(2, 'ldap_add(): Add...', 'C:\\inetpub\\wwwr...', 842, Array) #1 C:\inetpub\wwwroot\portal\vendor\directorytree\ldaprecord\src\Ldap.php(842): ldap_add(Resource id #6, 'cn=TESTE,OU=Por...', Array) #2 C:\inetpub\wwwroot\portal\vendor\directorytree\ldaprecord\src\Ldap.php(538): LdapRecord\Ldap->executeFailableOperation('ldap_add', Resource id #6, 'cn=TESTE,OU=Por...', Array) #3 C:\inetpub\wwwroot\portal\vendor\directorytree\ldaprecord\src\Query\Builder.php(1503): LdapRecord\Ldap->add('cn=TESTE,OU=Por...', Array) #4 C:\inetpub\wwwroot\portal\vendor\directorytree\ldaprecord\src\Connection.php(230): LdapRecord\Query\Builder->LdapRecord\Query\{closure}(Object(LdapRecord\Ldap)) #5 C:\inetpub\wwwroot\portal\vendor\directorytree\ldaprecord\ in C:\inetpub\wwwroot\portal\vendor\directorytree\ldaprecord\src\Connection.php on line 232`

### Steps To Reproduce:

This is my code:

```
$user = new User([
					'cn' => $arr_dados["name"],
					'givenname' => $arr_dados["name"],
					'unicodepwd' => $arr_dados["pwd"],
					'samccountname' => $arr_dados["login"],
					'userprincipalname' => $arr_dados["login"]."@mycompany.local",
					'mail' => $arr_dados["mail"],
					'dn' => 'CN='.$arr_dados['nome'].',OU=Portal,OU=Contacts, ,DC=mycompany,DC=local'
				]);


$user->save();
```

I've insert all the attributes there is "required" to create a new user, but it doesn't work.

**Comment by stevebauman** [comment]
Hi @danilodecanini!

`dn` is actually not an attribute you can set. You must set it via the `setDn` method:

```php
$user = new User([
    'cn' => $arr_dados["name"],
    'givenname' => $arr_dados["name"],
    'unicodepwd' => $arr_dados["pwd"],
    'samccountname' => $arr_dados["login"],
    'userprincipalname' => $arr_dados["login"]."@mycompany.local",
    'mail' => $arr_dados["mail"],
]);

$user->setDn('CN='.$arr_dados['nome'].',OU=Portal,OU=Contacts, ,DC=mycompany,DC=local');

$user->save();
```

Can you give that a shot and let me know?

**Comment by stevebauman** [comment]
This isn't actually clear in the documentation ☹️ . This is my mistake. Let me add this in and make it easy to understand.

**Comment by danilodecanini** [comment]
@stevebauman, 

I tried without the `'dn'`, and I got the same error, even though I insert the 'OU' before `save()` like this: 

```
$ou = OrganizationalUnit::findOrFail('OU=Portal,OU=Contacts,DC=romagnole,DC=local');

$user = new User([
    'cn' => $arr_dados["name"],
    'givenname' => $arr_dados["name"],
    'unicodepwd' => $arr_dados["pwd"],
    'samccountname' => $arr_dados["login"],
    'userprincipalname' => $arr_dados["login"]."@mycompany.local",
    'mail' => $arr_dados["mail"],
]);

$user->inside($ou)->save();
```

It doesn't work yet.

P.S: I tried to do exactly how you said but the same error. :(

**Comment by stevebauman** [comment]
`samccountname` must be `samaccountname` - A small typo there. Give it another go!

**Comment by danilodecanini** [comment]
@stevebauman,

I'm sorry man, it worked. It was my misspelling with the `samaccountname`. Thank you!

**Comment by stevebauman** [comment]
No problem at all! I’m glad you were able to resolve it 😄 

Anything else you encounter feel free to create an issue.
