### ISSUE TITLE
[Support] Missing clear API for getAttribute()

### ISSUE THREAD

**Issue by NicolasCARPi** [DirectoryTree/LdapRecord#568]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 8.1

Hello Steve.

At some point in my code, I want to get a specific attribute from a `Model`. If I call `getAttribute()`, I need to check if it's an array afterwards. It would be great to have a way to get an attribute and be sure it's a string or it throws an AttributeNotFound exception. So this function would also look into the resulting array for the real value. Or maybe this exists already?

Side note: I think it's dangerous to have so many `mixed` as return types, it makes it very hard to figure out what kind of things can be returned by functions. I would suggest to list explicitely the returned types, and have restrictive/clear return types as much as possible.

**Comment by stevebauman** [comment]
Hi @NicolasCARPi!

> It would be great to have a way to get an attribute and be sure it's a string or it throws an AttributeNotFound exception. So this function would also look into the resulting array for the real value. Or maybe this exists already?

I believe you're looking for `hasAttribute()`, which will return `false` if the attribute is an empty array or `null`:

```php
$user = User::findOrFail('...');

if ($user->hasAttribute('foo')) {
    // The "foo" attribute is non-empty.
}
```

> Side note: I think it's dangerous to have so many mixed as return types, it makes it very hard to figure out what kind of things can be returned by functions. I would suggest to list explicitely the returned types, and have restrictive/clear return types as much as possible.

Strict return types are being added in `v3`, however there will be `mixed` returns where necessary 👍

**Comment by NicolasCARPi** [comment]
Thank you, `getFirstAttribute()` was what I was looking for.
