### ISSUE TITLE
[Support] Error using TLS in Laravel, but working while using ldapsearch

### ISSUE THREAD

**Issue by zendi014** [DirectoryTree/LdapRecord#570]
error while using TLS config in env set as `true`, then returning 
`ldap_start_tls(): Unable to start TLS: Connect error. Error Code: [2]`

but working while using ldapsearch using ldaps://localhost

**Comment by stevebauman** [comment]
Hi @zendi014,

If you're able to connect via the `ldaps://` protocol, then you must have SSL enabled. Not TLS. TLS is performed under the traditional `ldap://` protocol.

Set `use_ssl => true` instead of `use_tls => true` in your LDAP configuration, and you should be all set.

**Comment by zendi014** [comment]
Hi @stevebauman i've been tried to set either ` use_ssl => true ` or  `use_tls => true`, but still got the same error message
im using openldap/osixia running in docker container

**Comment by stevebauman** [comment]
Hi @zendi014,

Can you post your LDAP configuration with any sensitive details omitted?

**Comment by zendi014** [comment]
in ldap.php
        'default' => [
            'hosts' => [env('LDAP_HOST')], // ldap.forumsys.com
            'username' => env('LDAP_USERNAME'),
            'password' => env('LDAP_PASSWORD'),
            'base_dn' => env('LDAP_BASE_DN'),
            'timeout' => env('LDAP_TIMEOUT', 5),
            'use_ssl' => env('LDAP_SSL', false),
            'use_tls' => env('LDAP_TLS', false),
        ],

in .env
LDAP_CONNECTION=default
LDAP_HOST=localhost
LDAP_BASE_DN="dc=openldap,dc=org"
LDAP_USERNAME="cn=admin,dc=openldap,dc=org"
LDAP_PASSWORD=password_here
LDAP_TLS=true
LDAP_LOGGING=false

**Comment by zendi014** [comment]
the authentication without tls or sll is running well, but we need to improve the user management for adding and update user include the password attribute

**Comment by stevebauman** [comment]
Thanks for posting that @zendi014.

To confirm, you’ve tried removing `LDAP_TLS` from your `.env` and have inserted `LDAP_SSL=true` and you’re still unable to connect?

Also, are you unable to connect at all if you disable both TLS and SSL?

**Comment by zendi014** [comment]
@stevebauman confirmed, i've tried to change directly the configuration in ldap.php
but also unable to connect.

**Comment by stevebauman** [comment]
Thanks for confirming that @zendi014.

Can you please post your working code that you have in which you’re able to search the LDAP server using the raw PHP ldap* functions?

Having that may make it easier to debug your SSL issues.

**Comment by zendi014** [comment]
@stevebauman thanks for respone

connection using `ldapsearch`
![image](https://user-images.githubusercontent.com/48636084/223608702-ce23f2fd-7bee-4097-a194-b8c862b68659.png)

connecting using `php artisan ldap:test`
![image](https://user-images.githubusercontent.com/48636084/223609139-a4b2bac1-96ae-4380-8f61-aaffc0679c69.png)

**Comment by zendi014** [comment]
@stevebauman thanks for respone

this the connection test using `ldapsearch`
![image](https://user-images.githubusercontent.com/48636084/223609393-7acd8515-6e37-4db0-90a2-b5cae03f5f2c.png)


this the connection test using `php artisan ldap:test`
![image](https://user-images.githubusercontent.com/48636084/223609342-ad21cffb-793a-40a6-abba-721a3d9fb4b4.png)

**Comment by zendi014** [comment]
@stevebauman thanks for respone

this the connection test using `ldapsearch`
![image](https://user-images.githubusercontent.com/48636084/223609549-3e5b93ee-b44b-4ce6-93bb-33e453aefcac.png)


this the connection test using `php artisan ldap:test`
![image](https://user-images.githubusercontent.com/48636084/223609591-a190f354-fb9d-4ed3-a670-185e777a1129.png)

**Comment by stevebauman** [comment]
It appears you still have TLS enabled, according to the connection error messages that are displayed via the test.

Also, it appears you’re connecting via the `ldapsearch` command directly on the docker LDAP container. Can you connect with `ldapsearch` from your computer outside of the container? The LDAPS port may not be open on your docker container (636).

**Comment by zendi014** [comment]
yes im just show the connection error while using tls or ssl, 
the connection using ldapsearch successfully accessed from outside the container

**Comment by stevebauman** [comment]
The connection error is the same, indicating that TLS is still being used. Are you caching your Laravel config files?

**Comment by zendi014** [comment]
docker exec ssoopenldap ldapsearch -x -H ldaps://localhost:636 -b dc=***** -D "cn=admin,dc=*******" -w password_here

its also running
![image](https://user-images.githubusercontent.com/48636084/223612193-269d37c0-bc0b-4028-88fa-f966fdfda038.png)

**Comment by zendi014** [comment]
the cache it's already cleared while i updated the configuration files

**Comment by stevebauman** [comment]
When you run docker exec, it’s running `ldapsearch` inside of the container itself, not from outside of it using your OS. I suspect there is a network port issue on your docker container configuration, and it is not allowing traffic over port 636.

Unfortunately, I’m out of possible debugging solutions. You will have to take a deep dive and inspect this issue on your computer.
