### ISSUE TITLE
[Bug] composer install fails in laravel 10

### ISSUE THREAD

**Issue by cfinnestad** [DirectoryTree/LdapRecord#576]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.2
 - Laravel Version: 10.0 

**Describe the bug:**
Compose install fails as laravel 10 is not in the list

>composer require directorytree/ldaprecord-laravel
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^2.7 for directorytree/ldaprecord-laravel
./composer.json has been updated
Running composer update directorytree/ldaprecord-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - directorytree/ldaprecord-laravel[v2.7.2, ..., v2.7.3] require directorytree/ldaprecord ^2.4.4 -> satisfiable by directorytree/ldaprecord[v2.4.4, ..., v2.20.3].
    - directorytree/ldaprecord-laravel[v2.7.0, ..., v2.7.1] require illuminate/support ^5.6|^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v5.6.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4
] but these were not loaded, likely because it conflicts with another require.
    - directorytree/ldaprecord[v2.4.4, ..., v2.7.0] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argume
nt for the update command.
    - directorytree/ldaprecord[v2.7.1, ..., v2.9.3] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it
 as an argument for the update command.
    - directorytree/ldaprecord[v2.9.4, ..., v2.20.3] require psr/simple-cache ^1.0|^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sur
e you list it as an argument for the update command.
    - Root composer.json requires directorytree/ldaprecord-laravel ^2.7 -> satisfiable by directorytree/ldaprecord-laravel[v2.7.0, v2.7.1, v2.7.2, v2.7.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require directorytree/ldaprecord-laravel:*" to figure out if any version is installable, or "composer require directorytree/ldaprecord-laravel:^2.1" if y
ou know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by cfinnestad** [comment]
php artisan vendor:publish --provider="LdapRecord\Laravel\LdapServiceProvider"

I used: composer require directorytree/ldaprecord-laravel -W
this installed but then this failed.
php artisan vendor:publish --provider="LdapRecord\Laravel\LdapServiceProvider"

**Comment by stevebauman** [comment]
Hi @cfinnestad,

Please see https://github.com/DirectoryTree/LdapRecord-Laravel/issues/392.

This issue will be resolved in the next major v3 release.
