### ISSUE TITLE
[Bug] memberof attribute not returned in LDAP model

### ISSUE THREAD

**Issue by cheesegrits** [DirectoryTree/LdapRecord#579]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - LdapRecord-Laravel Major Version: v2
 - PHP Version: 8.2

**Describe the bug:**

I don't know if this is a bug or just A Thing, but when fetching my LDAP user models, the 'memberof' attribute is not there.  Fetching a group does however get the 'member' attribute.

The reason I need this is I'm having to fix a weird inconsistency I sometimes see creeping in to my LDAP server, where a group's 'member' attributes don't exactly match the user's 'memberof'.  Like, I'll have a group where some of the 'member' users do not have the corresponding 'memberof' attribute for that group, or vice versa.  No idea how this happens, but it does, and often enough that I do need to fix it.

So I'm trying to write some code to detect and fix this, by just comparing and repairing the raw attributes, rather than using $group->members() and $user->groups().  But ... I kinda need to get the user 'memberof' to do that.

Any ideas gratefully received.

**Comment by stevebauman** [comment]
Hey @cheesegrits!

> If I do ...
> 
> $ldapUser = CotakUser::find($dn, ['*', 'memberof']);
> 
> ... it doesn't include 'memberof' (even though find() takes $columns as a param), but if I do ...
> 
> $ldapUser = CotakUser::where('entryDn', '=', $dn)->get(['*', 'memberof'])->first();
> 
> ... it does include them.

Are you finding and receiving the same user back in both above examples? LdapRecord forwards the selected attributes right into PHP's `ldap_search()` and `ldap_read()` methods:

https://github.com/DirectoryTree/LdapRecord/blob/e4e6ca496c8fc35132a9ea90a6a7f21f1f29278b/src/Query/Builder.php#L717-L723

Also, how many hosts do you have configured? It's possible depending on your environment that one of your queries may be hitting alternate hosts, where the `memberof` attribute may be stored in the root domain, but not in a replicated one (a referenced attribute).

Another also, how many group memberships does the user have? If there are many, the server may require them to be paginated over.

> Not a huge deal, but I would have expected find($dn, ['my','columns']) to include those columns?

This is definitely how it is expected to work, though LDAP servers vary in their virtual attribute implementations. `memberof` is a virtual attribute (i.e., it does not actually exist). It is calculated by the server.

> We (my small agency) would like to sponsor you. Does it matter who sponsors you, as it pertains to prioritizing stuff in GitHub? The sponsorship would probably come from my partner's account rather than mine - since GitHub quit accepting PayPal, and I won't give them my CC details.

Thanks for considering a sponsorship! No it doesn't matter at all 👍

**Comment by cheesegrits** [comment]
OK, I'll get my partner to start a sponsorship.

Yes, I'm testing the same user.  I only have one LDAP server.  I have about 30 groups total at the moment, and any one user only has a handful of groups, maybe a dozen tops.

I can literally put these two lines of code one after the other:

```
                $ldapUser = CotakUser::find($user->escapeDn(), ['*', 'memberof']);
                $ldapUser = CotakUser::where('entryDn', '=', $user->escapeDn())->get(['*', 'memberof'])->first();
```

... the first one doesn't return the 'memberof' attribute, the second one does.

https://app.screencast.com/FNkJH2ZMU4j6C?conversation=HhxXTa2SHdz7I60iGwS05C

**Comment by cheesegrits** [comment]
> Thanks for considering a sponsorship ❤️! No it doesn't matter at all 👍

Hey!  Hopefully my partner Robbie has been in touch about the sponsorship?

**Comment by stevebauman** [comment]
Hi @cheesegrits! I did receive a sponsorship from
“mediaateam” if this is what you’re referring to? I haven’t received any emails or DMs though.

**Comment by cheesegrits** [comment]
> Hi @cheesegrits! I did receive a sponsorship from “mediaateam” if this is what you’re referring to? I haven’t received any emails or DMs though.

Yup, that's us. She said she did the level that gets us a consult? I'm on a road trip atm (Alabama to Seattle, back via San Francisco about 6000), back in about a week. I'd like to get a sanity check from you on a couple of things.

**Comment by stevebauman** [comment]
Excellent, thank you 🙏 

> She said she did the level that gets us a consult? 

Yes that's correct.

>  I'd like to get a sanity check from you on a couple of things.

Sounds good! Let me know whenever you're available and we can setup a meeting. 😄
