### ISSUE TITLE
Method findByAnr

### ISSUE THREAD

**Issue by testlorenzospa** [DirectoryTree/LdapRecord#582]
Hello.

I haven't found the method findByAnr nor in the code neither in the documentation.
Where can I find it?

Thanks very much.

**Comment by testlorenzospa** [comment]
Sorry, an information.
I am using version 2.20.3

**Comment by stevebauman** [comment]
Hi @testlorenzospa, thanks for the report! The code for this function is located here:

https://github.com/DirectoryTree/LdapRecord/blob/7ccfdcae71ad15636d24b0bd9b1bd4cebc23b367/src/Query/Model/Builder.php#L144-L158

I've also updated the documentation to include usage:

https://ldaprecord.com/docs/core/v2/searching-api/#findbyanr

Here is how you can use `findByAnr()`:

**findByAnr**:

```php
$query = $connection->query();

if ($entry = $query->findByAnr('John Doe')) {
    // Found entry!
} else {
    // Not found.
}
```

**findByAnrOrFail**:

```php
$query = $connection->query();

try {
    $entry = $query->findByAnrOrFail('John Doe');
} catch (\LdapRecord\Models\ModelNotFoundException $ex) {
    // Not found.
}
```
