### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by testlorenzospa** [DirectoryTree/LdapRecord#585]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 8.1

**Describe the bug:**

Hello.

In AWS, I have an OpenLDAP instance (I am not sure if this is really an instance) with a group and some users.
In my PHP code, when I use the instruction

$g = Group::where("cn","=","group-name")->first();

or the intruction

$g = Group::find("DN");

I should obtain the reference to the group in the OpenLDAP instance.
Instead, I get a null value for the variable $g.

Executing some debugging (not very well...) I have discovered that the search filter builded by the library (for the second instruction) is

(&(objectclass=top)(objectclass=groupofuniquHello.

In AWS, I have an OpenLDAP instance (I am not sure if this is really an instance) with a group and some users.
In my PHP code, when I use the instruction

$g = Group::where("cn","=","group-name")->first();

or the intruction

$g = Group::find("DN");

I should obtain the reference to the group in the OpenLDAP instance.
Instead, I get a null value for the variable $g.

Executing some debugging (not very well...) I have discovered that the search filter builded by the library (for the second instruction) is

(&(objectclass=top)(objectclass=groupofuniquenames)(objectclass=*))

However, checking in my instance LDAP in AWS I have dicovered that the group has the objectclass  with the value groupofnames.
After many time, I have found in the library how to modify this value for using groupofnames instead of groupofuniquenames. Then, after I have changed this value to groupofnames the two function are working as expect.

What is the drama?
Why in my instance LDAP in AWS I have a value for objectclass (groupofnames) for my group when instead in the library there is another value (groupofuniquenames) for getting a group but with this the two functions doesn't work?

Thanks.

**Comment by stevebauman** [comment]
Hi @testlorenzospa,

The query is not being created incorrectly -- this is the correct filter for the `OpenLDAP\Group` object classes, as shown here:

https://github.com/DirectoryTree/LdapRecord/blob/00d04ee463322eb288616c20adeb28387d43fae4/src/Models/OpenLDAP/Group.php#L5-L15

It appears the OpenLDAP distribution on AWS you're using uses a different attribute to indicate it being a group. In this case, you must create your own `Group` model and set the `$objectClasses` property appropriately:

```php
namespace App\Ldap;

use LdapRecord\Models\Model;

class Group extends Model
{
    /**
     * The object classes of the LDAP model.
     *
     * @var array
     */
    public static $objectClasses = [
        'top',
        'groupofnames',
    ];
}
```

Then, you can query against your directory and the appropriate filter will be generated, returning you your OpenLDAP groups:

```php
use App\Ldap\Group;

$groups = Group::get();
```

Closing, as this will resolve your issue, but feel free to comment back if you encounter issues and I can assist further 👍

**Comment by testlorenzospa** [comment]
Hello @stevebauman.

Thanks for your reply.

One question (it is only for better understand).

In past (but also still now), in a web PHP project I have used your last library (Adldap2).
With Adldap2 I am not having this issue about the group.
Infact, with this library I can get happily the reference to the group and to the users inside.

Why instead with LdapRecord I have this issue?

Obviuosly, I know that this two library (Adldap2 and LdapRecord) works differently but I image that a LDAP filter search (for get a group) remains similar (but maybe not, I am not very expert about LDAP).

Thanks very much.

**Comment by testlorenzospa** [comment]
Hello @stevebauman.

Other then the previous question, I have a problem with you method.
I have follow your suggestion, but now I have another issue.
When I call the class with the right objectclass (in my case) I have the following error
**Call to undefined method LdapRecord\Query\Model\Builder::members()**

How can I get the users inside the group?

Thanks again.

**Comment by stevebauman** [comment]
Hi @testlorenzospa,

> Why instead with LdapRecord I have this issue?

LdapRecord was built from the ground up to be an [Active Record](https://en.wikipedia.org/wiki/Active_record_pattern) implementation for LDAP, and as such, it requires some more knowledge and configuration of both LDAP and how Active Record works. While it requires a bit more knowledge, it's far more configurable and extendable than Adldap2. Adldap2 is quite rigid and not easily extendable.

> How can I get the users inside the group?

Please read the documentation on implementing relationships on your new `Group` model:

https://ldaprecord.com/docs/core/v2/model-relationships

```php
class Group extends Model
{
    /**
     * The object classes of the LDAP model.
     *
     * @var array
     */
    public static $objectClasses = [
        'top',
        'groupofnames',
    ];

    /**
     * The members relationship.
     *
     * Retrieves members that are apart of the group.
     *
     * @return \LdapRecord\Models\Relations\HasMany
     */
    public function members()
    {
        return $this->hasMany([static::class, User::class], 'memberUid');
    }
}
```

Keep in mind that the included models in LdapRecord for OpenLDAP won't work for every distribution, as OpenLDAP implementations vary (as you've discovered with AWS OpenLDAP). The included models are for those with the standard LDAP distributions. Customized distributions will always require custom models to setup.
