### ISSUE TITLE
ldap_control_paged_result deprecated

### ISSUE THREAD

**Issue by Troopster19** [DirectoryTree/LdapRecord#59]
- LDAP Server Type: Active Directory
- PHP Version: 7.4.0

### Description:
As per https://www.php.net/manual/en/migration74.deprecated.php: 

ldap_control_paged_result_response() and ldap_control_paged_result() are deprecated. Pagination controls can be sent along with ldap_search() instead.

**Comment by stevebauman** [comment]
Hi @Troopster19, I've seen this - and it's going to be tricky to resolve in a backwards compatible manor, since PHP 7.2 does not support the `serverctrls` parameter in `ldap_search`.

How do you think this should be tackled?

**Comment by Troopster19** [comment]
Sounds like there isn't going to be a very clean way to do it. Could a check be added for the PHP version number? Use ldap_search for >=7.3 and fall back to ldap_control_paged_result for <7.3?

**Comment by stevebauman** [comment]
I agree with that, I think that is the only way. I'll have to rebuild the `runPaginate` method in the query builder to determine the current PHP version, and then run a compatible method.

https://github.com/DirectoryTree/LdapRecord/blob/3e024c437de4a2e531f3dc1179bb1f4fe0212144/src/Query/Builder.php#L507

**Comment by stevebauman** [comment]
Ok whew 😅  This one was a difficult to work out and implement - but it's done! Super excited about it.

A new release will be out in the next day or so with this fix.

**Comment by stevebauman** [comment]
[Release is out!](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.1.3). 🎉

**Comment by Troopster19** [comment]
Looks good so far! Thanks for all your great work :)
