### ISSUE TITLE
Carbon error when checking lockouttime

### ISSUE THREAD

**Issue by ctyler69** [DirectoryTree/LdapRecord#592]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - LdapRecord-Laravel Major Version: v2
 - PHP Version:  7.3

I am work on a main dashboard. I am getting all the users and checking for 

1. userlockouttim ($user->ldap->getFirstAttribute('lockouttime') > 0)
2. AccountControl::LOCKOUT
3. AccountControl::PASSWORD_EXPIRED
4. AccountControl::ACCOUNTDISABLE

The issue I am having is with the lockouttime. 
if I use $user->lockouttime[0] ?? 0 > 0 I get the error:

Cannot use object of type Carbon\Carbon as array

If I use $user->getFirstAttribute('lockouttime') > 0

I get the error:

Object of class Carbon\Carbon could not be converted to int

Here is the code:
Grab all of the users:
` $users = \App\Models\User::all();`

Set up the problem user collection:
`$problemUsers = collect();`

Loop over the users:

`
foreach ($users as $user) {

            $uac = new LdapRecord\Models\Attributes\AccountControl(
                $user->ldap->getFirstAttribute('userAccountControl')
            );

if ($user->ldap->getFirstAttribute('lockouttime') > 0) {
                    if (!$problemUsers->contains('id', $user->id)) {
                        $problemUsers->push($user);
                    }
                }

if ($uac->has(AccountControl::LOCKOUT)) {
                if (!$problemUsers->contains('id', $user->id)) {
                    $problemUsers->push($user);
                }
            }

}`

Then loop over the problem users:
 foreach ($problemUsers as $user) {
            $uac = new LdapRecord\Models\Attributes\AccountControl(
                $user->ldap->getFirstAttribute('userAccountControl')
            );
            $message = $user->ldap->getFirstAttribute('givenName') . ' ' . $user->ldap->getFirstAttribute('sn');
            if (!is_int($user->ldap->getFirstAttribute('lockouttime') && ($user->ldap->getFirstAttribute('lockouttime') != NULL))) {
                $message .= ' <b>Locked themselves out - ' . gettype($user->ldap->getFirstAttribute('lockouttime')) . ' ' . $user->ldap->getFirstAttribute('lockouttime');
            }
            if ($uac->has(AccountControl::LOCKOUT)) {
                $message .= ' <b>Is in Lock Out Status</b> ';
            }
            if ($uac->has(AccountControl::PASSWORD_EXPIRED)) {
                $message .= ' <b>Password Expired</b> ';
            }
            if ($uac->has(AccountControl::ACCOUNTDISABLE)) {
                $message .= ' <b>Disabled</b> ';
            }
            echo $message . '<br>';
        }

This is the code I am testing directly in the route web.php file

My apologies the code mark up does not seem to be working.

**Comment by wewhite** [comment]
> The issue I am having is with the lockouttime.
> if I use `$user->lockouttime[0] ?? 0 > 0` I get the error:
> 
> Cannot use object of type Carbon\Carbon as array

Do not use lockouttime as an array, change `$user->lockouttime[0]` to `$user->lockouttime`

**Comment by stevebauman** [comment]
@wewhite Is correct, `$user->lockouttime` will be an instance of `Carbon` if it's set. If it's set to zero `0`, then it will be zero. If it's not set, or set to `null`, it will be `null`.

If you want to retrieve the raw attribute value, you may call `$user->getAttributes()['lockouttime'] ?? null`.

**Comment by stevebauman** [comment]
No worries @ctyler69! Let me know if you run into any further 🙏
