### ISSUE TITLE
How to extend User/Group with custom model?

### ISSUE THREAD

**Issue by igittigitt** [DirectoryTree/LdapRecord#594]
Hi, i'm new to Laravel stuff so maybe my question is stupid, please don't blame me.

I'd like to create my own User/Group model because my Ldap is different from standard OpenLDAP in means of LDAP classes needed for those entry-types (e.g, need some extra ns... classes). I'm also using the lib outside Laravel framework, so any laravel implementation hints won't help me.

What is the best way to do this, without editing the existing code found under Model/... ?

**Comment by stevebauman** [comment]
Hi @igittigitt,

Have you taken a look at the documentation on this?

https://ldaprecord.com/docs/core/v2/models

You may create models by extending the base `LdapRecord\Models\Model` class and define the object classes that your `User` or `Group` object contains:

```php
namespace App\Ldap;

use LdapRecord\Models\Model;

class User extends Model
{
    public static $objectClasses = [
        'top',
        'person',
        'organizationalperson',
        'user',
    ];
}
```

Once you've created your model, you can immediately begin using it:

```php
use App\Ldap\User;

$users = User::get();
```

If you have more particular questions that is not documented, I can assist you further, however the docs should answer most of your questions.
