### ISSUE TITLE
Ldap query Returning Empty Results

### ISSUE THREAD

**Issue by ctyler69** [DirectoryTree/LdapRecord#60]
- LDAP Server Type: 
- PHP Version: #.#

### Steps To Reproduce:
LDAP Server Type: Active Directory
PHP Version: 7.3.13
Laravel: 6

I cannot seem to query AD. I had been using the Adldap2 for Laravel without issue, 

I followed the quickstart:
1.	composer require directorytree/ldaprecord-laravel
2.	php artisan vendor:publish --provider="LdapRecord\Laravel\LdapServiceProvider"
3.	Configure your LDAP connection
LDAP_LOGGING=true
LDAP_CONNECTION=default
LDAP_HOST="xxxxx.comlivserv.com"
LDAP_USERNAME="xxxxxxxxx@comlivserv.com"
LDAP_PASSWORD=’xxxxxxxxxxxx’
FOLLOW_REFERALS=true
LDAP_BASE_DN="DC=comlivserv,DC=com"
LDAP_TIMEOUT=5
LDAP_SSL=true
LDAP_TLS=false
These are the same value used in  adldap2. 
4.	I created an ldap user model: php artisan make:ldap-model User
5.	Added $objectClasses set:
public static $objectClasses = [
        'top',
        'person',
        'organizationalperson',
        'user',
    ];
Now when I use: $users = User::get();
I get an empty LdapRecord\Query\Collection 
I get a empty result even if I query by my sammaccountname. 
The log is stating:
[2020-01-22 16:44:56] local.INFO: LDAP (ldaps://xxxxxxx.comlivserv.com:636) - Operation: Search - Base DN: DC=comlivserv,DC=com - Filter: (&(objectclass=top)(objectclass=person)(objectclass=organizationalPerson)(objectclass=user)) - Selected: (*) - Time Elapsed: 83
So it seems like it is connecting - just no results.

**Comment by stevebauman** [comment]
Hi @ctyler69,

Disable `FOLLOW_REFERRALS`, this is likely the issue.

Let me know if you run into anything further!
