### ISSUE TITLE
Error when running php artisan ldap:test

### ISSUE THREAD

**Issue by ripperkhan** [DirectoryTree/LdapRecord#609]
After setting up LdapRecord with a fresh install of Laravel 9+ and try to test the LDAP connect I get the following error:

 Error

  Call to undefined method LdapRecord\ConnectionManager::all()

  at C:\Projects\TestApp\vendor\directorytree\ldaprecord\src\Container.php:63
     59▕      * Forward missing method calls onto the connection manager.
     60▕      */
     61▕     public function __call(string $method, array $parameters): mixed
     62▕     {
  ➜  63▕         return $this->manager->{$method}(...$parameters);
     64▕     }
     65▕
     66▕     /**
     67▕      * Set the current container instance available globally.

  1   C:\Projects\TestApp\vendor\directorytree\ldaprecord-laravel\src\Commands\TestLdapConnection.php:37
      LdapRecord\Container::__call("all", [])

  2   C:\Projects\TestApp\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      LdapRecord\Laravel\Commands\TestLdapConnection::handle()

I have tried both the 2 different configuration options and still have the same issue.

**Comment by stevebauman** [comment]
Hi @ripperkhan,

Please fill in the information requested in the issue template. I cannot assist without knowing your installed versions.

Thanks!

**Comment by ripperkhan** [comment]
**Environment:**
 - LDAP Server Type:  ActiveDirectory
 - PHP Version: 8.2
 - Laravel Version: 9.0
 - ldaprecord-laravel Version: v3.x-dev

I apologize I had used the Create issue link from the site and it didn't have the template in the new issue form.

**Comment by ripperkhan** [comment]
I'm sorry I also didn't see I submitted it in the wrong issue tracker. Want me to move it to the LdapRecord-Laravel one?

**Comment by ripperkhan** [comment]
I reverted to ldaprecord-laravelversion 2.7.3 issue went away. I will mark this closed for now but seems like the the dev build has an issue at the moment

**Comment by stevebauman** [comment]
Sorry for the late reply @ripperkhan, and thanks for following up with your issue and posting those details. I've resolved this on the `v3-dev` branch -- you can update to it again if you'd like. v3 is being finalized, so there are no more breaking changes (besides potential bug fixes) that will occur to the brach.
