### ISSUE TITLE
users() method missing

### ISSUE THREAD

**Issue by tekook** [DirectoryTree/LdapRecord#61]
- LDAP Server Type: Active Directory
- PHP Version: 7.4.0

### Description:
Don't know if the docs are outdated or I'm just missing something..

Docs states there is a users() method for query().
Method is not found in Sourcecode.

### Steps To Reproduce:
(1) create a connection
(2) use method $connection->query()->users() -> fails

**Comment by stevebauman** [comment]
Fixed, thanks! :smile:
