### ISSUE TITLE
[Feature] Pure Model functions signature

### ISSUE THREAD

**Issue by NicolasCARPi** [DirectoryTree/LdapRecord#610]
Hello Steve,

So I've just upgraded to 3.0.1. One small note you might want to add in the upgrade guide is the necessity to have the `iconv` extension now.

After upgrading, I run my static analysis tools and it tells me that `findByOrFail` can return a `Model` or an `array`. I want my function to return a `Model`, so I had to add something like "if result instanceof Model, return it", to appease the static gods (and make my code less bugprone!).

But it would be best if I could have access to a function signature that only returns a Model. I'm using the "Container" approach like you showed me so I can use the Models. Now the next step is to have pure function signatures without array type as a possibility. I don't know exactly how that could be achieved in your code, but I'm sure you'll have an idea about it. What do you think, is this something you'd be willing to improve or you consider that a mixed return type is inevitable?

I'm using a generic `Entry` object, and then `$this->entries::findByOrFail('attribute name', 'searched term')`

Best,
~Nico

EDIT: I realized now that I've opened a similar issue #567 in the past...

But in that issue you say you'll consider this change in v3, so here we are. Maybe having `findModelByOrFail` that would make sure we can only return a model would be enough.

**Comment by stevebauman** [comment]
Hey @NicolasCARPi!

> So I've just upgraded to 3.0.1. One small note you might want to add in the upgrade guide is the necessity to have the iconv extension now.

Thanks for the suggestion! I've just added this to the upgrade guide.

In regards to your other suggestions about the multiple return types on `findByOrFail` and other `find` methods, the return types are indeed valid, as the query builder can return both types, but only in their relevant circumstance (using a raw query vs model query). Though I can update these methods and override the return type to indicate that they only return model instances 👍 

I'll work on this now, thanks again for the reminder and suggestion!

**Comment by stevebauman** [comment]
Hi @NicolasCARPi, I've just released a patch for this ([v3.0.2](https://github.com/DirectoryTree/LdapRecord/releases/tag/v3.0.2)).

Let me know if you encounter any issues with your static analysis! 🙏

**Comment by NicolasCARPi** [comment]
Hello Steve,

Thank you very much, I can confirm that the patch fixes this issue! :clap:

**Comment by stevebauman** [comment]
Excellent! Glad to hear 😄
