### ISSUE TITLE
I can't figure out why I keep getting this error - please help!

### ISSUE THREAD

**Issue by chrishultberg** [DirectoryTree/LdapRecord#621]
TypeError
LdapRecord\Query\Builder::prepareWhereValue(): Return value must be of type string, LdapRecord\Models\Attributes\EscapedValue returned

LdapRecord\Query\Builder::prepareWhereValue
vendor/directorytree/ldaprecord/src/Query/Builder.php:955

**Comment by stevebauman** [comment]
Hi @chrishultberg,

Do you have strict types enabled?

**Comment by chrishultberg** [comment]
Thank you for the very fast response!
I did not add strict types nor can I find it anywhere in the project.

If it's helpful, here is the link - https://syllabus.ez-it-solutions.com/login

Try using any user/pass and you'll get the error - this will allow you to see the stack trace.

**Comment by stevebauman** [comment]
Hi @chrishultberg, can you run `composer update` on your server and try again? This should now be patched 👍

**Comment by chrishultberg** [comment]
Thank you so much, Steve!!

**Comment by stevebauman** [comment]
Happy to help @chrishultberg! Closing for now, but let me know if you run into any further issues 👍.
