### ISSUE TITLE
[TypeError] - Models

### ISSUE THREAD

**Issue by chrishultberg** [DirectoryTree/LdapRecord#623]
I did not create a new model because of the Predefined Active Directory Models - however, as soon as I try to log in, I get this error:

TypeError

LdapRecord\Laravel\Auth\UserProvider::fetchLdapUserByCredentials(): Return value must be of type ?LdapRecord\Models\Model, none returned

I have APP_DEBUG enabled - please feel free to see the trace stack:
https://syllabus.jacksonvillecollege.edu/login

**Comment by stevebauman** [comment]
Hi @chrishultberg,

This means you have strict types enabled on your application somewhere that's applying them globally.

The without strict types, the return of the function will be automatically converted to null. However, with strict types enabled, this behavior is disabled, leading to the exception your seeing here.
