### ISSUE TITLE
[Support] Difference Table Name for Login User App and Ldap Account

### ISSUE THREAD

**Issue by hans0801** [DirectoryTree/LdapRecord#624]
**Environment:**
 - LDAP Server Type: [ActiveDirectory]
 - PHP Version: [8.2]

Hi @stevebauman ,

Just want to ask again.
For now on my App, I used database authentication that sync into "Users" table.
I want sync all user on my AD too but on the difference "Users" table. Is it Possible? if yes, which line code/file should I change into.
Here is my auth config.
<img width="458" alt="Screenshot 2023-08-02 at 17 58 32" src="https://github.com/DirectoryTree/LdapRecord/assets/28553376/d1dfd380-20e2-4bdd-9879-2c3e709ec388">

Thanks in advance

**Comment by stevebauman** [comment]
Hi ther @hans0801,

If you would like to synchronize all of your AD users into another DB table, you can utilize the `Synchronizer` class mentioned in the docs here:

https://ldaprecord.com/docs/laravel/v3/importing

Here's an example:

```php
use App\Models\OtherUser; // <-- The Eloquent model of your user (not your `App\Models\User`)
use LdapRecord\Laravel\Import\Synchronizer;
use LdapRecord\Models\ActiveDirectory\User as LdapUser;

// Create the synchronizer.
$synchronizer = new Synchronizer(OtherUser::class, $config = [
    'sync_attributes' => [
        'name' => 'cn'
    ],
]);

// Import each user from the directory.
LdapUser::each(function (LdapUser $user) use ($synchronizer) {
    $synchronizer->run($user)->save();
});
```

**Comment by hans0801** [comment]
Hi @stevebauman ,

it's worked like a charm.
Thank you so much for your kindly response and information.

**Comment by stevebauman** [comment]
Awesome, glad to hear it worked for you. Always happy to help! 🙏
