### ISSUE TITLE
Can connect with administrator credentials but cannot login 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [DirectoryTree/LdapRecord#625]
**Environment: Ubuntu 20.04.6 LTS**
 - LDAP Server Type: OpenLDAP
 - PHP Version: [ 8.2]

**Describe the bug:**

admin credentials are working successfully with `php artisan ldap:test`

```
LDAP_USERNAME="cn=admin,dc=domain,dc=example,dc=com"
LDAP_PASSWORD="Password"
LDAP_BASE_DN="dc=domain,dc=example,dc=com"
```

but when I try to login with same credetials like

```
protected function credentials(Request $request): array
{
   return [
	'username' => 'cn=admin,dc=domain,dc=example,dc=com',
	'password' => 'Password',
  ];
}
```

It is not working. 
I am using phpLDAPadmin which has LdapRecord as a core package

**Comment by stevebauman** [comment]
Your `username` key is incorrect in the returned array is incorrect. You must return a key to search your directory by. This is currently executing a search in your LDAP directory for a user containing the `username` attribute equal to `cn=admin,dc=domain,dc=example,dc=com`, which will yield no results.

You should use an attribute that will contain a unique value per user, such as `samAccountName`, `mail`, or `userPrincipalName`. Your admin account may not have that those attributes though, so in your circumstance, the below will work:

```php
protected function credentials(Request $request): array
{
   return [
	'cn' => 'admin',
	'password' => 'Password',
  ];
}
```

**Comment by abhitheawesomecoder** [comment]
this is the first thing I tried but this is also not allowing login

```
protected function credentials(Request $request): array
	{
		// return [
		// 	'mail' => $request->get('email'),
		// 	'password' => $request->get('password'),
		// ];

		return [
			'cn' => 'admin',
			'password' => 'Password',
		];
	}
```

**Comment by abhitheawesomecoder** [comment]
Hello sir the issue is yet not resolved

**Comment by stevebauman** [comment]
Hi @abhitheawesomecoder,

Please post your LDAP configuration.

**Comment by abhitheawesomecoder** [comment]
LDAP_LOGGING=true
LDAP_CONNECTION=default
LDAP_HOST=ldap01.calsob.com
LDAP_PORT=389
LDAP_USERNAME="cn=admin,dc=ldap01,dc=calsob,dc=com"
LDAP_PASSWORD="Password"
LDAP_BASE_DN="dc=ldap01,dc=calsob,dc=com"
LDAP_TIMEOUT=5
LDAP_SSL=false
LDAP_TLS=false
LDAP_SASL=false

**Comment by abhitheawesomecoder** [comment]
I am able to login as a user
![Screenshot (30)](https://github.com/DirectoryTree/LdapRecord/assets/3944526/03e8eef5-a996-4fd1-8d79-4aeb2883accd)

**Comment by abhitheawesomecoder** [comment]
if there was some issue with server then php artisan ldap:test won't have worked.

**Comment by abhitheawesomecoder** [comment]
I came across this answer and I think this could be the real issue, what do you think? 

https://unix.stackexchange.com/questions/744327/cant-login-on-phpldapadmin-using-admin-user

**Comment by stevebauman** [comment]
Hi @abhitheawesomecoder, apologies for the delayed response.

I'm honestly not sure about this. The error you're seeing is a generic "incorrect password" error. If you're encountering problems logging in with your configured administrator account, this is either environment or application related. Since I don't maintain or have any involvement in phpLDAPAdmin, I would suggest asking on their issue tracker.
