### ISSUE TITLE
[Bug] Auth::attempt not working when no default credentials provided

### ISSUE THREAD

**Issue by noahshz** [DirectoryTree/LdapRecord#627]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.2.9
 
**Describe the bug:**
For my Laravel REST-Application i'm using Database Authentication. I don't want to provide a default username and password so I set both values to `null`. If i want to login now, the `Auth::attempt` returns false, that means the username or password is incorrect.
For testing purposes I provided a default username and password then everything works fine. 

If I do the same thing (not providing default credentials) and then use the LdapRecord Connection to authenticate a user, the auth is successfull, but then things like the attribute synchronisation isn't working.

PS: anonymous binding is enabled

For better understanding I'll paste my code down below:

`config/auth.php`:
```php
'defaults' => [
        'guard' => 'ldap',
        'passwords' => 'users',
    ],

    'guards' => [
        // jwt with ldap auth
        'ldap' => [
            'driver' => 'jwt',
            'provider' => 'ldap',
        ],
    ],


    'providers' => [
        'ldap' => [
            'driver' => 'ldap',
            'model' => LdapRecord\Models\ActiveDirectory\User::class,
            'rules' => [],
            'scopes' => [],
            'database' => [
                'model' => App\Models\User::class,
                'sync_passwords' => false,
                'password_column' => false,
                'sync_attributes' => [
                    'email' => 'mail',
                    'username' => 'samaccountname',
                    'fname' => 'givenName',
                    'lname' => 'sn'
                ],
            ],
        ],
    ],
```

`AuthController.php`:
(The login function where auth without providing default credentials ISN't working)
```php
 public function login(Request $request) {
        // Check if username and password are passed
        $credentials = $request->only(['username', 'password']);
        if(!array_key_exists('username', $credentials) || !array_key_exists('password', $credentials) ) {
            return json_response(400, false, __('_.ERR_MISSING_CREDENTIALS'));
        }
        // Map username to samaccountname
        $credentials['samaccountname'] = $credentials['username'];
        unset($credentials['username']);
        // Check if auth is successful
        if(!$token = Auth::attempt($credentials)) {
            return json_response(401, false, __('_.ERR_WRONG_CREDENTIALS'));
        }
        return json_response(200, true, __('_.MSG_LOGGED_IN'))
           ->withCookie(cookie(config('_re.session_cookie_name'), $token, config('jwt.ttl')));
    }
```

`AuthController.php`:
(The login function where auth without credentials IS working)
```php
public function login(Request $request) {
        // Check if username and password are passed
        $credentials = $request->only(['username', 'password']);
        if(!array_key_exists('username', $credentials) || !array_key_exists('password', $credentials) ) {
            return json_response(400, false, __('_.ERR_MISSING_CREDENTIALS'));
        }

        // Try to connect
        $connection = new \LdapRecord\Connection(['hosts' => config('ldap.connections.default.hosts')]);
        try {
            $connection->connect();
        } catch (\LdapRecord\Auth\BindException $e) {
            $error = $e->getDetailedError();
            Log::error('[LDAP]: ' . $error->getErrorCode());
            Log::error('[LDAP]: ' . $error->getErrorMessage());
            Log::error('[LDAP]: ' . $error->getDiagnosticMessage());
            return json_response(500, false, __('_.ERR_AD_NOT_REACHABLE'));
        }

        // Try to login
        $suffix = '@mydomain.com';     // only changed for posting on github
        if($connection->auth()->attempt($credentials['username'] . $suffix, $credentials['password'])) {
           // Auth is successfull-> but the synchronising attributes not work -->

            $user = User::where('username', '=', $credentials['username'])->first();
            $token = auth()->login($user);
            return json_response(200, true, __('_.MSG_LOGGED_IN'))->withCookie(cookie(config('_re.session_cookie_name'), $token, config('jwt.ttl')));

        }

        // If failed -> response
        return json_response(401, false, __('_.ERR_WRONG_CREDENTIALS'));
}
```

**Comment by stevebauman** [comment]
Hi @noahshz,

> If I do the same thing (not providing default credentials) and then use the LdapRecord Connection to authenticate a user, the auth is successfull, but then things like the attribute synchronisation isn't working.

This isn't possible. A user account must exist and be used to authenticate, because an email or username is required to create a local eloquent user in the database. When you anonymously bind to your LDAP server, there's no account to synchronize, thus no user to create and then authenticate into your Laravel application.

Let me know if I've misunderstood and I can re-open this issue.

**Comment by noahshz** [comment]
I think you misunderstood, but that's not a problem, maybe my post wasn't worded correctly. The AD user exists, with username, email, name etc. LdapRecord wants a standard username and password during configuration, for example to call "ldap:test" and test the Ldap connection. To log in to my application, I use database authentication. This also works as it should if I enter an AD username and password and I have specified a standard username and password in the ".env". (The configurations and code examples are above). If I now set the default username and password to "null" in the configuration, the authentication no longer works as it was written in the documentation.

**Comment by stevebauman** [comment]
LdapRecord requires a username and password to be configured (or, anonymous authentication enabled on the LDAP server) so that it may connect and search for the authenticated user **before** the actual LDAP authentication attempt takes place. This allows LdapRecord to login users with any attribute of your choice (such as `mail`, for example), since we can lookup the user with the attribute and then attempt binding to the domain with their distinguished name and submitted password.

You can see this comment for more detail: https://github.com/DirectoryTree/LdapRecord/issues/330#issuecomment-906398075

> LdapRecord needs to be able to search your directory for the user that is logging in via your login attribute (uid, mail, userprincipalname, etc.), so it can retrieve the users distinguished name for binding after successfully locating the user. This is exactly how database authentication works. You must configure a username and password so that Laravel may search the database to see if the user may authenticate.
> 
> This is also just simply impossible if you were using the plain LDAP authentication driver, as we would have to save the users credentials somehow and also assume their distinguished name to be able to re-bind them upon every subsequent request to your Laravel application to retrieve their user account for session management. This is due to PHP's stateless nature. It does not persist LDAP connectivity between requests. It must instantiate a new connection every single time a request is made.
> 
> If you allow anonymous authentication on your LDAP server, you could then set the username and password configuration keys to null. But of course you would have to trim the permissions of anonymous binds as well.
> 
> If you're somehow able to get around the limitations of pre-binding, you can always write a PR that I can merge in 👍
> 
> Hope this helps!

**Comment by noahshz** [comment]
Ok thanks I understand now. Thanks for your help. I found a workaround that allows database authentication to work even without standard credentials. I'm including the code example here so that if others encounter the problem, they maybe have a solution.

```php
         [...]
        $credentials = $request->only(['username', 'password']);
        if(!array_key_exists('username', $credentials) || !array_key_exists('password', $credentials) ) {
            return json_response(400, false, __('_.ERR_MISSING_CREDENTIALS'));
        }

        // Map username to samaccountname
        $credentials['samaccountname'] = $credentials['username'];
        unset($credentials['username']);

/*
The solution:
I change the default username and passwort in the connection configuration and try to search with these credentials.
If this account could not be found, the auth attempt will return false.
*/
        // change configuration to bind with username and passwort
        $default_conf = config('ldap.connections.default');
        $default_conf['username'] = $credentials['samaccountname'] . "@energie.local";
        $default_conf['password'] = $credentials['password'];

        $connection = Container::getDefaultConnection();
        $connection->setConfiguration($default_conf);


        // Check if auth is successful
        if(Auth::attempt($credentials)) {
            return json_response(401, false, 'Wrong credentials'));
        }
        [...]
```
