### ISSUE TITLE
[Bug] max 64-bit int isn't converted into carbon date

### ISSUE THREAD

**Issue by vatsake** [DirectoryTree/LdapRecord#630]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.1

**Describe the bug:**
I recently updated a bunch of packages (I'm not certain which one **broke** it).
directorytree/ldaprecord             v2.17.3 => v2.20.4
directorytree/ldaprecord-laravel   v2.6.0 => v2.7.3
laravel                                          v9.34.0 => v10.21.0

Sometimes accountExpires has a max 64-bit int value (9223372036854775807).
In older versions Carbon parsed this and returned something in the year 2008. Now It doesn't parse it at all.

`"Could not parse '9223372036854775807': Unexpected data found.\nTrailing data"`

Is this a bug or a feature? :D

**Comment by stevebauman** [comment]
Hi @vatsake,

This was actually a bug previously, as the max value cannot be parsed into a date. Instead, that value is returned when the accountExpires attribute contains that value.

Please see the originating bug report here:

https://github.com/DirectoryTree/LdapRecord/issues/552

And the documentation this here:

https://ldaprecord.com/docs/core/v3/active-directory/users/#user-account-expiry

Let me know if you have any further questions!

**Comment by stevebauman** [comment]
Happy to help! Always feel free to drop by if you encounter any further issues or have any questions.

**Comment by stevebauman** [comment]
Ah thanks! Appreciate you letting me know 🙏

**Comment by stevebauman** [comment]
Fixed!
