### ISSUE TITLE
Undefined constant "LdapRecord\Models\Attributes\LDAP_ESCAPE_FILTER"

### ISSUE THREAD

**Issue by gaticlin** [DirectoryTree/LdapRecord#636]
Good afternoon. I created a small Laravel application using LDAP Record. In the local development environment, the application worked perfectly. However, when I migrated it to the production environment, the code stopped working due to this error: Undefined constant "LdapRecord\Models\Attributes\LDAP_ESCAPE_FILTER". If you could assist me, please.

**Comment by stevebauman** [comment]
Hi @gaticlin,

This means your production environment doesn't have the PHP `ldap` extension enabled 👍
