### ISSUE TITLE
[Bug] Chunk fatal error on OrganisationUnits queries

### ISSUE THREAD

**Issue by zoriax** [DirectoryTree/LdapRecord#637]
**Environment:**
 - LDAP Server Type: ActiveDirectory 
 - PHP Version:  8.2

**Describe the bug:**
Hello @stevebauman !

I hope you are fine. 

I tried to use chunk on query with OrganisationUnits, query looks like that 
```
(&(objectclass=top)(objectclass=organizationalunit))
```
If I do the chunk, it finished with errror :
```
Fatal error: Uncaught ErrorException: ldap_search(): Search: Critical extension is unavailable in D:\Datas\www\projets\portail\hotfixes\vendor\directorytree\ldaprecord\src\Ldap.php:207 Stack trace: #0 [internal function]: LdapRecord\Ldap->LdapRecord\{closure}
```

I'm not sur of the root cause but it really looks like it's related to OrganisationUnits. Could you please help me ?

Thank you so much !

**Comment by zoriax** [comment]
Problem solved on my own, sorry for that !

Thanks

**Comment by zoriax** [comment]
Just to clarify this, it was due to "orderBy" before chunk. As I can see it's not possible to mix both ```->orderBy('name')->chunk(...)```. I used sortBy of collection instead.

**Comment by stevebauman** [comment]
Thanks for posting this @zoriax, much appreciated!
