### ISSUE TITLE
[Support] Methods return (v3)

### ISSUE THREAD

**Issue by zoriax** [DirectoryTree/LdapRecord#638]
**Environment:**
 - LDAP Server Type: [e.g. ActiveDirectory 
 - PHP Version: 8.2
Hi @stevebauman ! 

I hope you are fine ?

Juste a little question but I can't find answer on doc. With ```replaceAttribute()``` other methods on v3, I expected to have true / false return if replacement is successfull or not, I have ```null``` retrun if replacement is successfull. 

This return is expected or I missed something ?

Thanks

**Comment by stevebauman** [comment]
Hi @zoriax,

The `replaceAttribute()` method will throw an exception if it is not successful.

This was updated in `v3`, as `bool` return values are no longer returned from model creation/modification methods.

**Comment by zoriax** [comment]
Hi @stevebauman 

Thanks for your return.
