### ISSUE TITLE
[Feature] Auto convert Entry into related models

### ISSUE THREAD

**Issue by zoriax** [DirectoryTree/LdapRecord#640]
**Describe the feature you'd like:**
Hi @stevebauman,

Do you think it will be pssible to add a method to auto convert _Entry_ model into ActiveDirectory / Ldap related model ? 

For example, I need to search for ```test``` with _Entry_ model, for example ```Entry::query()->whereContains('name', 'test')```. I hava as return a user who is named _test_ and a group who is named _GRP_TEST_. 

Here, it will be **amazing** if I can "auto convert" my user into _User_ model and my group Into _Group_ model, maybe with : ```Entry::query()->whereContains('name', 'test')->autoConvert()```.

I think you can use ```objectclass``` or ```objectcategory``` attribute to determine the type of model to use.

Once again, many thanks for the amazing job you do with LdapRecord !

**Comment by zoriax** [comment]
Now I do that with and ```Entry->convert()``` based on objectcategory, but it's a workaround and attribute ``objectcategory``` **must** be present in select, so it's not totally perfect for me

```php
 switch ($q->objectcategory) {
            case 'person' :
                $q = $q->convert(new User());
                break;
            case 'group' :
                $q = $q->convert(new Group());
                break;
            case 'organizational-unit' :
                $q = $q->convert(new OrganizationalUnit());
                break;
            case 'computers' :
                $q = $q->convert(new Computer());
                break;
        }
        return $q;
```

**Comment by stevebauman** [comment]
Hi @zoriax,

I think that's a great idea, though we won't be able to use `objectcategory` as that's only available on ActiveDirectory. We'll have to use `objectclasses`.

We do something like this already in the `Relation` class to convert models to their related instances:

https://github.com/DirectoryTree/LdapRecord/blob/8aee79b58d1ca5cf88f19f495743e9289e898504/src/Models/Relations/Relation.php#L318-L337

Maybe we can extract this logic into models themselves, and models can define what models they can be "morphed to", similar to how Laravel Eloquent has a "morph map":

https://laravel.com/docs/master/eloquent-relationships#custom-polymorphic-types

```php
namespace LdapRecord\Models\ActiveDirectory;

// ...

class Entry extends Model
{
    public function getMorphModels(): array
    {
        return [
            \LdapRecord\Models\ActiveDirectory\User::class,
            \LdapRecord\Models\ActiveDirectory\Group::class,
            \LdapRecord\Models\ActiveDirectory\Printer::class,
            \LdapRecord\Models\ActiveDirectory\Computer::class,
            // ...
        ];
    }
}

```php
use LdapRecord\Models\ActiveDirectory\Entry;

$entry = Entry::find('...');

$entry->morph();
```

And maybe we can provide a map to the morph function so it can be transformed to a model if it matches any of the given model's object classes?

```php
use LdapRecord\Models\ActiveDirectory\Entry;

$entry = Entry::find('...');

$model = $entry->morph([
    \App\Ldap\User::class,
    \App\Ldap\Group::class,
]);
```

Morph method:

```php
public function morph(array $map = null): ?Model
{
    $model = $this->determineModelFromMap($map ?? $this->getMorphMap());

    if ($model) {
        return $this->convert(new $model);       
    }
    
    return $this;
}
```

Just scratching notes here for the implementation.

**Comment by zoriax** [comment]
Hi @stevebauman ! Sounds good like that 🥇 ! 

I enjoy seeing this new features, it will be very useful for me ! 

Thanks <3

**Comment by stevebauman** [comment]
Hey @zoriax, apologies on the delay on this feature, I've just added in this the latest release [v3.4.0](https://github.com/DirectoryTree/LdapRecord/releases/tag/v3.4.0).

You can now call the `morphInto` method to morph a model into its matching model by a given list:

```php
use LdapRecord\Models\ActiveDirectory\Entry;

$entry = Entry::find('...');

$model = $entry->morphInto([
    \App\Ldap\User::class,
    \App\Ldap\Group::class,
]);
```

You can also use `morphIntoOrFail` to attempt morphing a model into a matching model, but if one isn't found, an exception will be thrown:

```php
$entry = Entry::find('...');

try {
    $model = $entry->morphIntoOrFail($models);
} catch (\RuntimeException $e) {
    // Matching model could not be found.
}
```

**Comment by zoriax** [comment]
Hi @stevebauman !

Thanks for this new feature ! 🎉🎉
