### ISSUE TITLE
[Support] Ldap server connection's response problem

### ISSUE THREAD

**Issue by enversanli** [DirectoryTree/LdapRecord#641]
Hello, 

I am having some problems with this package, and I need your support or experience. 

I have installed the package (v3) and added the necessary information to connect to the server with the following information.  

Note : Username and password are not required to connect to the LDAP server. This is an OpenLDAP server and no authentication is required. 

 

```php
'default' => [ 

            'hosts' => [env('LDAP_HOST', example.ldap-server.com')], 

            'username' => env('LDAP_USERNAME', null), 

            'password' => env('LDAP_PASSWORD', null), 

            'port' => env('LDAP_PORT', 389), 

            'base_dn' => env('LDAP_BASE_DN', 'DC=ldap-server,DC=com'), 

            'timeout' => env('LDAP_TIMEOUT', 10), 

            'use_ssl' => env('LDAP_SSL', false), 

            'use_tls' => env('LDAP_TLS', false), 

            'use_sasl' => env('LDAP_SASL', false), 

            'sasl_options' => [ 

                // 'mech' => 'GSSAPI', 

            ], 

        ], 
```
 

When I run the test function in accordance with the above information, I get the following error: 

 

```
Successful : No 

Error Message : Success. Error Code: [] Diagnostic Message: null 
```

Vendor -> Ldap.php
```php
 public function bind(string $dn = null, string $password = null, array $controls = null): LdapResultResponse
    {
        /** @var \LDAP\Result $result */
        $result = $this->executeFailableOperation(function () use ($dn, $password, $controls) {
            return ldap_bind_ext($this->connection, $dn, $password ? html_entity_decode($password) : null, $controls);
        });

        $response = $this->parseResult($result);

        $this->bound = $response && $response->successful(); // Here is the response

        return $response;
    }
}
```

When I debugged the methods executed by the test, I noticed that the successful() function is checking for the errorCode and the errorMessage after ldap_bind_ext(). As you can see in the code above, the errorMessage actually contains a success message ("Bind succeeded"). When I modified the successful() function to return true, everything is working. Please see the example below:  

```php
 public function testLdap(){
    $connection = new Connection([
      'hosts' => 'example.ldap.com',
      'username' => null,
      'password' => null
    ]);

    try {
      $connection->connect();
      
/* Search user in LDAP in order to create DN */
        $search = $connection->query()->where('exampleColumn', '=', 'search parameter')->select('dn')->get(); // Works successfully

      echo "Successfully connected";
    }catch (\LdapRecord\Auth\BindException $e){
      dump($e);
    }
  }

```

In this case, I get successful results when I connect directly using the Connection object as shown above. 

But: If I revert my changes and the successful() function returns false again, the $e->getDetailedError() is null, causing all other function like getErrorCode() / getErrorMessage() / getDiagnosticMessage() to fail. 

Do you have any information about this behavior, or do you observe anything wrong with my configuration? Note: I previously used Adldap2 package which is using ldap_bind(). So most probably the error was already present in the past, but was just not visible. 

I'm waiting your support for that case. Thank you all.

**Comment by stevebauman** [comment]
Ok I've just released [v3.1.3](https://github.com/DirectoryTree/LdapRecord/releases/tag/v3.1.3) with this patch. Run `composer update` and you're all set! 👍

**Comment by enversanli** [comment]
Hello @stevebauman ,
Thank you so much for your support. I will update package and test it also on my project.

Again, Thank you for your support.

**Comment by stevebauman** [comment]
Happy to help @enversanli! Please drop by anytime you need assistance with LdapRecord 👍
