### ISSUE TITLE
[Support] Detect Binding

### ISSUE THREAD

**Issue by zoriax** [DirectoryTree/LdapRecord#643]
Hi @stevebauman,

I need to know how can I detect if a query is "binded". In our environment, we don't accept anonymous connection so we need to check if a specific user is authenticated before running any query in LDAP. Actually, if a query is send anonymously, it failed with a very awful exception :-). It should be in this case better to try/catch on authentication before :-)

Thanks for your help

**Comment by stevebauman** [comment]
Hi @zoriax!

You can do this by retrieving the connection from the query builder and calling `isConnected()`:

```php
use LdapRecord\Models\Entry;

if (Entry::query()->getConnection()->isConnected()) {
    // ...
}
```

Or you can do this by registering a wildcard listener on all the query events:

```php
use LdapRecord\Container;

Container::getDispatcher()->listen('LdapRecord\Query\Events\*', function (string $eventName, array $payload) {
  foreach ($payload as $event) {
    if (! $event->getQuery()->getConnection()->isConnected()) {
      throw new \Exception('Not connected.');
    }
  }
});
```

This should answer your question, but if it doesn't, let me know and I'll re-open this 👍

**Comment by zoriax** [comment]
Many thanks @stevebauman !

**Comment by stevebauman** [comment]
Happy to help @zoriax!
