### ISSUE TITLE
[Feature] User query should return type

### ISSUE THREAD

**Issue by vatsake** [DirectoryTree/LdapRecord#644]
Currently `LdapRecord\Models\ActiveDirectory\User` query()->get() returns `\LdapRecord\Query\Collection`.

But it should return `\LdapRecord\Query\Collection<int, User>` so IDE would autocomplete.

**Comment by stevebauman** [comment]
I don't think so, but I'll check later today to see if they've been able to add them in somehow and use their approach if it works!
