### ISSUE TITLE
[Bug] isDisabled() / isEnabled() doesn't work Computer Model

### ISSUE THREAD

**Issue by zoriax** [DirectoryTree/LdapRecord#648]
Hi @stevebauman 

I need to retrieve account state for a computer. Actually methods ```sDisabled()``` or ```isEnabled()``` doesn't work. The both failed with 
```
Fatal error: Uncaught BadMethodCallException: Call to undefined method LdapRecord\Query\Model\ActiveDirectoryBuilder::isEnabled()
```
It's ture on Computer Model, for example with a result like that, I can't reach "state" of object.
```js
ADAMengine\Models\LdapRecord\Computer {#59
  +exists: true
  +wasRecentlyCreated: false
  +wasRecentlyRenamed: false
[...]
```

Thanks for your help

**Comment by stevebauman** [comment]
Hi @zoriax,

The `ActiveDirectory\Computer` model doesn't have the `userAccountControl` methods that the `ActiveDirectory\User` model does.

Let me patch this! I'll close this out once completed and comment here when released 👍

**Comment by stevebauman** [comment]
Ok I've released a patch for this: https://github.com/DirectoryTree/LdapRecord/releases/tag/v3.1.5

Please run `composer update` and you're all set! Thanks for the report 🙏

**Comment by zoriax** [comment]
Hi @stevebauman !

Thanks for the fix ! All works as expected now ! You are the king !
