### ISSUE TITLE
[Bug] toArray() error on members()

### ISSUE THREAD

**Issue by zoriax** [DirectoryTree/LdapRecord#650]
Hi @stevebauman 

I have an error on Group model with ```members()->get()->toArray()```. It finisehd with 
```
Fatal error: Uncaught Error: Call to a member function toDateTimeString() on bool in \LdapRecord\Traits\ProcessAttributes.php:438 Stack trace: #0
```

As a workaround, this work fine : 
```php
->members()->get()->map(fn($grp) => $grp->name)->toArray()
```

Could you please check that ? 

Thanks !

**Comment by stevebauman** [comment]
Hi @zoriax!

> Fatal error: Uncaught Error: Call to a member function toDateTimeString() on bool in \LdapRecord\Traits\ProcessAttributes.php:438 Stack trace: #0

This trait isn't apart of the LdapRecord package. Is what you've shown the only logic taking place inside?

Also, have you added any additional `$casts` to an LdapRecord model that may be causing this?

**Comment by zoriax** [comment]
Hi @stevebauman,

Sorry for my late answer. You are totally right, the problem was on my own ;-) !

Don't waste your time and sorry for that...

**Comment by stevebauman** [comment]
No worries @zoriax! Appreciate you replying here and closing this out 🙏
