### ISSUE TITLE
[Bug] Groups relation Builder TypeError

### ISSUE THREAD

**Issue by misakstvanu** [DirectoryTree/LdapRecord#655]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.2

**Describe the bug:**
Hi! I am having a curious problem. After upgrading to Ldap Record v3, the query below gives me an error:

`LdapRecord\Query\Model\Builder::newInstance(): Return value must be of type LdapRecord\Query\Model\ActiveDirectoryBuilder, LdapRecord\Query\Model\Builder returned`

on the `whereIn()` - meaning the `groups()` relation resolves into wrong Builder?

```
$roles = LdapRecord\Models\ActiveDirectory\User::where('cn', '=', 'MYNAME')
    ->first()
    ->groups()
    ->whereIn('cn', ['LIST', 'OF', 'GROUPS'])
    ->get();
```

I'm a little lost now. Could you help? Is this a bug? Thanks in advance.

**Comment by stevebauman** [comment]
Hi @misakstvanu,

I'm able to reproduce this thanks! Fixing now 🙏

**Comment by misakstvanu** [comment]
Lovely! Thank you!

**Comment by stevebauman** [comment]
Ok this [has been patched](https://github.com/DirectoryTree/LdapRecord/releases/tag/v3.2.2)! Please run `composer update` and you should be all set 👍
