### ISSUE TITLE
[Support] Password reset behavior

### ISSUE THREAD

**Issue by NeutronSelector** [DirectoryTree/LdapRecord#659]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.2
 - LdapRecord version : 3.2.2

Hi, 

With this code, 
```php
$user = User::query()->where(['samaccountname' => 'test'])->first();
$user->update(['unicodepwd' => 'newTempPassword', 'lockouttime' => 0, 'pwdlastset' => 0]);
```

If pwdlastset already set to 0 (checkbox "User must change password at next logon" is checked), this update set a date in pwdlastset instead 0. 

With this code, pwdlastset is always set to 0
```php
$user->update(['unicodepwd' => 'newTempPassword']);
$user->refresh();
$user->update(['lockouttime' => 0, 'pwdlastset' => 0]);
```

This behavior is the one expected or it's a bug ?
Thanks

**Comment by stevebauman** [comment]
Hi @NeutronSelector,

This is the behaviour of Active Directory. After updating the users password, Active Directory will automatically set the users `pwdlastset` attribute. This is shown in their documentation:

https://learn.microsoft.com/en-us/windows/win32/adschema/a-pwdlastset

![Screenshot 2023-10-17 at 4 19 11 PM](https://github.com/DirectoryTree/LdapRecord/assets/6421846/33138aa7-1e02-4d3e-9354-73b724db8666)

You will have to perform this in two separate calls as you've discovered 👍
