### ISSUE TITLE
[Bug] listing method are missing in v3

### ISSUE THREAD

**Issue by devhubpl** [DirectoryTree/LdapRecord#665]
Used version 3.2.2
`
Call to undefined method LdapRecord\Query\Model\ActiveDirectoryBuilder::listing().
`
Listing methods are missing in the latest version. They are mentioned in the documentation but missing in the code.
I checked v2 and they are there

**Comment by stevebauman** [comment]
Hi @devhubpl,

This method was renamed to "list"' in v3.0 and is mentioned in the upgrade guide here:

https://ldaprecord.com/docs/core/v3/upgrading#ldaprecordquerybuilder-methods-renamed

Could you link me to where you see the method name "listing" in the v3 docs so I can update it?

**Comment by devhubpl** [comment]
Yes, You're right. "list" method is present and it's working.
Thank You for your awesome job.

"listing" method is mentioned in doc in "Searching" section Query Builder and API (Available methods).
Here are links:
[Query Builder - recursive](https://ldaprecord.com/docs/core/v3/searching/#recursive)
[API - listing](https://ldaprecord.com/docs/core/v3/searching-api/#listing)

**Comment by RajcsanyiZ** [comment]
Hi @stevebauman,

The documentation still refers to the lists() method under v3, please fix it!

You might want to mention in the V3 list() method, the LDAP module's LDAP_SCOPE_ONELEVEL options, and in the base example, that LDAP_SCOPE_SUBTREE is the default for the query.

Thanks,
  Zoltán

**Comment by stevebauman** [comment]
Thanks for the reminder! The references have been updated and are now live on the docs site.

https://github.com/DirectoryTree/LdapRecord-Docs/commit/ec20ae11fc9313a332421c3be91be4d81a88792b

> You might want to mention in the V3 list() method, the LDAP module's LDAP_SCOPE_ONELEVEL options, and in the base example, that LDAP_SCOPE_SUBTREE is the default for the query.

This is already present in the Search Options docs:

https://ldaprecord.com/docs/core/v3/searching/#list

> By default, all searches performed are recursive. This means that all nested entries of the base DN will be searched.
