### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by manu144x** [DirectoryTree/LdapRecord#67]
This is not regarding the project, but the documentation, more specific here

https://ldaprecord.com/docs/tutorials/activedirectory/user-management/#creation

There's a typo on the code example to create a new user.

It should be:
`$user->samaccountname` 

instead of `$user->samccountname`

I kept getting _ldap_add(): Add: No such attribute_ and I just couldn't figure it out. As I was a beginner, I didn't know exactly why and how it did that.

After debugging long and hard I found the typo :)

Probably fixing it will help others that are using that same example :)

**Comment by stevebauman** [comment]
Thanks for letting me know @manu144x!

I’ll have that fixed shortly :smile:
