### ISSUE TITLE
[Support] Usage of inside()

### ISSUE THREAD

**Issue by lukas-staab** [DirectoryTree/LdapRecord#670]
**Environment:**
 - LDAP Server Type: OpenLDAP 
 - PHP Version: 8.2

I am unsure if this is a bug, or if I just misunderstood the docs. 
Having: 

```php
    public function save(){
        $c = Committee::findByOrFail('ou', $this->ou);
        $r = new Group([
            'cn' => 'group1,
            'description' => $this->description,
            'uniqueMember' => '',
        ]);
        $r->inside($c);
        $r->save();

        return redirect()->route('committees.roles', ['ou' => $this->ou])
            ->with('message', __('New Role created'));
    }
```

I would *expect* the Role Group below the Committee DN, seems like it is not below, but the exact DN. Am I missing something? The doc was not clear here for me. https://ldaprecord.com/docs/core/v3/model-api/#inside
 
Let the DN of Committee be `ou=com1,dc=local,dc=net`  i would expect that the Group would have the DN `cn=group1,ou=com1,dc=local,dc=net` but instead i just got an error `ldap_add(): Add: Already exists`

**Comment by stevebauman** [comment]
@lukas-staab Nope you're understanding the feature correctly @lukas-staab! That's strange, as I have test cases surrounding this 🤔 

https://github.com/DirectoryTree/LdapRecord/blob/17540a7740964418c1eba251d31369a276a48a76/tests/Unit/Models/ModelTest.php#L139-L160

Could you try dumping the value of `$r->getCreatableDn()` after calling `$r->inside($c)` and see what it's generating?

```php
$c = Committee::findByOrFail('ou', $this->ou);

$r = new Group(['...']);

$r->inside($c);

dd($r->getCreatableDn());
```

**Comment by lukas-staab** [comment]
Huh, strangly i cannot reproduce it. Sorry for the wrong alarm. Closing for now...
