### ISSUE TITLE
[Bug] Missing return type findManyBy()

### ISSUE THREAD

**Issue by surda** [DirectoryTree/LdapRecord#676]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: [8.2]

**Describe the bug:**
Currently LdapRecord\Query\Builder method findManyBy() returns \LdapRecord\Query\Collection.

But it can return \LdapRecord\Query\Collection|array.

**Comment by stevebauman** [comment]
Thanks @surda! Patching now 🙏
