### ISSUE TITLE
[Feature] Disable mandatory TLS connection for localhost

### ISSUE THREAD

**Issue by gaspard-v** [DirectoryTree/LdapRecord#700]
Hello,

Thank you for LdapRecord, it's a great tool and I use it a lot :)

I try to change user password, my PHP server is on the same computer as my OpenLDAP, so my LDAP_HOST is **localhost**.
When I try to change user password, I got an error: "You must be connected to your LDAP server with TLS or SSL to perform this operation."

There's no point to use SSL/TLS on a "localhost" connection.

I'd suggest to skip this SSL/TLS verification if ldap connection is **localhost, 127.0.0.1/8 or ::1**

Thank

**Comment by stevebauman** [comment]
Hi @gaspard-v,

I've just released an update with a new configuration option that disables this check:

```php
$config = [
     'allow_insecure_password_changes' => true,
];
```

Please set this in your LDAP connection configuration and you're all set! 👍

**Comment by gaspard-v** [comment]
thank you!
