### ISSUE TITLE
Unable to find any users but Administrator.

### ISSUE THREAD

**Issue by chetanmadaan** [DirectoryTree/LdapRecord#71]
- LDAP Server Type: **Active Directory**
- PHP Version: 7.3

### Description:
I am able to connect and search the administrator user (the user used to login). But trying to find any other user seems to work.

Below code seems to work just fine.
`// Create a new connection:
$connection = new Connection([
    'hosts' => ['10.2.0.24'],
    'port' => 389,
    'base_dn' => 'DC=common,DC=local',
    'username' => 'CN=Administrator,CN=Users,DC=common,DC=local',
    'password' => '******',
]);

$connection->connect(); 
Container::addConnection($connection); 
$object = Entry::find("cn=Administrator,CN=Users,DC=common,DC=local");`

However, trying to login with any other user even or logging in with administror and trying to find other users' doesn't seem to work.
i.e. Changing the find to:
`$object = Entry::find('cn=username,CN=Users,DC=common,DC=local');`

returns:
`Fatal error: Uncaught ErrorException: ldap_read(): Search: No such object in E:\home\www\test\vendor\directorytree\ldaprecord\src\Connection.php on line 239`

**Comment by chetanmadaan** [comment]
Nevermind, It was invalid CN combination. All is well. Thank you so much for putting together this great PHP library!

**Comment by stevebauman** [comment]
Thanks so much for your kind words @chetanmadaan! :heart: I'm glad you were able to resolve the issue.
