### ISSUE TITLE
Why login return false connection ?

### ISSUE THREAD

**Issue by Mohammed-800** [DirectoryTree/LdapRecord#713]
<img width="726" alt="image" src="https://github.com/DirectoryTree/LdapRecord/assets/78163891/d0ac7712-ca69-48fc-af9e-fe3c16dd6d7e">

**Comment by stevebauman** [comment]
Hi @Mohammed-800,

The username of the user is incorrect. For the forumsys test server, account names have of the attribute of `uid`:

```php
use LdapRecord\Connection;

$conn = new Connection([
    "hosts" => ["ldap.forumsys.com"],
    "username" => "cn=read-only-admin,dc=example,dc=com",
    "password" => "password",
    "base_dn" => "dc=example,dc=com"
]);

$conn->connect();

$conn->auth()->attempt("uid=euler,dc=example,dc=com", "password");
```
