### ISSUE TITLE
[Question] Missing isDisabled() function for AD Users

### ISSUE THREAD

**Issue by opmx** [DirectoryTree/LdapRecord#717]
**Environment:**
 - LDAP Server Type: ActiveDirectory 
 - PHP Version: 8.1
 - Version: ^3.6

**Describe the bug:**
Hey, I'm following the guide to see if an AD account is disabled at https://ldaprecord.com/docs/core/v3/active-directory/users/#checking-user-enablement--disablement and calling if ($user->isDisabled())
 But get the error:

`Fatal error: Uncaught BadMethodCallException: Call to undefined method LdapRecord\Query\Model\Builder::isDisabled()`

I've looked at the source and searched for a function called "isDisabled()" and can't see it.  It was present in LdapRecord\Models\ActiveDirectory back in version 2.

Am I doing something wrong?

**Comment by stevebauman** [comment]
Hi @opmx,

Looks like you're calling `->isDisabled()` on a query builder, not a model instance.

Make sure you're retrieving your user before calling `isDisabled`:

**Single Result**:
```php
$user = User::find('...');

$user->isDisabled();
```

**Multiple Results**:
```php
$users = User::get();

foreach ($users as $user) {
    $user->isDisabled();
}
```
