### ISSUE TITLE
[Feature] `when` on `\LdapRecord\Query\Builder`

### ISSUE THREAD

**Issue by joakimbergros** [DirectoryTree/LdapRecord#730]
Hey,

I'd like to see if adding the `Illuminate\Support\Traits\Conditionable` trait to the `LdapRecord\Query\Builder` class would be of interest?

I find myself liking the fluent syntax over saving the builder to a variable and then use conditionals to mutate the builder if necessary.

```php

use LdapRecord\Models\ActiveDirectory\Group;

$builder = Group::query();

if (true) {
    $builder->where('name', '=', 'test');
}

$result = $builder->get();

```

vs

```php

use LdapRecord\Models\ActiveDirectory\Group;
use LdapRecord\Query\Builder;

$result = Group::query()
    ->when(true, fn (Builder $builder) => $builder->where('name', '=', 'test'))
    ->get();

```

I'd love to hear your thoughts!

I tested this on my own fork and it works nicely, so a PR is ready if you decide it's something you'd want.

Cheers

**Comment by joakimbergros** [comment]
I just noticed it's available as a standalone dependency as well with `illuminate/conditionable`.
It would follow the same structure as `illuminate/collection` and `illuminate/contracts` currently in the `comsposer.json`.

**Comment by joakimbergros** [comment]
I see, that's a bummer. Thanks for taking the time to check at the very least, appreciate it!

Decorator pattern to the rescue :)

**Comment by stevebauman** [comment]
Happy to help! 🙏
