### ISSUE TITLE
While validate or attempt method call. execute inset query by default. how to stop insert(create user) query at validate user.

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [DirectoryTree/LdapRecord#734]
While validate or attempt methods for verifying user credentials. library automatically executes the insert user query and created user. How to stop that?

Code 

```
        $credentials = [
            'samaccountname' => $request['username'],
            'password' => $request['password'],
        ];
        try {
            if (Auth::guard('admin')->attempt($credentials)) { // Automatic execute create query.
                $ldap_user = Auth::guard('admin')->user();
                $user = User::where('email', $ldap_user->email)->first();
                $name = $user->email . '_' . Carbon::now();
                $expiration = Carbon::now()->addDays(1);
                $token = $user->createToken($name, ['*'], $expiration)->plainTextToken;
                return response()->json([
                    'message' =>  __('auth.loginsuccess'),
                    'data' => ['token' => $token],
                ], 201);
            } else {
                return response()->json([
                    'message' => __('auth.failed'),
                ], 401);
            }
        } catch (\Exception $e) {

            return response()->json([
                'message' => $e->getMessage(),
            ], 500);
        }
```

auth.php there are two gard users and admins,

```
 'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
        'admins' => [
            'driver' => 'ldap',
            'model' => LdapRecord\Models\ActiveDirectory\User::class,
            'rules' => [],
            'scopes' => [],
            'database' => [
                'model' => App\Models\User::class,
                'sync_passwords' => false,
                'sync_attributes' => [
                    'name' => 'cn',
                    'username' => 'samaccountname',
                    'email' => 'mail',
                ],
            ],
        ]
],
```

![Screenshot (293)](https://github.com/user-attachments/assets/97040ba1-6ac5-4ca2-a0a5-6d19fe8b447e)

Error 

    "message": "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 

![Screenshot (294)](https://github.com/user-attachments/assets/c8358659-0d74-4b24-9ec5-1171922cb339)

**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.1

**Comment by stevebauman** [comment]
Hi @NALAWALAMURTUZA,

This is how the `database` authentication driver is designed to work. If you don't want users to be imported into your database upon authentication, use the plain authentication driver:

https://ldaprecord.com/docs/laravel/v3/auth/plain

Otherwise, if you want them to be imported and you have existing users inside your database and are seeing a duplicate key exception, you must use the `sync_existing` option:

https://ldaprecord.com/docs/laravel/v3/auth/database/configuration/#sync-existing-records
