### ISSUE TITLE
migrating from adlap2 and $user->inGroup() function

### ISSUE THREAD

**Issue by isaiahfisher** [DirectoryTree/LdapRecord#735]
Hi, I recently migrated an older project from the Adlap2 package. I think I have everything working properly but I cannot seem to find a replacement in the documentation for the previous `inGroup()` function. Here is an example of how I was using the code previously:

```php
use Adldap\Models\User as LdapUser;
...

$user->admin = $ldapUser->inGroup(config('ldap_custom.admin_group'));
```

I am looking to use this function as part of an Attribute Handler to sync down my admin status.

**Comment by stevebauman** [comment]
Hi @isaiahfisher,

LdapRecord uses relationships, similar to Eloquent relationships from Laravel (if you're using it).

I've written docs on group management for users here: 

https://ldaprecord.com/docs/core/v3/active-directory/users/#checking-existence
