### ISSUE TITLE
[Question] Adding a Group in OpenLDAP via Model impossible.

### ISSUE THREAD

**Issue by psuet** [DirectoryTree/LdapRecord#737]
**Environment:**
 - LDAP Server Type: OpenLDAP 2.4.57
 - PHP Version: 8.2.20 

**Describe the bug:**
Adding a Group via the provided LDAP Group Model is impossible. By default OpenLDAP requires a Member in each Group.

When using Group Model to create a Group you get:

```
openldap  | 66e9cc53 conn=1304744 op=5 ADD dn="cn=a,dc=ldap,dc=XXXX,dc=de"
openldap  | 66e9cc53 Entry (cn=a,dc=ldap,dc=XXXX,dc=de): object class 'groupOfUniqueNames' requires attribute 'uniqueMember'
openldap  | 66e9cc53 conn=1304744 op=5 RESULT tag=105 err=65 text=object class 'groupOfUniqueNames' requires attribute 'uniqueMember'
```
Setting a member before saving via 
```
$group->members()->attach($testuser);
```
does not work, because the group doesn't exist yet.

A workaround is manually setting a uniqueMember before saving:

```
$testuser = User::findBy('cn', 'XXX');

$group = (new Group())->inside("dc=groups,cn=a,dc=ldap,dc=XXXX,dc=de");
$group->setAttribute('uniqueMember', $testuser->getDn());
$group->save();
```

This is not really nice style.

**Comment by stevebauman** [comment]
Hi @psuet,

You may use the `associate` method instead of `attach` so that you may add the initial member to a group prior to saving:

```php
$testuser = User::findBy('cn', 'XXX');

$group = (new Group)->inside("dc=groups,cn=a,dc=ldap,dc=XXXX,dc=de");

$group->members()->associate($testuser);

$group->save();
```
