### ISSUE TITLE
[Bug] Undefined array key 1

### ISSUE THREAD

**Issue by vatsake** [DirectoryTree/LdapRecord#738]
**Environment:**
 - LDAP Server Type: ActiveDirectory 
 - PHP Version: 8.3

**Describe the bug:**
After upgrading 
  - Upgrading directorytree/ldaprecord (v3.6.1 => v3.7.0):
  - Upgrading directorytree/ldaprecord-laravel (v3.3.2 => v3.3.4):

I'm getting errors
![image](https://github.com/user-attachments/assets/1c21a3e0-264b-4903-95a9-45893167b75d)
vendor / directorytree / ldaprecord / src / Models / Concerns / HasAttributes .php : 359

```
$ldapUser = LdapUser::query()->where('objectSid', ...)->first();
$ldapUser?->getFirstAttribute('department');

```

```
class LdapUser extends ActiveDirectoryUser
{
    /**
     * The object classes of the LDAP model.
     *
     * @var array
     */
    public static array $objectClasses = [
        'top',
        'person',
        'organizationalperson',
        'user',
    ];
}
```

**Comment by stevebauman** [comment]
Hey @vatsake!

I was able to reproduce this by setting an invalid model cast:

```php
use LdapRecord\Models\ActiveDirectory\User as BaseModel;

class User extends BaseModel
{
    protected array $casts = ['foo' => 'datetime']; // Should be "datetime:<type>"
}

// ...

// Throws exception: Undefined array key 1
(new User)->getFirstAttribute('anything');
```

Do you have any casts that are like this in your models?

If not, I'll need more reproduction steps as I'm not able to reproduce it otherwise.

**Comment by stevebauman** [comment]
Ah okay, yea those should be:

```php
protected array $casts = [
    'accountexpires' => 'datetime:windows-int',
    'whenChanged' => 'datetime:windows',
];
```

A `type` is required because dates and times are stored in various formats in Active Directory (and in LDAP servers in general).

Update your casts and you should be all set, though I have also introduced a new exception to be thrown if this occurs for someone else in the future:

https://github.com/DirectoryTree/LdapRecord/commit/b82df10661aa1ffba2f6fd69d5dec8aa11215f11

```
"Invalid date cast [$cast]. A date cast must be in the format 'datetime:format'
```
