### ISSUE TITLE
[Feature] Add OrderingMatch rule to the orderBy function

### ISSUE THREAD

**Issue by gezadezsi** [DirectoryTree/LdapRecord#744]
Hi guys,

I'm new to this library, just started to implement it in our system and run into an issue:
Unfortunately our LDAP schema doesn't contains the OrderingMatch information and anything which relies on the orderBy function fail. 

This is part of the error message:
`Uncaught ErrorException: ldap_search(): Search: Inappropriate matching`

It would be handy to extend the orderBy functionality to support the Ordering Match flag, right now I overcome this issue by adding the control block to the query itself with the extra flag:

```
$query->addControl(LDAP_CONTROL_SORTREQUEST, true, [
            ['attr' => 'dc','oid'=>'2.5.13.2','reverse' => false],
        ]);

```

Please let me know if there is a better way to achieve this.

Cheers,
Geza

**Comment by gezadezsi** [comment]
Hi @stevebauman ,

It is an OpenLDAP installation (latest debian11 slapd). Not sure why we don't have that schema tag but it's not in my department unfortunately. I'll build my functions with the workaround above, it'd be lovely to have a constant in the configuration or an optional parameter in the orderBy function itself. I'm happy to send a pull request if that helps :)

Cheers,
Geza

**Comment by stevebauman** [comment]
Ok great thanks for the info!

You can submit a PR if you'd like! No obligations though.

Either way, I'll work on this later in the week (travelling back from vacation as we speak).

**Comment by stevebauman** [comment]
Hey @gezadezsi! I've just finished adding the capability of providing the `oid` you need in the `orderBy` method:

```php
$query->orderBy('dc', 'asc', ['oid' => '2.5.13.2']);

$query->orderByDesc('dc', ['oid' => '2.5.13.2']);
```

You're all set 👍
