### ISSUE TITLE
[Feature] Support for milliseconds format windows time

### ISSUE THREAD

**Issue by peteher** [DirectoryTree/LdapRecord#745]
Setting up integration with [OKTA](https://www.okta.com) (OpenLDAP).

OKTA provides `createTimestamp` and `modifyTimestamp` in the format of `20241107181210.000Z`.

The library has support for [`windows`](https://github.com/DirectoryTree/LdapRecord/blob/207c7273f3aa872606406194bbe4e304e87ed9b6/src/Models/Attributes/Timestamp.php#L15) time in the format of `'YmdHis.0Z'` [ref](https://github.com/DirectoryTree/LdapRecord/blob/207c7273f3aa872606406194bbe4e304e87ed9b6/src/Models/Attributes/Timestamp.php#L152C42-L152C54) however the additional two`00` produced by Okta in the millisecond position is not decoded when using [`getAttribute`](https://ldaprecord.com/docs/core/v3/models/#methods) method, rather null value is provided.

Feature request is to parse the millisecond format regardless if `.0Z` or `.000Z` (ie: `YmdHis.000\Z`) is provided, given we already define that the data source responds with [`windows`](https://github.com/DirectoryTree/LdapRecord/blob/207c7273f3aa872606406194bbe4e304e87ed9b6/src/Models/Concerns/HasAttributes.php#L58) format and not the default `ldap`.
Maybe create yet another Windows time format?
Thank you!

**Comment by stevebauman** [comment]
Hey @peteher, since this is an OpenLDAP timestamp, I think this should be handled under the `ldap` timestamp type and not Windows. Doing so may cause confusion for other developers since they aren't connecting to a Windows based LDAP server. Have a PR open for this. Will close this once released 👍

**Comment by stevebauman** [comment]
Released -- run `composer update` and you're all set. Your models will using this timestamp format will need to use the `ldap` type, btw!
