### ISSUE TITLE
[Bug] Infinite loop in LdapRecord\Models\Collection::contains function

### ISSUE THREAD

**Issue by sahopp** [DirectoryTree/LdapRecord#746]
**Environment:**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 8.3

**Describe the bug:**
There seems to be a bug yielding an infinite loop in the `contains` function of `LdapRecord\Models\Collection`.
(I'm observing this in a Laravel 11 application, but I report it in this repository since the Collection implementation is here).

**Reproduction:**
Create an LdapRecord\Models\Collection containing one or more instances of an LdapRecord model.
Then, execute the `contain` function to check if the collection contains a certain `$key`, `$operator`, `$value` triple.
```php
# Assume $coll is an LdapRecord\Models\Collection containing at least one model instance.
if ($coll->contains('givenname', '=', 'John')) {
    echo "Collection contains a user with name 'John'.";
} else {
    echo "Collection does not contain a user with name 'John'.";
}
```
This will yield an infinite loop.

**Reason**
In `LdapRecord\Models\Collection::contains`, we have
```php
        if (func_num_args() > 1 || $key instanceof Closure) {
            // If we are supplied with more than one argument, or
            // we were passed a closure, we will utilize the
            // parents contains method, for compatibility.
            return parent::contains($key, $operator, $value);
        }
...
```
Hence, even if our `$key` parameter is already a Closure, we call parent::contains (i.e. `Illuminate\Support\Collection::contains`) with 3 parameters (two of them being `null`). We therefore never enter the `if`-block `if (func_num_args() === 1)` in `Illuminate\Support\Collection::contains`. Therefore, `Illuminate\Support\Collection::contains` always returns `$this->contains($this->operatorForWhere(...func_get_args()))`. This again calls `LdapRecord\Models\Collection:contains`, which in turns again calls `Illuminate\Support\Collection::contains` with 3 parameters.

**Possible solution**
A possible solution might be to adjust `LdapRecord\Models\Collection::contains`:
```diff
- parent::contains($key, $operator, $value);
+ parent::contains(...func_get_args());
```

This at least breaks the infinite loop and seems to work in my case. It needs to be ensured that this has no other side effects.

**Addition**
Another issue is that `LdapRecord\Models\Collection::contains` would act more naturally if one can use a string as `$value`. Now we need to pass an array which exactly matches the array of values in the model. If an attribute can have multiple values, I can't easily check whether the collection has a model where the attribute has a certain value (possibly one of multiple values). e.g., if a user can have multiple values for `email`,
```php
# I can't make
$coll->contains('email', '=', 'john@myorg.com');

# I need to make
$coll->contains('email', '=', ['john@myorg.com']);
```
And this only works if the user has only one email.
But this could be a feature request.

**Comment by stevebauman** [comment]
Hey @sahopp, thanks a ton for the detailed issue! Much appreciated 🙏 

I've patched this with your suggestion and added a bunch of tests to ensure it's good to go. Run `composer update` to get it.

Though in regards to this:

> **Addition**
> Another issue is that `LdapRecord\Models\Collection::contains` would act more naturally if one can use a string as `$value`. Now we need to pass an array which exactly matches the array of values in the model. If an attribute can have multiple values, I can't easily check whether the collection has a model where the attribute has a certain value (possibly one of multiple values). e.g., if a user can have multiple values for `email`,
> ```php
> # I can't make
> $coll->contains('email', '=', 'john@myorg.com');
> 
> # I need to make
> $coll->contains('email', '=', ['john@myorg.com']);
> ```
> And this only works if the user has only one email.
> But this could be a feature request.

I don't personally agree on this, because the `=` operator should indicate that the whole attribute must equal the value given. If you need to perform an `in_array` check, you can use a closure instead:

```php
$coll->contains(function (Model $model) {
    return in_array('john@myorg.com', $model->email ?? []);
});
```
