### ISSUE TITLE
Creating Users on Ldap 

### ISSUE THREAD

**Issue by SuseelKc** [DirectoryTree/LdapRecord#751]
I am trying to connect to ldap server using ldaps for user creation  on port 636. I am facing issues in connection 389 works but at 636 using ssl i couldnt connect succesfully.
I am on testing environment and in ldap server i have added roles and feature (Active Directory certificate services )  install certificate authority 
https://www.youtube.com/watch?v=xC3ujXGkh_c&t=305s
as of above and tested connection on ldp.exe on that ip address i get unsuccesful conn but on domaiin i get succesful connection 
and in 
.env of laravel i placed the 636 and  domain on ldap host there is unsuccesful connection
Help in here to achieve the user creation

**Comment by stevebauman** [comment]
Hi @SuseelKc,

Please read the debugging guide: https://ldaprecord.com/docs/laravel/v3/debugging/#debugging
