### ISSUE TITLE
Unable to install and run LdapRecord

### ISSUE THREAD

**Issue by Beko67** [DirectoryTree/LdapRecord#84]
Hi,

I try to use LdapRecord instead of adLdap, so, I upgrade my PHP version from 7.0 to 7.4.

After that, I enabled the ldap extension in php.ini.

And finally, I "tried" to installed LdapRecord with the command : "composer require directorytree/ldaprecord" (Composer already installed).

I get this messages after installing : 

```
root : composer require directorytree/ldaprecord

PHP Warning:  Module 'ldap' already loaded in Unknown on line 0
Using version ^1.2 for directorytree/ldaprecord
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing symfony/translation-contracts (v2.0.1): Downloading (100%)
  - Installing symfony/translation (v5.0.4): Downloading (100%)
  - Installing nesbot/carbon (2.30.0): Downloading (100%)
  - Installing directorytree/ldaprecord (v1.2.3): Downloading (100%)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
symfony/translation suggests installing psr/log-implementation (To use logging capability in translator)
Writing lock file
Generating autoload files
```

But I'm now stuck, I don't know how to use it.

Is the installation is correct ?

I have a composer.json on my /root/ folder and my web project is on /var/www/html/ folder.

I don't know what the step after that, can someone explain to me please ?

Thank you !

**Comment by stevebauman** [comment]
Hi @Beko67,

It looks like you may have enabled the LDAP extension twice in your `php.ini` file. Please check that file and ensure it is only listed once.

Also, make sure that your composer installation on your computer is pointing to the same exact PHP version you are using on your local web server. If you're unsure, simply uninstall composer, reinstall, and make sure it shows PHP 7.4 as being the selected binary to use.

In regards to your question, there's tons of documentation to get up an running. Please look at the docs as it goes through installation, configuration, and usage:

https://ldaprecord.com/docs/installation/

**Comment by stevebauman** [comment]
Also, the installation of LdapRecord was successful. Inside of your log - that error you seeing is simply informing you that the LDAP extension is being loaded again when it has already been loaded.
