### ISSUE TITLE
ErrorException when using a Class Based Listener

### ISSUE THREAD

**Issue by eac0n** [DirectoryTree/LdapRecord#86]
**Describe the bug**
Using a non static `handle`-method with a class based listener, like described in the [docs](https://ldaprecord.com/docs/events/#events), causes an `ErrorException`:
**call_user_func_array() expects parameter 1 to be a valid callback, non-static method MyApp\BindingEventHandler::handle() should not be called statically**

**To Reproduce**
1. Create an `EventHandler` class with a non static `handle`-method
   ```php
   namespace MyApp;

   use LdapRecord\Auth\Events\Binding;

   class BindingEventHandler
   {
       public function handle( Binding $event )
       {
           // Handle the event...
       }
   }
   ```
1. Register the `EventHandler` to the dispatcher using the class based way
   ```php
   $dispatcher = \LdapRecord\Container::getEventDispatcher();
   $dispatcher->listen(Binding::class, MyApp\BindingEventHandler::class);
   ```

**Expected behavior**
The `handle`-method should be able to be non static or the docs should mention the method requires to be `static`.

**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.4.3
 - Laravel Version: 7.0.4

**Comment by stevebauman** [comment]
Fixed. New release will be out shortly!
