### ISSUE TITLE
Unable to Create Organizational Unit

### ISSUE THREAD

**Issue by aleksanderalright** [DirectoryTree/LdapRecord#88]
I am unsure of whether this is intentional or not, but I can't make an Organizational Unit through LDAP Record. (I can make a User just fine, and add it to an existing OU too.)

`$ou = new OrganizationalUnit(['ou' => $name, ]);
(...)
$ou->save();`

When running the above code, the following error is thrown by LDAP Record:
_A new LDAP entry must contain an object class (objectclass) and common name (cn)._

When changing the code that checks for a cn and throws the error, the OU is made as expected, and seems to works fine (I can also add users to it).
Side note: The followig code is only a quickfix, and might cause other issues.

in ldaprecord\src\Query\Builder.php

`
public function insert($dn, array $attributes)
{
    if (empty($dn)) {
        throw new Exception('A new LDAP entry must have a distinguished name (dn).');
    }

    if (!in_array('organizationalunit', $attributes['objectclass']) && (!array_key_exists('objectclass', $attributes) || !array_key_exists('cn', $attributes))) {
        throw new Exception(
           'A new LDAP entry must contain an object class (objectclass) and common name (cn).'
        );
    }

    return $this->connection->run(function (Ldap $ldap) use ($dn, $attributes) {
        return $ldap->add($dn, $attributes);
    });
} 
`

**Expected behavior**
I would expect to be able to make an OU in some way. Perhaps I am simply overlooking the correct way, but I could not find it in the documentation, nor does there seem to be any other insert function.

**Environment**
 - LDAP Server Type: OpenLDAP
 - PHP Version: 7.4

**Comment by stevebauman** [comment]
This is a bug - there should only be validation on the `objectclass` attribute as it is the only attribute that must be present to create an object in a directory. Thanks for the report!

Fixing this right now :smile:

**Comment by stevebauman** [comment]
Ok new release is out with this fix - [v1.2.9](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.2.9). Run `composer update` in a few minutes and you're good to go :smile:
