### ISSUE TITLE
AccountControl

### ISSUE THREAD

**Issue by ellisonpatterson** [DirectoryTree/LdapRecord#90]
The `AccountControl` trait is great, but I'm wondering if for user attributes, the `useraccountcontrol` attribute could be parsed and included with the user model (it could even be deferred until called) so I can, for example, check if a user cannot change their password without having to parse the flags myself. It seems the `AccountControl` trait is only for setting the flags currently.

Thanks!

**Comment by ellisonpatterson** [comment]
Eh well I guess you can just do this:
```
$passwordNeverExpires = (new AccountControl($user->getFirstAttribute('useraccountcontrol')))->has(AccountControl::DONT_EXPIRE_PASSWORD);
```

**Comment by stevebauman** [comment]
Hi @ellisonpatterson,

You should be able to actually do this now by adding an [accessor](https://ldaprecord.com/docs/model-mutators/#defining-an-accessor) to your `User` model for the `userAccountControl` attribute:

```php
use LdapRecord\Models\Attributes\AccountrControl;
use LdapRecord\Models\ActiveDirectory\User as BaseUser;

class User extends BaseUser
{
    public function getUseraccountcontrolAttribute($value)
    {
        return new AccountControl($value);
    }
}
```

**Note**: The casing of the above method (`getUseraccountcontrolAttribute` is important).

```php
$user = User::findByAnr('sbauman');

$passwordNeverExpires = $user->userAccountControl->has(AccountControl::DONT_EXPIRE_PASSWORD);
```

Can you give that a shot?

**Comment by ellisonpatterson** [comment]
> 
> 
> Hi @ellisonpatterson,
> 
> You should be able to actually do this now by adding an [accessor](https://ldaprecord.com/docs/model-mutators/#defining-an-accessor) to your `User` model for the `userAccountControl` attribute:
> 
> ```
> use LdapRecord\Models\Attributes\AccountrControl;
> use LdapRecord\Models\ActiveDirectory\User as BaseUser;
> 
> class User extends BaseUser
> {
>     public function getUseraccountcontrolAttribute($value)
>     {
>         return new AccountControl($value[0] ?? null);
>     }
> }
> ```
> 
> **Note**: The casing of the above method (`getUseraccountcontrolAttribute` is important).
> 
> ```
> $user = User::findByAnr('sbauman');
> 
> $passwordNeverExpires = $user->userAccountControl->has(AccountControl::DONT_EXPIRE_PASSWORD);
> ```
> 
> Can you give that a shot?

Yeah that is a better method, but it seems that the `PASSWD_CANT_CHANGE` property flag cannot be changed by modifying the `useraccountcontrol` attribute, but could it be added to the `AccountControl` class as a constant, just so one could reference it without having to type in its' decimal? It seems it's 64. https://support.microsoft.com/en-us/help/305144/how-to-use-useraccountcontrol-to-manipulate-user-account-properties

**Comment by stevebauman** [comment]
Oh wow I actually didn't know I missed this flag! We can definitely add this in. If you'd like to submit a PR, I can accept it right now, otherwise I will have this done by end of the day.

Thanks for the report :smile:

**Comment by ellisonpatterson** [comment]
> 
> 
> Oh wow I actually didn't know I missed this flag! We can definitely add this in. If you'd like to submit a PR, I can accept it right now, otherwise I will have this done by end of the day.
> 
> Thanks for the report 😄

Alright done! And thank you for making this awesome tool!

**Comment by stevebauman** [comment]
Perfect, and glad you find it useful, thanks for your support :smile:

As soon as the tests pass, I'll create a new version.
