### ISSUE TITLE
AccountControl const ACCOUNTDISABLE

### ISSUE THREAD

**Issue by bezops** [DirectoryTree/LdapRecord#92]
The const ACCOUNTDISABLE is currently set to 2, but is this an accurate check?

`if ($uac->has(AccountControl::ACCOUNTDISABLE)) {
    // This account is disabled.`

According to [MS](https://support.microsoft.com/en-au/help/305144/how-to-use-useraccountcontrol-to-manipulate-user-account-properties), flags are cumulative.

_To disable a user's account, set the UserAccountControl attribute to 0x0202 (0x002 + 0x0200). In decimal, this is 514 (2 + 512)._

ie. Flag (512) NORMAL_ACCOUNT with Flag (2) ACCOUNTDISABLE

This can also be seen from from the snippet of a standard query:

`            [useraccountcontrol] => Array
                (
                    [0] => 514
                )`

Should the value of 514 also be added as a valid constant to compare against or is there a better way to check for disabled accounts?

**Comment by stevebauman** [comment]
Hi @bezops,

> The const ACCOUNTDISABLE is currently set to 2, but is this an accurate check?

I don't see any issue with it. If the `ACCOUNTDISABLE` flag exists on the account control, then it is a disabled account.

If you'd prefer to do it in a more strict manor, simply check the existence of both flags:

```php
if (
    $uac->has(AccountControl::ACCOUNTDISABLE) && 
    $uac->has(AccountControl::NORMAL_ACCOUNT)
) {
    //
}
```

I don't think we should add another constant. Any combinations needed can be summed pretty easily.

I think we should stick with the flags provided directly from Microsoft and stay as close as possible to their implementation.

**Comment by stevebauman** [comment]
For another example, this will print "Account is normal and disabled.":

```php
use LdapRecord\Models\Attributes\AccountControl;

$ac = new AccountControl(514);

if (
    $ac->has(AccountControl::ACCOUNTDISABLE) &&
    $ac->has(AccountControl::NORMAL_ACCOUNT)
) {
    echo "Account is normal and disabled.";
}

**Comment by bezops** [comment]
Thanks @stevebauman ,

Didn't realise the flags could be simply summed in this manner, makes sense now!

**Comment by stevebauman** [comment]
No worries! You can sum any combination and then add it into the `AccountControl` constructor. It will extract each flag for you and you can check their existence.

If you have any further questions feel free to create another issue :smile:
