### ISSUE TITLE
Issue to few arguments to setAttribute()

### ISSUE THREAD

**Issue by mstoicaixia** [DirectoryTree/LdapRecord#94]
I encounter the following error when I try to connect with Ldap and sync the user in the local database.
Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in [2020-03-25 11:51:56] local.INFO: User [mastoica] has been successfully located for authentication.  
[2020-03-25 11:51:56] local.INFO: User [mastoica] is being imported.  
[2020-03-25 11:51:56] local.INFO: User [mastoica] is being synchronized.  
[2020-03-25 11:51:56] local.ERROR: Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 674 and exactly 2 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Illuminate\\Database\\Eloquent\\Model::setAttribute(), 1 passed in /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 674 and exactly 2 expected at /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:616)
[stacktrace]
#0 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(674): Illuminate\\Database\\Eloquent\\Model->setAttribute('IHzTkhMigIYSs69...')
#1 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(622): Illuminate\\Database\\Eloquent\\Model->setMutatedAttributeValue(NULL, 'IHzTkhMigIYSs69...')
#2 /Users/mastoica/Sites/woc/laravel-woc/vendor/directorytree/ldaprecord-laravel/src/LdapUserImporter.php(179): Illuminate\\Database\\Eloquent\\Model->setAttribute(NULL, 'IHzTkhMigIYSs69...')
#3 /Users/mastoica/Sites/woc/laravel-woc/vendor/directorytree/ldaprecord-laravel/src/LdapUserImporter.php(74): LdapRecord\\Laravel\\LdapUserImporter->setPassword(Object(App\\User), 'IHzTkhMigIYSs69...')
#4 /Users/mastoica/Sites/woc/laravel-woc/vendor/directorytree/ldaprecord-laravel/src/Auth/DatabaseUserProvider.php(108): LdapRecord\\Laravel\\LdapUserImporter->run(Object(LdapRecord\\Models\\ActiveDirectory\\User), 'IHzTkhMigIYSs69...')
#5 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(357): LdapRecord\\Laravel\\Auth\\DatabaseUserProvider->retrieveByCredentials(Array)
#6 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/ui/auth-backend/AuthenticatesUsers.php(83): Illuminate\\Auth\\SessionGuard->attempt(Array, false)
#7 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/ui/auth-backend/AuthenticatesUsers.php(46): App\\Http\\Controllers\\Auth\\LoginController->attemptLogin(Object(Illuminate\\Http\\Request))
#8 [internal function]: App\\Http\\Controllers\\Auth\\LoginController->login(Object(Illuminate\\Http\\Request))
#9 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#10 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('login', Array)
#11 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(225): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\LoginController), 'login')
#12 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(182): Illuminate\\Routing\\Route->runController()
#13 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#14 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/mastoica/Sites/woc/laravel-woc/vendor/fruitcake/laravel-cors/src/HandleCors.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Users/mastoica/Sites/woc/laravel-woc/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /Users/mastoica/Sites/woc/laravel-woc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#49 /Users/mastoica/Sites/woc/laravel-woc/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#50 /Users/mastoica/Sites/woc/laravel-woc/server.php(21): require_once('/Users/mastoica...')
#51 {main}
"}

**Comment by stevebauman** [comment]
Going to need much more detail than this.

Please post your `config/auth.php` filez

**Comment by mstoicaixia** [comment]
Indeed the error was from the config/auth.php. Now I have managed to solve this by changing the ldap provider to:
'ldap' => [
            'driver' => 'ldap',
            'model' => LdapRecord\Models\ActiveDirectory\User::class,
            'rules' => [],
            'database' => [
                'model' => App\User::class,
                'sync_passwords' => true,
                'sync_attributes' => [
                    'name' => 'displayname',
                    'email' => 'mail',
                    'phone' => 'telephonenumber',
                    App\Ldap\AttributeHandler::class,
                ],
            ],
        ],

when it gave the error the sync_passwords was set to false and password_column to null(as I had no password field in my users table).
Now I have created passwords field into my table and I've choose to save it locally in my database as well and it is working.

**Comment by stevebauman** [comment]
Thanks for following up so fast @mstoicaixia, I'm glad you resolved the issue. LdapRecord-Laravel should allow you to use no password column though, let me make sure this is the case.
