### ISSUE TITLE
Query is not cached and DateTime as a parameter is wrong

### ISSUE THREAD

**Issue by lucraraujo** [DirectoryTree/LdapRecord#96]
**Describe the bug**
So, I found 2 problems with caching.
1) The Query class, when it is instantiated, the cache attribute is not initiated, even if the connection object have a cache object.
2) The 'until' parameter on the 'cache' method on the Query class MUST BE null|int|DateInterval because the Psr\SimpleCache\CacheInterface::set() signature says so.

**To Reproduce**
Execute the code.
[cacheBug.zip](https://github.com/DirectoryTree/LdapRecord/files/4411714/cacheBug.zip)

**Expected behavior**
The cache should be created and the TTL should be set.

**Environment**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 7.4.4

**Comment by lucraraujo** [comment]
The second problem reported will be fixed just by changing the method signature on the line
https://github.com/DirectoryTree/LdapRecord/blob/master/src/Query/Builder.php#L1526 to the same on the PSR16 CacheInterface::set.

The first problem reported can be solver by using the cache attribute on the Connection class or setting the cache attribute on the Builder class on the constructor with the same set on the Connection class.
https://github.com/DirectoryTree/LdapRecord/blob/master/src/Query/Builder.php#L122

**Comment by stevebauman** [comment]
Thanks @lucraraujo, going to look at this shortly.

**Comment by lucraraujo** [comment]
@stevebauman I'm already looked at the problems and I can open a PR soon with the changes that I think will solve the problems.
The only thing that I'm struggling are the tests, or who to test with cache.

**Comment by stevebauman** [comment]
Sounds good! 👌 Will await your PR.

**Comment by lucraraujo** [comment]
So... Before starting to work on the fix, I did what ever dev should do first. Run the tests.
And, since I live in Brazil, I have my timezone set to "America/Sao_Paulo" (GMT-3), and, some tests broke, since the timezone the tests are expecting is GMT+0. I will check this problem with the tests first and them I will try to create at least 1 test to fix the bugs.

**Comment by stevebauman** [comment]
You must have that set inside of your `php.ini` I'm guessing? You may have to add `date_default_timezone_set('UTC')` to the `TestCase::setUp` method.

**Comment by lucraraujo** [comment]
Yes, you guessed right, and it worked like a charm! Can I leave that piece of code in the TestCase::setUp?

**Comment by stevebauman** [comment]
You can leave it in there and I'll remove it afterwards 👍

**Comment by stevebauman** [comment]
Fixed in [v1.2.12](https://github.com/DirectoryTree/LdapRecord/releases/tag/v1.2.12). Thanks! 👍
