### ISSUE TITLE
Issue calling groups() relationship method

### ISSUE THREAD

**Issue by ctyler69** [DirectoryTree/LdapRecord#97]
I seem to be having an use with calling the groups() relationship method.

I created my LDAP User model and extended it 
```
use LdapRecord\Models\ActiveDirectory\User as BaseModel;
class User extends BaseModel
```
If I search for a user like so:

```
$user = User::find('CN=Tyler\, Casey,CN=Users,DC=comlivserv,DC=com');
```
I can get all of the groups the user belongs to like this:

```
dd($user->getAttribute('memberof'));
```
However, when I call $user->groups()->get() I get an emtpty collection. I also tried calling $user->groups() and  $user->groups.

If I look at the vendor/directorytree/ldaprecord/src/Models/ActiveDirectory/User.php the relationship is defined like this:

```
public function groups()
    {
        return $this->hasMany(Group::class, 'member');
    }
```

So I thought maybe the attribute it was using ('member') was wrong so I changed it with an override to:

```
public function groups()
    {
        return $this->hasMany(Group::class, 'memberof');
    }
```
Same result - empty Collection. 

Any ideas what could be causing this?

 - ActiveDirectory 
 - PHP 7.3 
 - Laravel Version: 7.0

**Comment by stevebauman** [comment]
I'm able to reproduce this perfectly by setting an incorrect `base_dn` inside of my connections configuration.

**Comment by ctyler69** [comment]
```
<?php

namespace App\Ldap;

use App\Ldap\Scopes\RealUsers;
use LdapRecord\Models\ActiveDirectory\Group;
use LdapRecord\Models\ActiveDirectory\User as BaseModel;


class User extends BaseModel
{
    /**
     * The object classes of the LDAP model.
     *
     * @var array
     */
    public static $objectClasses = [
        'top',
        'person',
        'organizationalperson',
        'user',
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new RealUsers);
    }

    public function groups()
    {
        return $this->hasMany(Group::class, 'member');
    }

}

```

**Comment by stevebauman** [comment]
If you call `\App\Ldap\User::get()`, do you get any results? Also, is your in your `base_dn` inside of your configuration correct?

**Comment by ctyler69** [comment]
@stevebauman 
When I call 
```
$users = \App\Ldap\User::get();
        dd($users);
```
I get
```
LdapRecord\Query\Collection {#343 ▼
  #items: array:161 [▶]
}
```
That is  correct and that is including the global scope as well. 

The base_dn is correct.

**Comment by ctyler69** [comment]
Also this is working:
$user = User::find('CN=Tyler\, Casey,CN=Users,DC=comlivserv,DC=com');
dd($user->manager()->get());

**Comment by stevebauman** [comment]
Can you remove this line and try again?

```php
static::addGlobalScope(new RealUsers);
```

**Comment by ctyler69** [comment]
@stevebauman 
BINGO!
$user = User::find('CN=Tyler\, Casey,CN=Users,DC=comlivserv,DC=com');
dd($user->groups()->get());
That is now pulling in all the groups for the user.
So. How should I proceed with the global scope?

**Comment by stevebauman** [comment]
Ah perfect, okay I know what's going on -- this is a bug. Thanks! :smile:

Global scopes should be removed from relationship queries automatically. Right now, this is not being done:

https://github.com/DirectoryTree/LdapRecord/blob/6e15b621741e70f35d3e02a8d2b4668f5f1dc1ab/src/Models/Relations/Relation.php#L166-L171

Going to patch this now.

**Comment by stevebauman** [comment]
Fixed - new release will be out shortly, thanks for the report! :smile:

**Comment by ctyler69** [comment]
Thank you @stevebauman 
Works perfectly!
